// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

/**
 * <pre>
 * FullSync carries exactly the registered servers, so a reconnect during a
 * drain cannot undo a deregistration.
 * </pre>
 *
 * Protobuf type {@code spawnery.agent.v1alpha1.FullSync}
 */
@com.google.protobuf.Generated
public final class FullSync extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:spawnery.agent.v1alpha1.FullSync)
    FullSyncOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "FullSync");
  }
  // Use FullSync.newBuilder() to construct.
  private FullSync(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private FullSync() {
    servers_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_FullSync_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_FullSync_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_FullSync_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.spawnery.agent.pb.FullSync.class, cloud.spawnery.agent.pb.FullSync.Builder.class);
  }

  public static final int SERVERS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<cloud.spawnery.agent.pb.RegisteredServer> servers_;
  /**
   * <code>repeated .spawnery.agent.v1alpha1.RegisteredServer servers = 1;</code>
   */
  @java.lang.Override
  public java.util.List<cloud.spawnery.agent.pb.RegisteredServer> getServersList() {
    return servers_;
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.RegisteredServer servers = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends cloud.spawnery.agent.pb.RegisteredServerOrBuilder> 
      getServersOrBuilderList() {
    return servers_;
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.RegisteredServer servers = 1;</code>
   */
  @java.lang.Override
  public int getServersCount() {
    return servers_.size();
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.RegisteredServer servers = 1;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.RegisteredServer getServers(int index) {
    return servers_.get(index);
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.RegisteredServer servers = 1;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.RegisteredServerOrBuilder getServersOrBuilder(
      int index) {
    return servers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < servers_.size(); i++) {
      output.writeMessage(1, servers_.get(i));
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;

        {
          final int count = servers_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(servers_.get(i));
          }
          size += 1 * count;
        }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.spawnery.agent.pb.FullSync)) {
      return super.equals(obj);
    }
    cloud.spawnery.agent.pb.FullSync other = (cloud.spawnery.agent.pb.FullSync) obj;

    if (!getServersList()
        .equals(other.getServersList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getServersCount() > 0) {
      hash = (37 * hash) + SERVERS_FIELD_NUMBER;
      hash = (53 * hash) + getServersList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.spawnery.agent.pb.FullSync parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.FullSync parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.FullSync parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.FullSync parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.FullSync parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.FullSync parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.FullSync parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.FullSync parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.spawnery.agent.pb.FullSync parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.spawnery.agent.pb.FullSync parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.FullSync parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.FullSync parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.spawnery.agent.pb.FullSync prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * FullSync carries exactly the registered servers, so a reconnect during a
   * drain cannot undo a deregistration.
   * </pre>
   *
   * Protobuf type {@code spawnery.agent.v1alpha1.FullSync}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:spawnery.agent.v1alpha1.FullSync)
      cloud.spawnery.agent.pb.FullSyncOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_FullSync_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_FullSync_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.spawnery.agent.pb.FullSync.class, cloud.spawnery.agent.pb.FullSync.Builder.class);
    }

    // Construct using cloud.spawnery.agent.pb.FullSync.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (serversBuilder_ == null) {
        servers_ = java.util.Collections.emptyList();
      } else {
        servers_ = null;
        serversBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_FullSync_descriptor;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.FullSync getDefaultInstanceForType() {
      return cloud.spawnery.agent.pb.FullSync.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.FullSync build() {
      cloud.spawnery.agent.pb.FullSync result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.FullSync buildPartial() {
      cloud.spawnery.agent.pb.FullSync result = new cloud.spawnery.agent.pb.FullSync(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(cloud.spawnery.agent.pb.FullSync result) {
      if (serversBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          servers_ = java.util.Collections.unmodifiableList(servers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.servers_ = servers_;
      } else {
        result.servers_ = serversBuilder_.build();
      }
    }

    private void buildPartial0(cloud.spawnery.agent.pb.FullSync result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.spawnery.agent.pb.FullSync) {
        return mergeFrom((cloud.spawnery.agent.pb.FullSync)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.spawnery.agent.pb.FullSync other) {
      if (other == cloud.spawnery.agent.pb.FullSync.getDefaultInstance()) return this;
      if (serversBuilder_ == null) {
        if (!other.servers_.isEmpty()) {
          if (servers_.isEmpty()) {
            servers_ = other.servers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureServersIsMutable();
            servers_.addAll(other.servers_);
          }
          onChanged();
        }
      } else {
        if (!other.servers_.isEmpty()) {
          if (serversBuilder_.isEmpty()) {
            serversBuilder_.dispose();
            serversBuilder_ = null;
            servers_ = other.servers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            serversBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetServersFieldBuilder() : null;
          } else {
            serversBuilder_.addAllMessages(other.servers_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              cloud.spawnery.agent.pb.RegisteredServer m =
                  input.readMessage(
                      cloud.spawnery.agent.pb.RegisteredServer.parser(),
                      extensionRegistry);
              if (serversBuilder_ == null) {
                ensureServersIsMutable();
                servers_.add(m);
              } else {
                serversBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<cloud.spawnery.agent.pb.RegisteredServer> servers_ =
      java.util.Collections.emptyList();
    private void ensureServersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        servers_ = new java.util.ArrayList<cloud.spawnery.agent.pb.RegisteredServer>(servers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.spawnery.agent.pb.RegisteredServer, cloud.spawnery.agent.pb.RegisteredServer.Builder, cloud.spawnery.agent.pb.RegisteredServerOrBuilder> serversBuilder_;

    /**
     * <code>repeated .spawnery.agent.v1alpha1.RegisteredServer servers = 1;</code>
     */
    public java.util.List<cloud.spawnery.agent.pb.RegisteredServer> getServersList() {
      if (serversBuilder_ == null) {
        return java.util.Collections.unmodifiableList(servers_);
      } else {
        return serversBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RegisteredServer servers = 1;</code>
     */
    public int getServersCount() {
      if (serversBuilder_ == null) {
        return servers_.size();
      } else {
        return serversBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RegisteredServer servers = 1;</code>
     */
    public cloud.spawnery.agent.pb.RegisteredServer getServers(int index) {
      if (serversBuilder_ == null) {
        return servers_.get(index);
      } else {
        return serversBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RegisteredServer servers = 1;</code>
     */
    public Builder setServers(
        int index, cloud.spawnery.agent.pb.RegisteredServer value) {
      if (serversBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServersIsMutable();
        servers_.set(index, value);
        onChanged();
      } else {
        serversBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RegisteredServer servers = 1;</code>
     */
    public Builder setServers(
        int index, cloud.spawnery.agent.pb.RegisteredServer.Builder builderForValue) {
      if (serversBuilder_ == null) {
        ensureServersIsMutable();
        servers_.set(index, builderForValue.build());
        onChanged();
      } else {
        serversBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RegisteredServer servers = 1;</code>
     */
    public Builder addServers(cloud.spawnery.agent.pb.RegisteredServer value) {
      if (serversBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServersIsMutable();
        servers_.add(value);
        onChanged();
      } else {
        serversBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RegisteredServer servers = 1;</code>
     */
    public Builder addServers(
        int index, cloud.spawnery.agent.pb.RegisteredServer value) {
      if (serversBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServersIsMutable();
        servers_.add(index, value);
        onChanged();
      } else {
        serversBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RegisteredServer servers = 1;</code>
     */
    public Builder addServers(
        cloud.spawnery.agent.pb.RegisteredServer.Builder builderForValue) {
      if (serversBuilder_ == null) {
        ensureServersIsMutable();
        servers_.add(builderForValue.build());
        onChanged();
      } else {
        serversBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RegisteredServer servers = 1;</code>
     */
    public Builder addServers(
        int index, cloud.spawnery.agent.pb.RegisteredServer.Builder builderForValue) {
      if (serversBuilder_ == null) {
        ensureServersIsMutable();
        servers_.add(index, builderForValue.build());
        onChanged();
      } else {
        serversBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RegisteredServer servers = 1;</code>
     */
    public Builder addAllServers(
        java.lang.Iterable<? extends cloud.spawnery.agent.pb.RegisteredServer> values) {
      if (serversBuilder_ == null) {
        ensureServersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, servers_);
        onChanged();
      } else {
        serversBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RegisteredServer servers = 1;</code>
     */
    public Builder clearServers() {
      if (serversBuilder_ == null) {
        servers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        serversBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RegisteredServer servers = 1;</code>
     */
    public Builder removeServers(int index) {
      if (serversBuilder_ == null) {
        ensureServersIsMutable();
        servers_.remove(index);
        onChanged();
      } else {
        serversBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RegisteredServer servers = 1;</code>
     */
    public cloud.spawnery.agent.pb.RegisteredServer.Builder getServersBuilder(
        int index) {
      return internalGetServersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RegisteredServer servers = 1;</code>
     */
    public cloud.spawnery.agent.pb.RegisteredServerOrBuilder getServersOrBuilder(
        int index) {
      if (serversBuilder_ == null) {
        return servers_.get(index);  } else {
        return serversBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RegisteredServer servers = 1;</code>
     */
    public java.util.List<? extends cloud.spawnery.agent.pb.RegisteredServerOrBuilder> 
         getServersOrBuilderList() {
      if (serversBuilder_ != null) {
        return serversBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(servers_);
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RegisteredServer servers = 1;</code>
     */
    public cloud.spawnery.agent.pb.RegisteredServer.Builder addServersBuilder() {
      return internalGetServersFieldBuilder().addBuilder(
          cloud.spawnery.agent.pb.RegisteredServer.getDefaultInstance());
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RegisteredServer servers = 1;</code>
     */
    public cloud.spawnery.agent.pb.RegisteredServer.Builder addServersBuilder(
        int index) {
      return internalGetServersFieldBuilder().addBuilder(
          index, cloud.spawnery.agent.pb.RegisteredServer.getDefaultInstance());
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RegisteredServer servers = 1;</code>
     */
    public java.util.List<cloud.spawnery.agent.pb.RegisteredServer.Builder> 
         getServersBuilderList() {
      return internalGetServersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.spawnery.agent.pb.RegisteredServer, cloud.spawnery.agent.pb.RegisteredServer.Builder, cloud.spawnery.agent.pb.RegisteredServerOrBuilder> 
        internalGetServersFieldBuilder() {
      if (serversBuilder_ == null) {
        serversBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            cloud.spawnery.agent.pb.RegisteredServer, cloud.spawnery.agent.pb.RegisteredServer.Builder, cloud.spawnery.agent.pb.RegisteredServerOrBuilder>(
                servers_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        servers_ = null;
      }
      return serversBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:spawnery.agent.v1alpha1.FullSync)
  }

  // @@protoc_insertion_point(class_scope:spawnery.agent.v1alpha1.FullSync)
  private static final cloud.spawnery.agent.pb.FullSync DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.spawnery.agent.pb.FullSync();
  }

  public static cloud.spawnery.agent.pb.FullSync getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FullSync>
      PARSER = new com.google.protobuf.AbstractParser<FullSync>() {
    @java.lang.Override
    public FullSync parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FullSync> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FullSync> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.spawnery.agent.pb.FullSync getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

