// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

/**
 * <pre>
 * BoostResult is the boost that now exists.
 *
 * It repeats the replica count back rather than assuming the caller's, because
 * the request may have been for zero seconds and this says what the default
 * resolved to.
 * </pre>
 *
 * Protobuf type {@code spawnery.agent.v1alpha1.BoostResult}
 */
@com.google.protobuf.Generated
public final class BoostResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:spawnery.agent.v1alpha1.BoostResult)
    BoostResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "BoostResult");
  }
  // Use BoostResult.newBuilder() to construct.
  private BoostResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BoostResult() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_BoostResult_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_BoostResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_BoostResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.spawnery.agent.pb.BoostResult.class, cloud.spawnery.agent.pb.BoostResult.Builder.class);
  }

  public static final int REPLICAS_FIELD_NUMBER = 1;
  private int replicas_ = 0;
  /**
   * <code>int32 replicas = 1;</code>
   * @return The replicas.
   */
  @java.lang.Override
  public int getReplicas() {
    return replicas_;
  }

  public static final int EXPIRES_AT_UNIX_FIELD_NUMBER = 2;
  private long expiresAtUnix_ = 0L;
  /**
   * <pre>
   * When it stops counting, as seconds since the epoch on the operator's
   * clock. An instant here and a duration on the way in, and the asymmetry is
   * the point: the operator is the side with the authoritative clock, so it
   * states the answer and the agent states the ask.
   * </pre>
   *
   * <code>int64 expires_at_unix = 2;</code>
   * @return The expiresAtUnix.
   */
  @java.lang.Override
  public long getExpiresAtUnix() {
    return expiresAtUnix_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (replicas_ != 0) {
      output.writeInt32(1, replicas_);
    }
    if (expiresAtUnix_ != 0L) {
      output.writeInt64(2, expiresAtUnix_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (replicas_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, replicas_);
    }
    if (expiresAtUnix_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, expiresAtUnix_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.spawnery.agent.pb.BoostResult)) {
      return super.equals(obj);
    }
    cloud.spawnery.agent.pb.BoostResult other = (cloud.spawnery.agent.pb.BoostResult) obj;

    if (getReplicas()
        != other.getReplicas()) return false;
    if (getExpiresAtUnix()
        != other.getExpiresAtUnix()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REPLICAS_FIELD_NUMBER;
    hash = (53 * hash) + getReplicas();
    hash = (37 * hash) + EXPIRES_AT_UNIX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExpiresAtUnix());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.spawnery.agent.pb.BoostResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.BoostResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.BoostResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.BoostResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.BoostResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.BoostResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.BoostResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.BoostResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.spawnery.agent.pb.BoostResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.spawnery.agent.pb.BoostResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.BoostResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.BoostResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.spawnery.agent.pb.BoostResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * BoostResult is the boost that now exists.
   *
   * It repeats the replica count back rather than assuming the caller's, because
   * the request may have been for zero seconds and this says what the default
   * resolved to.
   * </pre>
   *
   * Protobuf type {@code spawnery.agent.v1alpha1.BoostResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:spawnery.agent.v1alpha1.BoostResult)
      cloud.spawnery.agent.pb.BoostResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_BoostResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_BoostResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.spawnery.agent.pb.BoostResult.class, cloud.spawnery.agent.pb.BoostResult.Builder.class);
    }

    // Construct using cloud.spawnery.agent.pb.BoostResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      replicas_ = 0;
      expiresAtUnix_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_BoostResult_descriptor;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.BoostResult getDefaultInstanceForType() {
      return cloud.spawnery.agent.pb.BoostResult.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.BoostResult build() {
      cloud.spawnery.agent.pb.BoostResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.BoostResult buildPartial() {
      cloud.spawnery.agent.pb.BoostResult result = new cloud.spawnery.agent.pb.BoostResult(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(cloud.spawnery.agent.pb.BoostResult result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.replicas_ = replicas_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.expiresAtUnix_ = expiresAtUnix_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.spawnery.agent.pb.BoostResult) {
        return mergeFrom((cloud.spawnery.agent.pb.BoostResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.spawnery.agent.pb.BoostResult other) {
      if (other == cloud.spawnery.agent.pb.BoostResult.getDefaultInstance()) return this;
      if (other.getReplicas() != 0) {
        setReplicas(other.getReplicas());
      }
      if (other.getExpiresAtUnix() != 0L) {
        setExpiresAtUnix(other.getExpiresAtUnix());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              replicas_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              expiresAtUnix_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int replicas_ ;
    /**
     * <code>int32 replicas = 1;</code>
     * @return The replicas.
     */
    @java.lang.Override
    public int getReplicas() {
      return replicas_;
    }
    /**
     * <code>int32 replicas = 1;</code>
     * @param value The replicas to set.
     * @return This builder for chaining.
     */
    public Builder setReplicas(int value) {

      replicas_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 replicas = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReplicas() {
      bitField0_ = (bitField0_ & ~0x00000001);
      replicas_ = 0;
      onChanged();
      return this;
    }

    private long expiresAtUnix_ ;
    /**
     * <pre>
     * When it stops counting, as seconds since the epoch on the operator's
     * clock. An instant here and a duration on the way in, and the asymmetry is
     * the point: the operator is the side with the authoritative clock, so it
     * states the answer and the agent states the ask.
     * </pre>
     *
     * <code>int64 expires_at_unix = 2;</code>
     * @return The expiresAtUnix.
     */
    @java.lang.Override
    public long getExpiresAtUnix() {
      return expiresAtUnix_;
    }
    /**
     * <pre>
     * When it stops counting, as seconds since the epoch on the operator's
     * clock. An instant here and a duration on the way in, and the asymmetry is
     * the point: the operator is the side with the authoritative clock, so it
     * states the answer and the agent states the ask.
     * </pre>
     *
     * <code>int64 expires_at_unix = 2;</code>
     * @param value The expiresAtUnix to set.
     * @return This builder for chaining.
     */
    public Builder setExpiresAtUnix(long value) {

      expiresAtUnix_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When it stops counting, as seconds since the epoch on the operator's
     * clock. An instant here and a duration on the way in, and the asymmetry is
     * the point: the operator is the side with the authoritative clock, so it
     * states the answer and the agent states the ask.
     * </pre>
     *
     * <code>int64 expires_at_unix = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearExpiresAtUnix() {
      bitField0_ = (bitField0_ & ~0x00000002);
      expiresAtUnix_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:spawnery.agent.v1alpha1.BoostResult)
  }

  // @@protoc_insertion_point(class_scope:spawnery.agent.v1alpha1.BoostResult)
  private static final cloud.spawnery.agent.pb.BoostResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.spawnery.agent.pb.BoostResult();
  }

  public static cloud.spawnery.agent.pb.BoostResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BoostResult>
      PARSER = new com.google.protobuf.AbstractParser<BoostResult>() {
    @java.lang.Override
    public BoostResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BoostResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BoostResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.spawnery.agent.pb.BoostResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

