// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface ConnectResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.ConnectResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool ordered = 1;</code>
   * @return The ordered.
   */
  boolean getOrdered();

  /**
   * <code>bool already_there = 2;</code>
   * @return The alreadyThere.
   */
  boolean getAlreadyThere();

  /**
   * <pre>
   * The server the move was aimed at, or the player's current one when
   * already_there is set.
   * </pre>
   *
   * <code>string target = 3;</code>
   * @return The target.
   */
  java.lang.String getTarget();
  /**
   * <pre>
   * The server the move was aimed at, or the player's current one when
   * already_there is set.
   * </pre>
   *
   * <code>string target = 3;</code>
   * @return The bytes for target.
   */
  com.google.protobuf.ByteString
      getTargetBytes();
}
