// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface ConnectRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.ConnectRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string player_uuid = 1;</code>
   * @return The playerUuid.
   */
  java.lang.String getPlayerUuid();
  /**
   * <code>string player_uuid = 1;</code>
   * @return The bytes for playerUuid.
   */
  com.google.protobuf.ByteString
      getPlayerUuidBytes();

  /**
   * <code>string server = 2;</code>
   * @return Whether the server field is set.
   */
  boolean hasServer();
  /**
   * <code>string server = 2;</code>
   * @return The server.
   */
  java.lang.String getServer();
  /**
   * <code>string server = 2;</code>
   * @return The bytes for server.
   */
  com.google.protobuf.ByteString
      getServerBytes();

  /**
   * <code>string group = 3;</code>
   * @return Whether the group field is set.
   */
  boolean hasGroup();
  /**
   * <code>string group = 3;</code>
   * @return The group.
   */
  java.lang.String getGroup();
  /**
   * <code>string group = 3;</code>
   * @return The bytes for group.
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  cloud.spawnery.agent.pb.ConnectRequest.TargetCase getTargetCase();
}
