// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface GroupStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.GroupState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.spawnery.agent.v1alpha1.GroupState.Kind kind = 2;</code>
   * @return The enum numeric value on the wire for kind.
   */
  int getKindValue();
  /**
   * <code>.spawnery.agent.v1alpha1.GroupState.Kind kind = 2;</code>
   * @return The kind.
   */
  cloud.spawnery.agent.pb.GroupState.Kind getKind();

  /**
   * <code>int32 replicas = 3;</code>
   * @return The replicas.
   */
  int getReplicas();

  /**
   * <code>int32 ready_replicas = 4;</code>
   * @return The readyReplicas.
   */
  int getReadyReplicas();

  /**
   * <code>int32 online_players = 5;</code>
   * @return The onlinePlayers.
   */
  int getOnlinePlayers();

  /**
   * <pre>
   * The operator's own figure, which counts only ready servers of the group's
   * current spec. Not a sum an agent could compute from the servers below, and
   * the two can disagree while a rolling update is in flight.
   * </pre>
   *
   * <code>int32 free_slots = 6;</code>
   * @return The freeSlots.
   */
  int getFreeSlots();
}
