// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface GroupStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.GroupState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.spawnery.agent.v1alpha1.GroupState.Kind kind = 2;</code>
   * @return The enum numeric value on the wire for kind.
   */
  int getKindValue();
  /**
   * <code>.spawnery.agent.v1alpha1.GroupState.Kind kind = 2;</code>
   * @return The kind.
   */
  cloud.spawnery.agent.pb.GroupState.Kind getKind();

  /**
   * <code>int32 replicas = 3;</code>
   * @return The replicas.
   */
  int getReplicas();

  /**
   * <code>int32 ready_replicas = 4;</code>
   * @return The readyReplicas.
   */
  int getReadyReplicas();

  /**
   * <code>int32 online_players = 5;</code>
   * @return The onlinePlayers.
   */
  int getOnlinePlayers();

  /**
   * <pre>
   * The operator's own figure, which counts only ready servers of the group's
   * current spec. Not a sum an agent could compute from the servers below, and
   * the two can disagree while a rolling update is in flight.
   * </pre>
   *
   * <code>int32 free_slots = 6;</code>
   * @return The freeSlots.
   */
  int getFreeSlots();

  /**
   * <pre>
   * The group's spec.attributes: what a person wrote about the group, as
   * opposed to ServerState.attributes, which a server announces.
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 7;</code>
   */
  int getAttributesCount();
  /**
   * <pre>
   * The group's spec.attributes: what a person wrote about the group, as
   * opposed to ServerState.attributes, which a server announces.
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 7;</code>
   */
  boolean containsAttributes(
      java.lang.String key);
  /**
   * Use {@link #getAttributesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getAttributes();
  /**
   * <pre>
   * The group's spec.attributes: what a person wrote about the group, as
   * opposed to ServerState.attributes, which a server announces.
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 7;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getAttributesMap();
  /**
   * <pre>
   * The group's spec.attributes: what a person wrote about the group, as
   * opposed to ServerState.attributes, which a server announces.
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 7;</code>
   */
  /* nullable */
java.lang.String getAttributesOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * The group's spec.attributes: what a person wrote about the group, as
   * opposed to ServerState.attributes, which a server announces.
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 7;</code>
   */
  java.lang.String getAttributesOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * The group's spec.displayName. Empty when unset; the agent then shows the
   * group's name.
   * </pre>
   *
   * <code>string display_name = 8;</code>
   * @return The displayName.
   */
  java.lang.String getDisplayName();
  /**
   * <pre>
   * The group's spec.displayName. Empty when unset; the agent then shows the
   * group's name.
   * </pre>
   *
   * <code>string display_name = 8;</code>
   * @return The bytes for displayName.
   */
  com.google.protobuf.ByteString
      getDisplayNameBytes();

  /**
   * <pre>
   * The group's spec.playableSlots, 0 if unset.
   * </pre>
   *
   * <code>int32 playable_slots = 9;</code>
   * @return The playableSlots.
   */
  int getPlayableSlots();

  /**
   * <pre>
   * spec.enforcePlayableSlots.
   * </pre>
   *
   * <code>bool enforce_playable_slots = 10;</code>
   * @return The enforcePlayableSlots.
   */
  boolean getEnforcePlayableSlots();

  /**
   * <pre>
   * The permission that decides who may join this group's servers, already
   * resolved from spec.joinPermission. Empty means the group has no rule.
   * </pre>
   *
   * <code>string join_permission = 11;</code>
   * @return The joinPermission.
   */
  java.lang.String getJoinPermission();
  /**
   * <pre>
   * The permission that decides who may join this group's servers, already
   * resolved from spec.joinPermission. Empty means the group has no rule.
   * </pre>
   *
   * <code>string join_permission = 11;</code>
   * @return The bytes for joinPermission.
   */
  com.google.protobuf.ByteString
      getJoinPermissionBytes();

  /**
   * <pre>
   * spec.joinPermission.mode is DenyOnly: only an explicit false refuses.
   * </pre>
   *
   * <code>bool join_permission_deny_only = 12;</code>
   * @return The joinPermissionDenyOnly.
   */
  boolean getJoinPermissionDenyOnly();

  /**
   * <pre>
   * An Exact ScaleBoost holds the group at pinned_replicas servers, which can
   * be 0. Without a pin both fields below are zero and mean nothing.
   * </pre>
   *
   * <code>bool pinned = 13;</code>
   * @return The pinned.
   */
  boolean getPinned();

  /**
   * <code>int32 pinned_replicas = 14;</code>
   * @return The pinnedReplicas.
   */
  int getPinnedReplicas();

  /**
   * <pre>
   * When the pin ends, on the operator's clock; 0 for a pin without an end.
   * </pre>
   *
   * <code>int64 pinned_until_unix = 15;</code>
   * @return The pinnedUntilUnix.
   */
  long getPinnedUntilUnix();
}
