// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface HelloOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.Hello)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string version = 1;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 1;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <pre>
   * ready is meaningful for server agents only. Readiness is a state, not an
   * event, so it is repeated on every connect.
   * </pre>
   *
   * <code>bool ready = 2;</code>
   * @return The ready.
   */
  boolean getReady();
}
