// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

/**
 * <pre>
 * ListRestorePointsResult: the current generation first, then the older
 * ones, newest first.
 * </pre>
 *
 * Protobuf type {@code spawnery.agent.v1alpha1.ListRestorePointsResult}
 */
@com.google.protobuf.Generated
public final class ListRestorePointsResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:spawnery.agent.v1alpha1.ListRestorePointsResult)
    ListRestorePointsResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "ListRestorePointsResult");
  }
  // Use ListRestorePointsResult.newBuilder() to construct.
  private ListRestorePointsResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListRestorePointsResult() {
    points_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_ListRestorePointsResult_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_ListRestorePointsResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_ListRestorePointsResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.spawnery.agent.pb.ListRestorePointsResult.class, cloud.spawnery.agent.pb.ListRestorePointsResult.Builder.class);
  }

  public static final int POINTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<cloud.spawnery.agent.pb.RestorePoint> points_;
  /**
   * <code>repeated .spawnery.agent.v1alpha1.RestorePoint points = 1;</code>
   */
  @java.lang.Override
  public java.util.List<cloud.spawnery.agent.pb.RestorePoint> getPointsList() {
    return points_;
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.RestorePoint points = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends cloud.spawnery.agent.pb.RestorePointOrBuilder> 
      getPointsOrBuilderList() {
    return points_;
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.RestorePoint points = 1;</code>
   */
  @java.lang.Override
  public int getPointsCount() {
    return points_.size();
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.RestorePoint points = 1;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.RestorePoint getPoints(int index) {
    return points_.get(index);
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.RestorePoint points = 1;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.RestorePointOrBuilder getPointsOrBuilder(
      int index) {
    return points_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < points_.size(); i++) {
      output.writeMessage(1, points_.get(i));
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;

        {
          final int count = points_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(points_.get(i));
          }
          size += 1 * count;
        }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.spawnery.agent.pb.ListRestorePointsResult)) {
      return super.equals(obj);
    }
    cloud.spawnery.agent.pb.ListRestorePointsResult other = (cloud.spawnery.agent.pb.ListRestorePointsResult) obj;

    if (!getPointsList()
        .equals(other.getPointsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPointsCount() > 0) {
      hash = (37 * hash) + POINTS_FIELD_NUMBER;
      hash = (53 * hash) + getPointsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.spawnery.agent.pb.ListRestorePointsResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.ListRestorePointsResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.ListRestorePointsResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.ListRestorePointsResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.ListRestorePointsResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.ListRestorePointsResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.ListRestorePointsResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.ListRestorePointsResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.spawnery.agent.pb.ListRestorePointsResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.spawnery.agent.pb.ListRestorePointsResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.ListRestorePointsResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.ListRestorePointsResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.spawnery.agent.pb.ListRestorePointsResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ListRestorePointsResult: the current generation first, then the older
   * ones, newest first.
   * </pre>
   *
   * Protobuf type {@code spawnery.agent.v1alpha1.ListRestorePointsResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:spawnery.agent.v1alpha1.ListRestorePointsResult)
      cloud.spawnery.agent.pb.ListRestorePointsResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_ListRestorePointsResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_ListRestorePointsResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.spawnery.agent.pb.ListRestorePointsResult.class, cloud.spawnery.agent.pb.ListRestorePointsResult.Builder.class);
    }

    // Construct using cloud.spawnery.agent.pb.ListRestorePointsResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (pointsBuilder_ == null) {
        points_ = java.util.Collections.emptyList();
      } else {
        points_ = null;
        pointsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_ListRestorePointsResult_descriptor;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.ListRestorePointsResult getDefaultInstanceForType() {
      return cloud.spawnery.agent.pb.ListRestorePointsResult.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.ListRestorePointsResult build() {
      cloud.spawnery.agent.pb.ListRestorePointsResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.ListRestorePointsResult buildPartial() {
      cloud.spawnery.agent.pb.ListRestorePointsResult result = new cloud.spawnery.agent.pb.ListRestorePointsResult(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(cloud.spawnery.agent.pb.ListRestorePointsResult result) {
      if (pointsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          points_ = java.util.Collections.unmodifiableList(points_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.points_ = points_;
      } else {
        result.points_ = pointsBuilder_.build();
      }
    }

    private void buildPartial0(cloud.spawnery.agent.pb.ListRestorePointsResult result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.spawnery.agent.pb.ListRestorePointsResult) {
        return mergeFrom((cloud.spawnery.agent.pb.ListRestorePointsResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.spawnery.agent.pb.ListRestorePointsResult other) {
      if (other == cloud.spawnery.agent.pb.ListRestorePointsResult.getDefaultInstance()) return this;
      if (pointsBuilder_ == null) {
        if (!other.points_.isEmpty()) {
          if (points_.isEmpty()) {
            points_ = other.points_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePointsIsMutable();
            points_.addAll(other.points_);
          }
          onChanged();
        }
      } else {
        if (!other.points_.isEmpty()) {
          if (pointsBuilder_.isEmpty()) {
            pointsBuilder_.dispose();
            pointsBuilder_ = null;
            points_ = other.points_;
            bitField0_ = (bitField0_ & ~0x00000001);
            pointsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetPointsFieldBuilder() : null;
          } else {
            pointsBuilder_.addAllMessages(other.points_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              cloud.spawnery.agent.pb.RestorePoint m =
                  input.readMessage(
                      cloud.spawnery.agent.pb.RestorePoint.parser(),
                      extensionRegistry);
              if (pointsBuilder_ == null) {
                ensurePointsIsMutable();
                points_.add(m);
              } else {
                pointsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<cloud.spawnery.agent.pb.RestorePoint> points_ =
      java.util.Collections.emptyList();
    private void ensurePointsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        points_ = new java.util.ArrayList<cloud.spawnery.agent.pb.RestorePoint>(points_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.spawnery.agent.pb.RestorePoint, cloud.spawnery.agent.pb.RestorePoint.Builder, cloud.spawnery.agent.pb.RestorePointOrBuilder> pointsBuilder_;

    /**
     * <code>repeated .spawnery.agent.v1alpha1.RestorePoint points = 1;</code>
     */
    public java.util.List<cloud.spawnery.agent.pb.RestorePoint> getPointsList() {
      if (pointsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(points_);
      } else {
        return pointsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RestorePoint points = 1;</code>
     */
    public int getPointsCount() {
      if (pointsBuilder_ == null) {
        return points_.size();
      } else {
        return pointsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RestorePoint points = 1;</code>
     */
    public cloud.spawnery.agent.pb.RestorePoint getPoints(int index) {
      if (pointsBuilder_ == null) {
        return points_.get(index);
      } else {
        return pointsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RestorePoint points = 1;</code>
     */
    public Builder setPoints(
        int index, cloud.spawnery.agent.pb.RestorePoint value) {
      if (pointsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePointsIsMutable();
        points_.set(index, value);
        onChanged();
      } else {
        pointsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RestorePoint points = 1;</code>
     */
    public Builder setPoints(
        int index, cloud.spawnery.agent.pb.RestorePoint.Builder builderForValue) {
      if (pointsBuilder_ == null) {
        ensurePointsIsMutable();
        points_.set(index, builderForValue.build());
        onChanged();
      } else {
        pointsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RestorePoint points = 1;</code>
     */
    public Builder addPoints(cloud.spawnery.agent.pb.RestorePoint value) {
      if (pointsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePointsIsMutable();
        points_.add(value);
        onChanged();
      } else {
        pointsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RestorePoint points = 1;</code>
     */
    public Builder addPoints(
        int index, cloud.spawnery.agent.pb.RestorePoint value) {
      if (pointsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePointsIsMutable();
        points_.add(index, value);
        onChanged();
      } else {
        pointsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RestorePoint points = 1;</code>
     */
    public Builder addPoints(
        cloud.spawnery.agent.pb.RestorePoint.Builder builderForValue) {
      if (pointsBuilder_ == null) {
        ensurePointsIsMutable();
        points_.add(builderForValue.build());
        onChanged();
      } else {
        pointsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RestorePoint points = 1;</code>
     */
    public Builder addPoints(
        int index, cloud.spawnery.agent.pb.RestorePoint.Builder builderForValue) {
      if (pointsBuilder_ == null) {
        ensurePointsIsMutable();
        points_.add(index, builderForValue.build());
        onChanged();
      } else {
        pointsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RestorePoint points = 1;</code>
     */
    public Builder addAllPoints(
        java.lang.Iterable<? extends cloud.spawnery.agent.pb.RestorePoint> values) {
      if (pointsBuilder_ == null) {
        ensurePointsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, points_);
        onChanged();
      } else {
        pointsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RestorePoint points = 1;</code>
     */
    public Builder clearPoints() {
      if (pointsBuilder_ == null) {
        points_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        pointsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RestorePoint points = 1;</code>
     */
    public Builder removePoints(int index) {
      if (pointsBuilder_ == null) {
        ensurePointsIsMutable();
        points_.remove(index);
        onChanged();
      } else {
        pointsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RestorePoint points = 1;</code>
     */
    public cloud.spawnery.agent.pb.RestorePoint.Builder getPointsBuilder(
        int index) {
      return internalGetPointsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RestorePoint points = 1;</code>
     */
    public cloud.spawnery.agent.pb.RestorePointOrBuilder getPointsOrBuilder(
        int index) {
      if (pointsBuilder_ == null) {
        return points_.get(index);  } else {
        return pointsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RestorePoint points = 1;</code>
     */
    public java.util.List<? extends cloud.spawnery.agent.pb.RestorePointOrBuilder> 
         getPointsOrBuilderList() {
      if (pointsBuilder_ != null) {
        return pointsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(points_);
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RestorePoint points = 1;</code>
     */
    public cloud.spawnery.agent.pb.RestorePoint.Builder addPointsBuilder() {
      return internalGetPointsFieldBuilder().addBuilder(
          cloud.spawnery.agent.pb.RestorePoint.getDefaultInstance());
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RestorePoint points = 1;</code>
     */
    public cloud.spawnery.agent.pb.RestorePoint.Builder addPointsBuilder(
        int index) {
      return internalGetPointsFieldBuilder().addBuilder(
          index, cloud.spawnery.agent.pb.RestorePoint.getDefaultInstance());
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RestorePoint points = 1;</code>
     */
    public java.util.List<cloud.spawnery.agent.pb.RestorePoint.Builder> 
         getPointsBuilderList() {
      return internalGetPointsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.spawnery.agent.pb.RestorePoint, cloud.spawnery.agent.pb.RestorePoint.Builder, cloud.spawnery.agent.pb.RestorePointOrBuilder> 
        internalGetPointsFieldBuilder() {
      if (pointsBuilder_ == null) {
        pointsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            cloud.spawnery.agent.pb.RestorePoint, cloud.spawnery.agent.pb.RestorePoint.Builder, cloud.spawnery.agent.pb.RestorePointOrBuilder>(
                points_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        points_ = null;
      }
      return pointsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:spawnery.agent.v1alpha1.ListRestorePointsResult)
  }

  // @@protoc_insertion_point(class_scope:spawnery.agent.v1alpha1.ListRestorePointsResult)
  private static final cloud.spawnery.agent.pb.ListRestorePointsResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.spawnery.agent.pb.ListRestorePointsResult();
  }

  public static cloud.spawnery.agent.pb.ListRestorePointsResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListRestorePointsResult>
      PARSER = new com.google.protobuf.AbstractParser<ListRestorePointsResult>() {
    @java.lang.Override
    public ListRestorePointsResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListRestorePointsResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListRestorePointsResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.spawnery.agent.pb.ListRestorePointsResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

