// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

/**
 * <pre>
 * NetworkState is the whole picture of one namespace, as the operator sees it.
 *
 * The mirror the plugin API reads from. It goes to both agent kinds, in the
 * same shape, because the API's whole premise is that a plugin author moving
 * between a backend and a proxy does not have to think differently -- and two
 * shapes here would make that a lie one layer down.
 *
 * A state and not a diff. Every message carries the whole picture, so a
 * reconnect needs no catch-up and a dropped one costs a resync interval of
 * freshness. That is the same rule FullSync follows, for the same reason.
 *
 * The phase is a string rather than an enum, and deliberately: the operator's
 * phase vocabulary lives in internal/phase and gains values, and an agent that
 * is older than a value must read it as "something I do not know" rather than
 * fail to parse the message it arrived in. The plugin API's own
 * ServerPhase.fromWire is the other half of that decision.
 * </pre>
 *
 * Protobuf type {@code spawnery.agent.v1alpha1.NetworkState}
 */
@com.google.protobuf.Generated
public final class NetworkState extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:spawnery.agent.v1alpha1.NetworkState)
    NetworkStateOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "NetworkState");
  }
  // Use NetworkState.newBuilder() to construct.
  private NetworkState(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private NetworkState() {
    groups_ = java.util.Collections.emptyList();
    servers_ = java.util.Collections.emptyList();
    players_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_NetworkState_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_NetworkState_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_NetworkState_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.spawnery.agent.pb.NetworkState.class, cloud.spawnery.agent.pb.NetworkState.Builder.class);
  }

  public static final int GROUPS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<cloud.spawnery.agent.pb.GroupState> groups_;
  /**
   * <code>repeated .spawnery.agent.v1alpha1.GroupState groups = 1;</code>
   */
  @java.lang.Override
  public java.util.List<cloud.spawnery.agent.pb.GroupState> getGroupsList() {
    return groups_;
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.GroupState groups = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends cloud.spawnery.agent.pb.GroupStateOrBuilder> 
      getGroupsOrBuilderList() {
    return groups_;
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.GroupState groups = 1;</code>
   */
  @java.lang.Override
  public int getGroupsCount() {
    return groups_.size();
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.GroupState groups = 1;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.GroupState getGroups(int index) {
    return groups_.get(index);
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.GroupState groups = 1;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.GroupStateOrBuilder getGroupsOrBuilder(
      int index) {
    return groups_.get(index);
  }

  public static final int SERVERS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<cloud.spawnery.agent.pb.ServerState> servers_;
  /**
   * <code>repeated .spawnery.agent.v1alpha1.ServerState servers = 2;</code>
   */
  @java.lang.Override
  public java.util.List<cloud.spawnery.agent.pb.ServerState> getServersList() {
    return servers_;
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.ServerState servers = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends cloud.spawnery.agent.pb.ServerStateOrBuilder> 
      getServersOrBuilderList() {
    return servers_;
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.ServerState servers = 2;</code>
   */
  @java.lang.Override
  public int getServersCount() {
    return servers_.size();
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.ServerState servers = 2;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.ServerState getServers(int index) {
    return servers_.get(index);
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.ServerState servers = 2;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.ServerStateOrBuilder getServersOrBuilder(
      int index) {
    return servers_.get(index);
  }

  public static final int PLAYERS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<cloud.spawnery.agent.pb.RosterEntry> players_;
  /**
   * <pre>
   * Every player on this network, aggregated across the proxies. Empty when
   * no proxy has reported recently -- which is a real state and not an error,
   * and is why the API documents an empty list as ordinary.
   * </pre>
   *
   * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 3;</code>
   */
  @java.lang.Override
  public java.util.List<cloud.spawnery.agent.pb.RosterEntry> getPlayersList() {
    return players_;
  }
  /**
   * <pre>
   * Every player on this network, aggregated across the proxies. Empty when
   * no proxy has reported recently -- which is a real state and not an error,
   * and is why the API documents an empty list as ordinary.
   * </pre>
   *
   * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends cloud.spawnery.agent.pb.RosterEntryOrBuilder> 
      getPlayersOrBuilderList() {
    return players_;
  }
  /**
   * <pre>
   * Every player on this network, aggregated across the proxies. Empty when
   * no proxy has reported recently -- which is a real state and not an error,
   * and is why the API documents an empty list as ordinary.
   * </pre>
   *
   * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 3;</code>
   */
  @java.lang.Override
  public int getPlayersCount() {
    return players_.size();
  }
  /**
   * <pre>
   * Every player on this network, aggregated across the proxies. Empty when
   * no proxy has reported recently -- which is a real state and not an error,
   * and is why the API documents an empty list as ordinary.
   * </pre>
   *
   * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 3;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.RosterEntry getPlayers(int index) {
    return players_.get(index);
  }
  /**
   * <pre>
   * Every player on this network, aggregated across the proxies. Empty when
   * no proxy has reported recently -- which is a real state and not an error,
   * and is why the API documents an empty list as ordinary.
   * </pre>
   *
   * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 3;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.RosterEntryOrBuilder getPlayersOrBuilder(
      int index) {
    return players_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < groups_.size(); i++) {
      output.writeMessage(1, groups_.get(i));
    }
    for (int i = 0; i < servers_.size(); i++) {
      output.writeMessage(2, servers_.get(i));
    }
    for (int i = 0; i < players_.size(); i++) {
      output.writeMessage(3, players_.get(i));
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;

        {
          final int count = groups_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(groups_.get(i));
          }
          size += 1 * count;
        }

        {
          final int count = servers_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(servers_.get(i));
          }
          size += 1 * count;
        }

        {
          final int count = players_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(players_.get(i));
          }
          size += 1 * count;
        }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.spawnery.agent.pb.NetworkState)) {
      return super.equals(obj);
    }
    cloud.spawnery.agent.pb.NetworkState other = (cloud.spawnery.agent.pb.NetworkState) obj;

    if (!getGroupsList()
        .equals(other.getGroupsList())) return false;
    if (!getServersList()
        .equals(other.getServersList())) return false;
    if (!getPlayersList()
        .equals(other.getPlayersList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getGroupsCount() > 0) {
      hash = (37 * hash) + GROUPS_FIELD_NUMBER;
      hash = (53 * hash) + getGroupsList().hashCode();
    }
    if (getServersCount() > 0) {
      hash = (37 * hash) + SERVERS_FIELD_NUMBER;
      hash = (53 * hash) + getServersList().hashCode();
    }
    if (getPlayersCount() > 0) {
      hash = (37 * hash) + PLAYERS_FIELD_NUMBER;
      hash = (53 * hash) + getPlayersList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.spawnery.agent.pb.NetworkState parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.NetworkState parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.NetworkState parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.NetworkState parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.NetworkState parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.NetworkState parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.NetworkState parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.NetworkState parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.spawnery.agent.pb.NetworkState parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.spawnery.agent.pb.NetworkState parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.NetworkState parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.NetworkState parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.spawnery.agent.pb.NetworkState prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * NetworkState is the whole picture of one namespace, as the operator sees it.
   *
   * The mirror the plugin API reads from. It goes to both agent kinds, in the
   * same shape, because the API's whole premise is that a plugin author moving
   * between a backend and a proxy does not have to think differently -- and two
   * shapes here would make that a lie one layer down.
   *
   * A state and not a diff. Every message carries the whole picture, so a
   * reconnect needs no catch-up and a dropped one costs a resync interval of
   * freshness. That is the same rule FullSync follows, for the same reason.
   *
   * The phase is a string rather than an enum, and deliberately: the operator's
   * phase vocabulary lives in internal/phase and gains values, and an agent that
   * is older than a value must read it as "something I do not know" rather than
   * fail to parse the message it arrived in. The plugin API's own
   * ServerPhase.fromWire is the other half of that decision.
   * </pre>
   *
   * Protobuf type {@code spawnery.agent.v1alpha1.NetworkState}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:spawnery.agent.v1alpha1.NetworkState)
      cloud.spawnery.agent.pb.NetworkStateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_NetworkState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_NetworkState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.spawnery.agent.pb.NetworkState.class, cloud.spawnery.agent.pb.NetworkState.Builder.class);
    }

    // Construct using cloud.spawnery.agent.pb.NetworkState.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (groupsBuilder_ == null) {
        groups_ = java.util.Collections.emptyList();
      } else {
        groups_ = null;
        groupsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (serversBuilder_ == null) {
        servers_ = java.util.Collections.emptyList();
      } else {
        servers_ = null;
        serversBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (playersBuilder_ == null) {
        players_ = java.util.Collections.emptyList();
      } else {
        players_ = null;
        playersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_NetworkState_descriptor;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.NetworkState getDefaultInstanceForType() {
      return cloud.spawnery.agent.pb.NetworkState.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.NetworkState build() {
      cloud.spawnery.agent.pb.NetworkState result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.NetworkState buildPartial() {
      cloud.spawnery.agent.pb.NetworkState result = new cloud.spawnery.agent.pb.NetworkState(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(cloud.spawnery.agent.pb.NetworkState result) {
      if (groupsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          groups_ = java.util.Collections.unmodifiableList(groups_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.groups_ = groups_;
      } else {
        result.groups_ = groupsBuilder_.build();
      }
      if (serversBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          servers_ = java.util.Collections.unmodifiableList(servers_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.servers_ = servers_;
      } else {
        result.servers_ = serversBuilder_.build();
      }
      if (playersBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          players_ = java.util.Collections.unmodifiableList(players_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.players_ = players_;
      } else {
        result.players_ = playersBuilder_.build();
      }
    }

    private void buildPartial0(cloud.spawnery.agent.pb.NetworkState result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.spawnery.agent.pb.NetworkState) {
        return mergeFrom((cloud.spawnery.agent.pb.NetworkState)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.spawnery.agent.pb.NetworkState other) {
      if (other == cloud.spawnery.agent.pb.NetworkState.getDefaultInstance()) return this;
      if (groupsBuilder_ == null) {
        if (!other.groups_.isEmpty()) {
          if (groups_.isEmpty()) {
            groups_ = other.groups_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureGroupsIsMutable();
            groups_.addAll(other.groups_);
          }
          onChanged();
        }
      } else {
        if (!other.groups_.isEmpty()) {
          if (groupsBuilder_.isEmpty()) {
            groupsBuilder_.dispose();
            groupsBuilder_ = null;
            groups_ = other.groups_;
            bitField0_ = (bitField0_ & ~0x00000001);
            groupsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetGroupsFieldBuilder() : null;
          } else {
            groupsBuilder_.addAllMessages(other.groups_);
          }
        }
      }
      if (serversBuilder_ == null) {
        if (!other.servers_.isEmpty()) {
          if (servers_.isEmpty()) {
            servers_ = other.servers_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureServersIsMutable();
            servers_.addAll(other.servers_);
          }
          onChanged();
        }
      } else {
        if (!other.servers_.isEmpty()) {
          if (serversBuilder_.isEmpty()) {
            serversBuilder_.dispose();
            serversBuilder_ = null;
            servers_ = other.servers_;
            bitField0_ = (bitField0_ & ~0x00000002);
            serversBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetServersFieldBuilder() : null;
          } else {
            serversBuilder_.addAllMessages(other.servers_);
          }
        }
      }
      if (playersBuilder_ == null) {
        if (!other.players_.isEmpty()) {
          if (players_.isEmpty()) {
            players_ = other.players_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePlayersIsMutable();
            players_.addAll(other.players_);
          }
          onChanged();
        }
      } else {
        if (!other.players_.isEmpty()) {
          if (playersBuilder_.isEmpty()) {
            playersBuilder_.dispose();
            playersBuilder_ = null;
            players_ = other.players_;
            bitField0_ = (bitField0_ & ~0x00000004);
            playersBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetPlayersFieldBuilder() : null;
          } else {
            playersBuilder_.addAllMessages(other.players_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              cloud.spawnery.agent.pb.GroupState m =
                  input.readMessage(
                      cloud.spawnery.agent.pb.GroupState.parser(),
                      extensionRegistry);
              if (groupsBuilder_ == null) {
                ensureGroupsIsMutable();
                groups_.add(m);
              } else {
                groupsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              cloud.spawnery.agent.pb.ServerState m =
                  input.readMessage(
                      cloud.spawnery.agent.pb.ServerState.parser(),
                      extensionRegistry);
              if (serversBuilder_ == null) {
                ensureServersIsMutable();
                servers_.add(m);
              } else {
                serversBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              cloud.spawnery.agent.pb.RosterEntry m =
                  input.readMessage(
                      cloud.spawnery.agent.pb.RosterEntry.parser(),
                      extensionRegistry);
              if (playersBuilder_ == null) {
                ensurePlayersIsMutable();
                players_.add(m);
              } else {
                playersBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<cloud.spawnery.agent.pb.GroupState> groups_ =
      java.util.Collections.emptyList();
    private void ensureGroupsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        groups_ = new java.util.ArrayList<cloud.spawnery.agent.pb.GroupState>(groups_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.spawnery.agent.pb.GroupState, cloud.spawnery.agent.pb.GroupState.Builder, cloud.spawnery.agent.pb.GroupStateOrBuilder> groupsBuilder_;

    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupState groups = 1;</code>
     */
    public java.util.List<cloud.spawnery.agent.pb.GroupState> getGroupsList() {
      if (groupsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(groups_);
      } else {
        return groupsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupState groups = 1;</code>
     */
    public int getGroupsCount() {
      if (groupsBuilder_ == null) {
        return groups_.size();
      } else {
        return groupsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupState groups = 1;</code>
     */
    public cloud.spawnery.agent.pb.GroupState getGroups(int index) {
      if (groupsBuilder_ == null) {
        return groups_.get(index);
      } else {
        return groupsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupState groups = 1;</code>
     */
    public Builder setGroups(
        int index, cloud.spawnery.agent.pb.GroupState value) {
      if (groupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupsIsMutable();
        groups_.set(index, value);
        onChanged();
      } else {
        groupsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupState groups = 1;</code>
     */
    public Builder setGroups(
        int index, cloud.spawnery.agent.pb.GroupState.Builder builderForValue) {
      if (groupsBuilder_ == null) {
        ensureGroupsIsMutable();
        groups_.set(index, builderForValue.build());
        onChanged();
      } else {
        groupsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupState groups = 1;</code>
     */
    public Builder addGroups(cloud.spawnery.agent.pb.GroupState value) {
      if (groupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupsIsMutable();
        groups_.add(value);
        onChanged();
      } else {
        groupsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupState groups = 1;</code>
     */
    public Builder addGroups(
        int index, cloud.spawnery.agent.pb.GroupState value) {
      if (groupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupsIsMutable();
        groups_.add(index, value);
        onChanged();
      } else {
        groupsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupState groups = 1;</code>
     */
    public Builder addGroups(
        cloud.spawnery.agent.pb.GroupState.Builder builderForValue) {
      if (groupsBuilder_ == null) {
        ensureGroupsIsMutable();
        groups_.add(builderForValue.build());
        onChanged();
      } else {
        groupsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupState groups = 1;</code>
     */
    public Builder addGroups(
        int index, cloud.spawnery.agent.pb.GroupState.Builder builderForValue) {
      if (groupsBuilder_ == null) {
        ensureGroupsIsMutable();
        groups_.add(index, builderForValue.build());
        onChanged();
      } else {
        groupsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupState groups = 1;</code>
     */
    public Builder addAllGroups(
        java.lang.Iterable<? extends cloud.spawnery.agent.pb.GroupState> values) {
      if (groupsBuilder_ == null) {
        ensureGroupsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, groups_);
        onChanged();
      } else {
        groupsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupState groups = 1;</code>
     */
    public Builder clearGroups() {
      if (groupsBuilder_ == null) {
        groups_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        groupsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupState groups = 1;</code>
     */
    public Builder removeGroups(int index) {
      if (groupsBuilder_ == null) {
        ensureGroupsIsMutable();
        groups_.remove(index);
        onChanged();
      } else {
        groupsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupState groups = 1;</code>
     */
    public cloud.spawnery.agent.pb.GroupState.Builder getGroupsBuilder(
        int index) {
      return internalGetGroupsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupState groups = 1;</code>
     */
    public cloud.spawnery.agent.pb.GroupStateOrBuilder getGroupsOrBuilder(
        int index) {
      if (groupsBuilder_ == null) {
        return groups_.get(index);  } else {
        return groupsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupState groups = 1;</code>
     */
    public java.util.List<? extends cloud.spawnery.agent.pb.GroupStateOrBuilder> 
         getGroupsOrBuilderList() {
      if (groupsBuilder_ != null) {
        return groupsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(groups_);
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupState groups = 1;</code>
     */
    public cloud.spawnery.agent.pb.GroupState.Builder addGroupsBuilder() {
      return internalGetGroupsFieldBuilder().addBuilder(
          cloud.spawnery.agent.pb.GroupState.getDefaultInstance());
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupState groups = 1;</code>
     */
    public cloud.spawnery.agent.pb.GroupState.Builder addGroupsBuilder(
        int index) {
      return internalGetGroupsFieldBuilder().addBuilder(
          index, cloud.spawnery.agent.pb.GroupState.getDefaultInstance());
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupState groups = 1;</code>
     */
    public java.util.List<cloud.spawnery.agent.pb.GroupState.Builder> 
         getGroupsBuilderList() {
      return internalGetGroupsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.spawnery.agent.pb.GroupState, cloud.spawnery.agent.pb.GroupState.Builder, cloud.spawnery.agent.pb.GroupStateOrBuilder> 
        internalGetGroupsFieldBuilder() {
      if (groupsBuilder_ == null) {
        groupsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            cloud.spawnery.agent.pb.GroupState, cloud.spawnery.agent.pb.GroupState.Builder, cloud.spawnery.agent.pb.GroupStateOrBuilder>(
                groups_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        groups_ = null;
      }
      return groupsBuilder_;
    }

    private java.util.List<cloud.spawnery.agent.pb.ServerState> servers_ =
      java.util.Collections.emptyList();
    private void ensureServersIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        servers_ = new java.util.ArrayList<cloud.spawnery.agent.pb.ServerState>(servers_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.spawnery.agent.pb.ServerState, cloud.spawnery.agent.pb.ServerState.Builder, cloud.spawnery.agent.pb.ServerStateOrBuilder> serversBuilder_;

    /**
     * <code>repeated .spawnery.agent.v1alpha1.ServerState servers = 2;</code>
     */
    public java.util.List<cloud.spawnery.agent.pb.ServerState> getServersList() {
      if (serversBuilder_ == null) {
        return java.util.Collections.unmodifiableList(servers_);
      } else {
        return serversBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.ServerState servers = 2;</code>
     */
    public int getServersCount() {
      if (serversBuilder_ == null) {
        return servers_.size();
      } else {
        return serversBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.ServerState servers = 2;</code>
     */
    public cloud.spawnery.agent.pb.ServerState getServers(int index) {
      if (serversBuilder_ == null) {
        return servers_.get(index);
      } else {
        return serversBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.ServerState servers = 2;</code>
     */
    public Builder setServers(
        int index, cloud.spawnery.agent.pb.ServerState value) {
      if (serversBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServersIsMutable();
        servers_.set(index, value);
        onChanged();
      } else {
        serversBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.ServerState servers = 2;</code>
     */
    public Builder setServers(
        int index, cloud.spawnery.agent.pb.ServerState.Builder builderForValue) {
      if (serversBuilder_ == null) {
        ensureServersIsMutable();
        servers_.set(index, builderForValue.build());
        onChanged();
      } else {
        serversBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.ServerState servers = 2;</code>
     */
    public Builder addServers(cloud.spawnery.agent.pb.ServerState value) {
      if (serversBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServersIsMutable();
        servers_.add(value);
        onChanged();
      } else {
        serversBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.ServerState servers = 2;</code>
     */
    public Builder addServers(
        int index, cloud.spawnery.agent.pb.ServerState value) {
      if (serversBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServersIsMutable();
        servers_.add(index, value);
        onChanged();
      } else {
        serversBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.ServerState servers = 2;</code>
     */
    public Builder addServers(
        cloud.spawnery.agent.pb.ServerState.Builder builderForValue) {
      if (serversBuilder_ == null) {
        ensureServersIsMutable();
        servers_.add(builderForValue.build());
        onChanged();
      } else {
        serversBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.ServerState servers = 2;</code>
     */
    public Builder addServers(
        int index, cloud.spawnery.agent.pb.ServerState.Builder builderForValue) {
      if (serversBuilder_ == null) {
        ensureServersIsMutable();
        servers_.add(index, builderForValue.build());
        onChanged();
      } else {
        serversBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.ServerState servers = 2;</code>
     */
    public Builder addAllServers(
        java.lang.Iterable<? extends cloud.spawnery.agent.pb.ServerState> values) {
      if (serversBuilder_ == null) {
        ensureServersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, servers_);
        onChanged();
      } else {
        serversBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.ServerState servers = 2;</code>
     */
    public Builder clearServers() {
      if (serversBuilder_ == null) {
        servers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        serversBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.ServerState servers = 2;</code>
     */
    public Builder removeServers(int index) {
      if (serversBuilder_ == null) {
        ensureServersIsMutable();
        servers_.remove(index);
        onChanged();
      } else {
        serversBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.ServerState servers = 2;</code>
     */
    public cloud.spawnery.agent.pb.ServerState.Builder getServersBuilder(
        int index) {
      return internalGetServersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.ServerState servers = 2;</code>
     */
    public cloud.spawnery.agent.pb.ServerStateOrBuilder getServersOrBuilder(
        int index) {
      if (serversBuilder_ == null) {
        return servers_.get(index);  } else {
        return serversBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.ServerState servers = 2;</code>
     */
    public java.util.List<? extends cloud.spawnery.agent.pb.ServerStateOrBuilder> 
         getServersOrBuilderList() {
      if (serversBuilder_ != null) {
        return serversBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(servers_);
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.ServerState servers = 2;</code>
     */
    public cloud.spawnery.agent.pb.ServerState.Builder addServersBuilder() {
      return internalGetServersFieldBuilder().addBuilder(
          cloud.spawnery.agent.pb.ServerState.getDefaultInstance());
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.ServerState servers = 2;</code>
     */
    public cloud.spawnery.agent.pb.ServerState.Builder addServersBuilder(
        int index) {
      return internalGetServersFieldBuilder().addBuilder(
          index, cloud.spawnery.agent.pb.ServerState.getDefaultInstance());
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.ServerState servers = 2;</code>
     */
    public java.util.List<cloud.spawnery.agent.pb.ServerState.Builder> 
         getServersBuilderList() {
      return internalGetServersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.spawnery.agent.pb.ServerState, cloud.spawnery.agent.pb.ServerState.Builder, cloud.spawnery.agent.pb.ServerStateOrBuilder> 
        internalGetServersFieldBuilder() {
      if (serversBuilder_ == null) {
        serversBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            cloud.spawnery.agent.pb.ServerState, cloud.spawnery.agent.pb.ServerState.Builder, cloud.spawnery.agent.pb.ServerStateOrBuilder>(
                servers_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        servers_ = null;
      }
      return serversBuilder_;
    }

    private java.util.List<cloud.spawnery.agent.pb.RosterEntry> players_ =
      java.util.Collections.emptyList();
    private void ensurePlayersIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        players_ = new java.util.ArrayList<cloud.spawnery.agent.pb.RosterEntry>(players_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.spawnery.agent.pb.RosterEntry, cloud.spawnery.agent.pb.RosterEntry.Builder, cloud.spawnery.agent.pb.RosterEntryOrBuilder> playersBuilder_;

    /**
     * <pre>
     * Every player on this network, aggregated across the proxies. Empty when
     * no proxy has reported recently -- which is a real state and not an error,
     * and is why the API documents an empty list as ordinary.
     * </pre>
     *
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 3;</code>
     */
    public java.util.List<cloud.spawnery.agent.pb.RosterEntry> getPlayersList() {
      if (playersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(players_);
      } else {
        return playersBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Every player on this network, aggregated across the proxies. Empty when
     * no proxy has reported recently -- which is a real state and not an error,
     * and is why the API documents an empty list as ordinary.
     * </pre>
     *
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 3;</code>
     */
    public int getPlayersCount() {
      if (playersBuilder_ == null) {
        return players_.size();
      } else {
        return playersBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Every player on this network, aggregated across the proxies. Empty when
     * no proxy has reported recently -- which is a real state and not an error,
     * and is why the API documents an empty list as ordinary.
     * </pre>
     *
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 3;</code>
     */
    public cloud.spawnery.agent.pb.RosterEntry getPlayers(int index) {
      if (playersBuilder_ == null) {
        return players_.get(index);
      } else {
        return playersBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Every player on this network, aggregated across the proxies. Empty when
     * no proxy has reported recently -- which is a real state and not an error,
     * and is why the API documents an empty list as ordinary.
     * </pre>
     *
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 3;</code>
     */
    public Builder setPlayers(
        int index, cloud.spawnery.agent.pb.RosterEntry value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.set(index, value);
        onChanged();
      } else {
        playersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Every player on this network, aggregated across the proxies. Empty when
     * no proxy has reported recently -- which is a real state and not an error,
     * and is why the API documents an empty list as ordinary.
     * </pre>
     *
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 3;</code>
     */
    public Builder setPlayers(
        int index, cloud.spawnery.agent.pb.RosterEntry.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.set(index, builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Every player on this network, aggregated across the proxies. Empty when
     * no proxy has reported recently -- which is a real state and not an error,
     * and is why the API documents an empty list as ordinary.
     * </pre>
     *
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 3;</code>
     */
    public Builder addPlayers(cloud.spawnery.agent.pb.RosterEntry value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.add(value);
        onChanged();
      } else {
        playersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Every player on this network, aggregated across the proxies. Empty when
     * no proxy has reported recently -- which is a real state and not an error,
     * and is why the API documents an empty list as ordinary.
     * </pre>
     *
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 3;</code>
     */
    public Builder addPlayers(
        int index, cloud.spawnery.agent.pb.RosterEntry value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.add(index, value);
        onChanged();
      } else {
        playersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Every player on this network, aggregated across the proxies. Empty when
     * no proxy has reported recently -- which is a real state and not an error,
     * and is why the API documents an empty list as ordinary.
     * </pre>
     *
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 3;</code>
     */
    public Builder addPlayers(
        cloud.spawnery.agent.pb.RosterEntry.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.add(builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Every player on this network, aggregated across the proxies. Empty when
     * no proxy has reported recently -- which is a real state and not an error,
     * and is why the API documents an empty list as ordinary.
     * </pre>
     *
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 3;</code>
     */
    public Builder addPlayers(
        int index, cloud.spawnery.agent.pb.RosterEntry.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.add(index, builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Every player on this network, aggregated across the proxies. Empty when
     * no proxy has reported recently -- which is a real state and not an error,
     * and is why the API documents an empty list as ordinary.
     * </pre>
     *
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 3;</code>
     */
    public Builder addAllPlayers(
        java.lang.Iterable<? extends cloud.spawnery.agent.pb.RosterEntry> values) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, players_);
        onChanged();
      } else {
        playersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Every player on this network, aggregated across the proxies. Empty when
     * no proxy has reported recently -- which is a real state and not an error,
     * and is why the API documents an empty list as ordinary.
     * </pre>
     *
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 3;</code>
     */
    public Builder clearPlayers() {
      if (playersBuilder_ == null) {
        players_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        playersBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Every player on this network, aggregated across the proxies. Empty when
     * no proxy has reported recently -- which is a real state and not an error,
     * and is why the API documents an empty list as ordinary.
     * </pre>
     *
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 3;</code>
     */
    public Builder removePlayers(int index) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.remove(index);
        onChanged();
      } else {
        playersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Every player on this network, aggregated across the proxies. Empty when
     * no proxy has reported recently -- which is a real state and not an error,
     * and is why the API documents an empty list as ordinary.
     * </pre>
     *
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 3;</code>
     */
    public cloud.spawnery.agent.pb.RosterEntry.Builder getPlayersBuilder(
        int index) {
      return internalGetPlayersFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Every player on this network, aggregated across the proxies. Empty when
     * no proxy has reported recently -- which is a real state and not an error,
     * and is why the API documents an empty list as ordinary.
     * </pre>
     *
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 3;</code>
     */
    public cloud.spawnery.agent.pb.RosterEntryOrBuilder getPlayersOrBuilder(
        int index) {
      if (playersBuilder_ == null) {
        return players_.get(index);  } else {
        return playersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Every player on this network, aggregated across the proxies. Empty when
     * no proxy has reported recently -- which is a real state and not an error,
     * and is why the API documents an empty list as ordinary.
     * </pre>
     *
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 3;</code>
     */
    public java.util.List<? extends cloud.spawnery.agent.pb.RosterEntryOrBuilder> 
         getPlayersOrBuilderList() {
      if (playersBuilder_ != null) {
        return playersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(players_);
      }
    }
    /**
     * <pre>
     * Every player on this network, aggregated across the proxies. Empty when
     * no proxy has reported recently -- which is a real state and not an error,
     * and is why the API documents an empty list as ordinary.
     * </pre>
     *
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 3;</code>
     */
    public cloud.spawnery.agent.pb.RosterEntry.Builder addPlayersBuilder() {
      return internalGetPlayersFieldBuilder().addBuilder(
          cloud.spawnery.agent.pb.RosterEntry.getDefaultInstance());
    }
    /**
     * <pre>
     * Every player on this network, aggregated across the proxies. Empty when
     * no proxy has reported recently -- which is a real state and not an error,
     * and is why the API documents an empty list as ordinary.
     * </pre>
     *
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 3;</code>
     */
    public cloud.spawnery.agent.pb.RosterEntry.Builder addPlayersBuilder(
        int index) {
      return internalGetPlayersFieldBuilder().addBuilder(
          index, cloud.spawnery.agent.pb.RosterEntry.getDefaultInstance());
    }
    /**
     * <pre>
     * Every player on this network, aggregated across the proxies. Empty when
     * no proxy has reported recently -- which is a real state and not an error,
     * and is why the API documents an empty list as ordinary.
     * </pre>
     *
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 3;</code>
     */
    public java.util.List<cloud.spawnery.agent.pb.RosterEntry.Builder> 
         getPlayersBuilderList() {
      return internalGetPlayersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.spawnery.agent.pb.RosterEntry, cloud.spawnery.agent.pb.RosterEntry.Builder, cloud.spawnery.agent.pb.RosterEntryOrBuilder> 
        internalGetPlayersFieldBuilder() {
      if (playersBuilder_ == null) {
        playersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            cloud.spawnery.agent.pb.RosterEntry, cloud.spawnery.agent.pb.RosterEntry.Builder, cloud.spawnery.agent.pb.RosterEntryOrBuilder>(
                players_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        players_ = null;
      }
      return playersBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:spawnery.agent.v1alpha1.NetworkState)
  }

  // @@protoc_insertion_point(class_scope:spawnery.agent.v1alpha1.NetworkState)
  private static final cloud.spawnery.agent.pb.NetworkState DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.spawnery.agent.pb.NetworkState();
  }

  public static cloud.spawnery.agent.pb.NetworkState getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NetworkState>
      PARSER = new com.google.protobuf.AbstractParser<NetworkState>() {
    @java.lang.Override
    public NetworkState parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<NetworkState> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NetworkState> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.spawnery.agent.pb.NetworkState getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

