// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

/**
 * Protobuf type {@code spawnery.agent.v1alpha1.OperatorToProxy}
 */
@com.google.protobuf.Generated
public final class OperatorToProxy extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:spawnery.agent.v1alpha1.OperatorToProxy)
    OperatorToProxyOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "OperatorToProxy");
  }
  // Use OperatorToProxy.newBuilder() to construct.
  private OperatorToProxy(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private OperatorToProxy() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_OperatorToProxy_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_OperatorToProxy_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_OperatorToProxy_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.spawnery.agent.pb.OperatorToProxy.class, cloud.spawnery.agent.pb.OperatorToProxy.Builder.class);
  }

  private int messageCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object message_;
  public enum MessageCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    FULL_SYNC(1),
    REGISTER_SERVER(2),
    UNREGISTER_SERVER(3),
    DRAIN_PLAYERS(4),
    REPORT_INTERVAL(5),
    SESSION_DEADLINE(6),
    SET_READY(7),
    NETWORK_STATE(8),
    CLOUD_RESPONSE(9),
    MOVE_PLAYER(10),
    MESSAGE_NOT_SET(0);
    private final int value;
    private MessageCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageCase valueOf(int value) {
      return forNumber(value);
    }

    public static MessageCase forNumber(int value) {
      switch (value) {
        case 1: return FULL_SYNC;
        case 2: return REGISTER_SERVER;
        case 3: return UNREGISTER_SERVER;
        case 4: return DRAIN_PLAYERS;
        case 5: return REPORT_INTERVAL;
        case 6: return SESSION_DEADLINE;
        case 7: return SET_READY;
        case 8: return NETWORK_STATE;
        case 9: return CLOUD_RESPONSE;
        case 10: return MOVE_PLAYER;
        case 0: return MESSAGE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MessageCase
  getMessageCase() {
    return MessageCase.forNumber(
        messageCase_);
  }

  public static final int FULL_SYNC_FIELD_NUMBER = 1;
  /**
   * <code>.spawnery.agent.v1alpha1.FullSync full_sync = 1;</code>
   * @return Whether the fullSync field is set.
   */
  @java.lang.Override
  public boolean hasFullSync() {
    return messageCase_ == 1;
  }
  /**
   * <code>.spawnery.agent.v1alpha1.FullSync full_sync = 1;</code>
   * @return The fullSync.
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.FullSync getFullSync() {
    if (messageCase_ == 1) {
       return (cloud.spawnery.agent.pb.FullSync) message_;
    }
    return cloud.spawnery.agent.pb.FullSync.getDefaultInstance();
  }
  /**
   * <code>.spawnery.agent.v1alpha1.FullSync full_sync = 1;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.FullSyncOrBuilder getFullSyncOrBuilder() {
    if (messageCase_ == 1) {
       return (cloud.spawnery.agent.pb.FullSync) message_;
    }
    return cloud.spawnery.agent.pb.FullSync.getDefaultInstance();
  }

  public static final int REGISTER_SERVER_FIELD_NUMBER = 2;
  /**
   * <code>.spawnery.agent.v1alpha1.RegisterServer register_server = 2;</code>
   * @return Whether the registerServer field is set.
   */
  @java.lang.Override
  public boolean hasRegisterServer() {
    return messageCase_ == 2;
  }
  /**
   * <code>.spawnery.agent.v1alpha1.RegisterServer register_server = 2;</code>
   * @return The registerServer.
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.RegisterServer getRegisterServer() {
    if (messageCase_ == 2) {
       return (cloud.spawnery.agent.pb.RegisterServer) message_;
    }
    return cloud.spawnery.agent.pb.RegisterServer.getDefaultInstance();
  }
  /**
   * <code>.spawnery.agent.v1alpha1.RegisterServer register_server = 2;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.RegisterServerOrBuilder getRegisterServerOrBuilder() {
    if (messageCase_ == 2) {
       return (cloud.spawnery.agent.pb.RegisterServer) message_;
    }
    return cloud.spawnery.agent.pb.RegisterServer.getDefaultInstance();
  }

  public static final int UNREGISTER_SERVER_FIELD_NUMBER = 3;
  /**
   * <code>.spawnery.agent.v1alpha1.UnregisterServer unregister_server = 3;</code>
   * @return Whether the unregisterServer field is set.
   */
  @java.lang.Override
  public boolean hasUnregisterServer() {
    return messageCase_ == 3;
  }
  /**
   * <code>.spawnery.agent.v1alpha1.UnregisterServer unregister_server = 3;</code>
   * @return The unregisterServer.
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.UnregisterServer getUnregisterServer() {
    if (messageCase_ == 3) {
       return (cloud.spawnery.agent.pb.UnregisterServer) message_;
    }
    return cloud.spawnery.agent.pb.UnregisterServer.getDefaultInstance();
  }
  /**
   * <code>.spawnery.agent.v1alpha1.UnregisterServer unregister_server = 3;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.UnregisterServerOrBuilder getUnregisterServerOrBuilder() {
    if (messageCase_ == 3) {
       return (cloud.spawnery.agent.pb.UnregisterServer) message_;
    }
    return cloud.spawnery.agent.pb.UnregisterServer.getDefaultInstance();
  }

  public static final int DRAIN_PLAYERS_FIELD_NUMBER = 4;
  /**
   * <code>.spawnery.agent.v1alpha1.DrainPlayers drain_players = 4;</code>
   * @return Whether the drainPlayers field is set.
   */
  @java.lang.Override
  public boolean hasDrainPlayers() {
    return messageCase_ == 4;
  }
  /**
   * <code>.spawnery.agent.v1alpha1.DrainPlayers drain_players = 4;</code>
   * @return The drainPlayers.
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.DrainPlayers getDrainPlayers() {
    if (messageCase_ == 4) {
       return (cloud.spawnery.agent.pb.DrainPlayers) message_;
    }
    return cloud.spawnery.agent.pb.DrainPlayers.getDefaultInstance();
  }
  /**
   * <code>.spawnery.agent.v1alpha1.DrainPlayers drain_players = 4;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.DrainPlayersOrBuilder getDrainPlayersOrBuilder() {
    if (messageCase_ == 4) {
       return (cloud.spawnery.agent.pb.DrainPlayers) message_;
    }
    return cloud.spawnery.agent.pb.DrainPlayers.getDefaultInstance();
  }

  public static final int REPORT_INTERVAL_FIELD_NUMBER = 5;
  /**
   * <code>.spawnery.agent.v1alpha1.ReportInterval report_interval = 5;</code>
   * @return Whether the reportInterval field is set.
   */
  @java.lang.Override
  public boolean hasReportInterval() {
    return messageCase_ == 5;
  }
  /**
   * <code>.spawnery.agent.v1alpha1.ReportInterval report_interval = 5;</code>
   * @return The reportInterval.
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.ReportInterval getReportInterval() {
    if (messageCase_ == 5) {
       return (cloud.spawnery.agent.pb.ReportInterval) message_;
    }
    return cloud.spawnery.agent.pb.ReportInterval.getDefaultInstance();
  }
  /**
   * <code>.spawnery.agent.v1alpha1.ReportInterval report_interval = 5;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.ReportIntervalOrBuilder getReportIntervalOrBuilder() {
    if (messageCase_ == 5) {
       return (cloud.spawnery.agent.pb.ReportInterval) message_;
    }
    return cloud.spawnery.agent.pb.ReportInterval.getDefaultInstance();
  }

  public static final int SESSION_DEADLINE_FIELD_NUMBER = 6;
  /**
   * <code>.spawnery.agent.v1alpha1.SessionDeadline session_deadline = 6;</code>
   * @return Whether the sessionDeadline field is set.
   */
  @java.lang.Override
  public boolean hasSessionDeadline() {
    return messageCase_ == 6;
  }
  /**
   * <code>.spawnery.agent.v1alpha1.SessionDeadline session_deadline = 6;</code>
   * @return The sessionDeadline.
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.SessionDeadline getSessionDeadline() {
    if (messageCase_ == 6) {
       return (cloud.spawnery.agent.pb.SessionDeadline) message_;
    }
    return cloud.spawnery.agent.pb.SessionDeadline.getDefaultInstance();
  }
  /**
   * <code>.spawnery.agent.v1alpha1.SessionDeadline session_deadline = 6;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.SessionDeadlineOrBuilder getSessionDeadlineOrBuilder() {
    if (messageCase_ == 6) {
       return (cloud.spawnery.agent.pb.SessionDeadline) message_;
    }
    return cloud.spawnery.agent.pb.SessionDeadline.getDefaultInstance();
  }

  public static final int SET_READY_FIELD_NUMBER = 7;
  /**
   * <code>.spawnery.agent.v1alpha1.SetReady set_ready = 7;</code>
   * @return Whether the setReady field is set.
   */
  @java.lang.Override
  public boolean hasSetReady() {
    return messageCase_ == 7;
  }
  /**
   * <code>.spawnery.agent.v1alpha1.SetReady set_ready = 7;</code>
   * @return The setReady.
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.SetReady getSetReady() {
    if (messageCase_ == 7) {
       return (cloud.spawnery.agent.pb.SetReady) message_;
    }
    return cloud.spawnery.agent.pb.SetReady.getDefaultInstance();
  }
  /**
   * <code>.spawnery.agent.v1alpha1.SetReady set_ready = 7;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.SetReadyOrBuilder getSetReadyOrBuilder() {
    if (messageCase_ == 7) {
       return (cloud.spawnery.agent.pb.SetReady) message_;
    }
    return cloud.spawnery.agent.pb.SetReady.getDefaultInstance();
  }

  public static final int NETWORK_STATE_FIELD_NUMBER = 8;
  /**
   * <code>.spawnery.agent.v1alpha1.NetworkState network_state = 8;</code>
   * @return Whether the networkState field is set.
   */
  @java.lang.Override
  public boolean hasNetworkState() {
    return messageCase_ == 8;
  }
  /**
   * <code>.spawnery.agent.v1alpha1.NetworkState network_state = 8;</code>
   * @return The networkState.
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.NetworkState getNetworkState() {
    if (messageCase_ == 8) {
       return (cloud.spawnery.agent.pb.NetworkState) message_;
    }
    return cloud.spawnery.agent.pb.NetworkState.getDefaultInstance();
  }
  /**
   * <code>.spawnery.agent.v1alpha1.NetworkState network_state = 8;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.NetworkStateOrBuilder getNetworkStateOrBuilder() {
    if (messageCase_ == 8) {
       return (cloud.spawnery.agent.pb.NetworkState) message_;
    }
    return cloud.spawnery.agent.pb.NetworkState.getDefaultInstance();
  }

  public static final int CLOUD_RESPONSE_FIELD_NUMBER = 9;
  /**
   * <code>.spawnery.agent.v1alpha1.CloudResponse cloud_response = 9;</code>
   * @return Whether the cloudResponse field is set.
   */
  @java.lang.Override
  public boolean hasCloudResponse() {
    return messageCase_ == 9;
  }
  /**
   * <code>.spawnery.agent.v1alpha1.CloudResponse cloud_response = 9;</code>
   * @return The cloudResponse.
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.CloudResponse getCloudResponse() {
    if (messageCase_ == 9) {
       return (cloud.spawnery.agent.pb.CloudResponse) message_;
    }
    return cloud.spawnery.agent.pb.CloudResponse.getDefaultInstance();
  }
  /**
   * <code>.spawnery.agent.v1alpha1.CloudResponse cloud_response = 9;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.CloudResponseOrBuilder getCloudResponseOrBuilder() {
    if (messageCase_ == 9) {
       return (cloud.spawnery.agent.pb.CloudResponse) message_;
    }
    return cloud.spawnery.agent.pb.CloudResponse.getDefaultInstance();
  }

  public static final int MOVE_PLAYER_FIELD_NUMBER = 10;
  /**
   * <code>.spawnery.agent.v1alpha1.MovePlayer move_player = 10;</code>
   * @return Whether the movePlayer field is set.
   */
  @java.lang.Override
  public boolean hasMovePlayer() {
    return messageCase_ == 10;
  }
  /**
   * <code>.spawnery.agent.v1alpha1.MovePlayer move_player = 10;</code>
   * @return The movePlayer.
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.MovePlayer getMovePlayer() {
    if (messageCase_ == 10) {
       return (cloud.spawnery.agent.pb.MovePlayer) message_;
    }
    return cloud.spawnery.agent.pb.MovePlayer.getDefaultInstance();
  }
  /**
   * <code>.spawnery.agent.v1alpha1.MovePlayer move_player = 10;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.MovePlayerOrBuilder getMovePlayerOrBuilder() {
    if (messageCase_ == 10) {
       return (cloud.spawnery.agent.pb.MovePlayer) message_;
    }
    return cloud.spawnery.agent.pb.MovePlayer.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageCase_ == 1) {
      output.writeMessage(1, (cloud.spawnery.agent.pb.FullSync) message_);
    }
    if (messageCase_ == 2) {
      output.writeMessage(2, (cloud.spawnery.agent.pb.RegisterServer) message_);
    }
    if (messageCase_ == 3) {
      output.writeMessage(3, (cloud.spawnery.agent.pb.UnregisterServer) message_);
    }
    if (messageCase_ == 4) {
      output.writeMessage(4, (cloud.spawnery.agent.pb.DrainPlayers) message_);
    }
    if (messageCase_ == 5) {
      output.writeMessage(5, (cloud.spawnery.agent.pb.ReportInterval) message_);
    }
    if (messageCase_ == 6) {
      output.writeMessage(6, (cloud.spawnery.agent.pb.SessionDeadline) message_);
    }
    if (messageCase_ == 7) {
      output.writeMessage(7, (cloud.spawnery.agent.pb.SetReady) message_);
    }
    if (messageCase_ == 8) {
      output.writeMessage(8, (cloud.spawnery.agent.pb.NetworkState) message_);
    }
    if (messageCase_ == 9) {
      output.writeMessage(9, (cloud.spawnery.agent.pb.CloudResponse) message_);
    }
    if (messageCase_ == 10) {
      output.writeMessage(10, (cloud.spawnery.agent.pb.MovePlayer) message_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (messageCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (cloud.spawnery.agent.pb.FullSync) message_);
    }
    if (messageCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (cloud.spawnery.agent.pb.RegisterServer) message_);
    }
    if (messageCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (cloud.spawnery.agent.pb.UnregisterServer) message_);
    }
    if (messageCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (cloud.spawnery.agent.pb.DrainPlayers) message_);
    }
    if (messageCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (cloud.spawnery.agent.pb.ReportInterval) message_);
    }
    if (messageCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (cloud.spawnery.agent.pb.SessionDeadline) message_);
    }
    if (messageCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (cloud.spawnery.agent.pb.SetReady) message_);
    }
    if (messageCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (cloud.spawnery.agent.pb.NetworkState) message_);
    }
    if (messageCase_ == 9) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, (cloud.spawnery.agent.pb.CloudResponse) message_);
    }
    if (messageCase_ == 10) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, (cloud.spawnery.agent.pb.MovePlayer) message_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.spawnery.agent.pb.OperatorToProxy)) {
      return super.equals(obj);
    }
    cloud.spawnery.agent.pb.OperatorToProxy other = (cloud.spawnery.agent.pb.OperatorToProxy) obj;

    if (!getMessageCase().equals(other.getMessageCase())) return false;
    switch (messageCase_) {
      case 1:
        if (!getFullSync()
            .equals(other.getFullSync())) return false;
        break;
      case 2:
        if (!getRegisterServer()
            .equals(other.getRegisterServer())) return false;
        break;
      case 3:
        if (!getUnregisterServer()
            .equals(other.getUnregisterServer())) return false;
        break;
      case 4:
        if (!getDrainPlayers()
            .equals(other.getDrainPlayers())) return false;
        break;
      case 5:
        if (!getReportInterval()
            .equals(other.getReportInterval())) return false;
        break;
      case 6:
        if (!getSessionDeadline()
            .equals(other.getSessionDeadline())) return false;
        break;
      case 7:
        if (!getSetReady()
            .equals(other.getSetReady())) return false;
        break;
      case 8:
        if (!getNetworkState()
            .equals(other.getNetworkState())) return false;
        break;
      case 9:
        if (!getCloudResponse()
            .equals(other.getCloudResponse())) return false;
        break;
      case 10:
        if (!getMovePlayer()
            .equals(other.getMovePlayer())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (messageCase_) {
      case 1:
        hash = (37 * hash) + FULL_SYNC_FIELD_NUMBER;
        hash = (53 * hash) + getFullSync().hashCode();
        break;
      case 2:
        hash = (37 * hash) + REGISTER_SERVER_FIELD_NUMBER;
        hash = (53 * hash) + getRegisterServer().hashCode();
        break;
      case 3:
        hash = (37 * hash) + UNREGISTER_SERVER_FIELD_NUMBER;
        hash = (53 * hash) + getUnregisterServer().hashCode();
        break;
      case 4:
        hash = (37 * hash) + DRAIN_PLAYERS_FIELD_NUMBER;
        hash = (53 * hash) + getDrainPlayers().hashCode();
        break;
      case 5:
        hash = (37 * hash) + REPORT_INTERVAL_FIELD_NUMBER;
        hash = (53 * hash) + getReportInterval().hashCode();
        break;
      case 6:
        hash = (37 * hash) + SESSION_DEADLINE_FIELD_NUMBER;
        hash = (53 * hash) + getSessionDeadline().hashCode();
        break;
      case 7:
        hash = (37 * hash) + SET_READY_FIELD_NUMBER;
        hash = (53 * hash) + getSetReady().hashCode();
        break;
      case 8:
        hash = (37 * hash) + NETWORK_STATE_FIELD_NUMBER;
        hash = (53 * hash) + getNetworkState().hashCode();
        break;
      case 9:
        hash = (37 * hash) + CLOUD_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getCloudResponse().hashCode();
        break;
      case 10:
        hash = (37 * hash) + MOVE_PLAYER_FIELD_NUMBER;
        hash = (53 * hash) + getMovePlayer().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.spawnery.agent.pb.OperatorToProxy parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.OperatorToProxy parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.OperatorToProxy parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.OperatorToProxy parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.OperatorToProxy parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.OperatorToProxy parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.OperatorToProxy parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.OperatorToProxy parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.spawnery.agent.pb.OperatorToProxy parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.spawnery.agent.pb.OperatorToProxy parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.OperatorToProxy parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.OperatorToProxy parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.spawnery.agent.pb.OperatorToProxy prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code spawnery.agent.v1alpha1.OperatorToProxy}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:spawnery.agent.v1alpha1.OperatorToProxy)
      cloud.spawnery.agent.pb.OperatorToProxyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_OperatorToProxy_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_OperatorToProxy_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.spawnery.agent.pb.OperatorToProxy.class, cloud.spawnery.agent.pb.OperatorToProxy.Builder.class);
    }

    // Construct using cloud.spawnery.agent.pb.OperatorToProxy.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (fullSyncBuilder_ != null) {
        fullSyncBuilder_.clear();
      }
      if (registerServerBuilder_ != null) {
        registerServerBuilder_.clear();
      }
      if (unregisterServerBuilder_ != null) {
        unregisterServerBuilder_.clear();
      }
      if (drainPlayersBuilder_ != null) {
        drainPlayersBuilder_.clear();
      }
      if (reportIntervalBuilder_ != null) {
        reportIntervalBuilder_.clear();
      }
      if (sessionDeadlineBuilder_ != null) {
        sessionDeadlineBuilder_.clear();
      }
      if (setReadyBuilder_ != null) {
        setReadyBuilder_.clear();
      }
      if (networkStateBuilder_ != null) {
        networkStateBuilder_.clear();
      }
      if (cloudResponseBuilder_ != null) {
        cloudResponseBuilder_.clear();
      }
      if (movePlayerBuilder_ != null) {
        movePlayerBuilder_.clear();
      }
      messageCase_ = 0;
      message_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_OperatorToProxy_descriptor;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.OperatorToProxy getDefaultInstanceForType() {
      return cloud.spawnery.agent.pb.OperatorToProxy.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.OperatorToProxy build() {
      cloud.spawnery.agent.pb.OperatorToProxy result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.OperatorToProxy buildPartial() {
      cloud.spawnery.agent.pb.OperatorToProxy result = new cloud.spawnery.agent.pb.OperatorToProxy(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(cloud.spawnery.agent.pb.OperatorToProxy result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(cloud.spawnery.agent.pb.OperatorToProxy result) {
      result.messageCase_ = messageCase_;
      result.message_ = this.message_;
      if (messageCase_ == 1 &&
          fullSyncBuilder_ != null) {
        result.message_ = fullSyncBuilder_.build();
      }
      if (messageCase_ == 2 &&
          registerServerBuilder_ != null) {
        result.message_ = registerServerBuilder_.build();
      }
      if (messageCase_ == 3 &&
          unregisterServerBuilder_ != null) {
        result.message_ = unregisterServerBuilder_.build();
      }
      if (messageCase_ == 4 &&
          drainPlayersBuilder_ != null) {
        result.message_ = drainPlayersBuilder_.build();
      }
      if (messageCase_ == 5 &&
          reportIntervalBuilder_ != null) {
        result.message_ = reportIntervalBuilder_.build();
      }
      if (messageCase_ == 6 &&
          sessionDeadlineBuilder_ != null) {
        result.message_ = sessionDeadlineBuilder_.build();
      }
      if (messageCase_ == 7 &&
          setReadyBuilder_ != null) {
        result.message_ = setReadyBuilder_.build();
      }
      if (messageCase_ == 8 &&
          networkStateBuilder_ != null) {
        result.message_ = networkStateBuilder_.build();
      }
      if (messageCase_ == 9 &&
          cloudResponseBuilder_ != null) {
        result.message_ = cloudResponseBuilder_.build();
      }
      if (messageCase_ == 10 &&
          movePlayerBuilder_ != null) {
        result.message_ = movePlayerBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.spawnery.agent.pb.OperatorToProxy) {
        return mergeFrom((cloud.spawnery.agent.pb.OperatorToProxy)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.spawnery.agent.pb.OperatorToProxy other) {
      if (other == cloud.spawnery.agent.pb.OperatorToProxy.getDefaultInstance()) return this;
      switch (other.getMessageCase()) {
        case FULL_SYNC: {
          mergeFullSync(other.getFullSync());
          break;
        }
        case REGISTER_SERVER: {
          mergeRegisterServer(other.getRegisterServer());
          break;
        }
        case UNREGISTER_SERVER: {
          mergeUnregisterServer(other.getUnregisterServer());
          break;
        }
        case DRAIN_PLAYERS: {
          mergeDrainPlayers(other.getDrainPlayers());
          break;
        }
        case REPORT_INTERVAL: {
          mergeReportInterval(other.getReportInterval());
          break;
        }
        case SESSION_DEADLINE: {
          mergeSessionDeadline(other.getSessionDeadline());
          break;
        }
        case SET_READY: {
          mergeSetReady(other.getSetReady());
          break;
        }
        case NETWORK_STATE: {
          mergeNetworkState(other.getNetworkState());
          break;
        }
        case CLOUD_RESPONSE: {
          mergeCloudResponse(other.getCloudResponse());
          break;
        }
        case MOVE_PLAYER: {
          mergeMovePlayer(other.getMovePlayer());
          break;
        }
        case MESSAGE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetFullSyncFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetRegisterServerFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetUnregisterServerFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetDrainPlayersFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetReportIntervalFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 5;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  internalGetSessionDeadlineFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 6;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  internalGetSetReadyFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 7;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  internalGetNetworkStateFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 8;
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  internalGetCloudResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 9;
              break;
            } // case 74
            case 82: {
              input.readMessage(
                  internalGetMovePlayerFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 10;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int messageCase_ = 0;
    private java.lang.Object message_;
    public MessageCase
        getMessageCase() {
      return MessageCase.forNumber(
          messageCase_);
    }

    public Builder clearMessage() {
      messageCase_ = 0;
      message_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.FullSync, cloud.spawnery.agent.pb.FullSync.Builder, cloud.spawnery.agent.pb.FullSyncOrBuilder> fullSyncBuilder_;
    /**
     * <code>.spawnery.agent.v1alpha1.FullSync full_sync = 1;</code>
     * @return Whether the fullSync field is set.
     */
    @java.lang.Override
    public boolean hasFullSync() {
      return messageCase_ == 1;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.FullSync full_sync = 1;</code>
     * @return The fullSync.
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.FullSync getFullSync() {
      if (fullSyncBuilder_ == null) {
        if (messageCase_ == 1) {
          return (cloud.spawnery.agent.pb.FullSync) message_;
        }
        return cloud.spawnery.agent.pb.FullSync.getDefaultInstance();
      } else {
        if (messageCase_ == 1) {
          return fullSyncBuilder_.getMessage();
        }
        return cloud.spawnery.agent.pb.FullSync.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.FullSync full_sync = 1;</code>
     */
    public Builder setFullSync(cloud.spawnery.agent.pb.FullSync value) {
      if (fullSyncBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        fullSyncBuilder_.setMessage(value);
      }
      messageCase_ = 1;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.FullSync full_sync = 1;</code>
     */
    public Builder setFullSync(
        cloud.spawnery.agent.pb.FullSync.Builder builderForValue) {
      if (fullSyncBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        fullSyncBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 1;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.FullSync full_sync = 1;</code>
     */
    public Builder mergeFullSync(cloud.spawnery.agent.pb.FullSync value) {
      if (fullSyncBuilder_ == null) {
        if (messageCase_ == 1 &&
            message_ != cloud.spawnery.agent.pb.FullSync.getDefaultInstance()) {
          message_ = cloud.spawnery.agent.pb.FullSync.newBuilder((cloud.spawnery.agent.pb.FullSync) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 1) {
          fullSyncBuilder_.mergeFrom(value);
        } else {
          fullSyncBuilder_.setMessage(value);
        }
      }
      messageCase_ = 1;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.FullSync full_sync = 1;</code>
     */
    public Builder clearFullSync() {
      if (fullSyncBuilder_ == null) {
        if (messageCase_ == 1) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 1) {
          messageCase_ = 0;
          message_ = null;
        }
        fullSyncBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.FullSync full_sync = 1;</code>
     */
    public cloud.spawnery.agent.pb.FullSync.Builder getFullSyncBuilder() {
      return internalGetFullSyncFieldBuilder().getBuilder();
    }
    /**
     * <code>.spawnery.agent.v1alpha1.FullSync full_sync = 1;</code>
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.FullSyncOrBuilder getFullSyncOrBuilder() {
      if ((messageCase_ == 1) && (fullSyncBuilder_ != null)) {
        return fullSyncBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 1) {
          return (cloud.spawnery.agent.pb.FullSync) message_;
        }
        return cloud.spawnery.agent.pb.FullSync.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.FullSync full_sync = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.FullSync, cloud.spawnery.agent.pb.FullSync.Builder, cloud.spawnery.agent.pb.FullSyncOrBuilder> 
        internalGetFullSyncFieldBuilder() {
      if (fullSyncBuilder_ == null) {
        if (!(messageCase_ == 1)) {
          message_ = cloud.spawnery.agent.pb.FullSync.getDefaultInstance();
        }
        fullSyncBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cloud.spawnery.agent.pb.FullSync, cloud.spawnery.agent.pb.FullSync.Builder, cloud.spawnery.agent.pb.FullSyncOrBuilder>(
                (cloud.spawnery.agent.pb.FullSync) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 1;
      onChanged();
      return fullSyncBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.RegisterServer, cloud.spawnery.agent.pb.RegisterServer.Builder, cloud.spawnery.agent.pb.RegisterServerOrBuilder> registerServerBuilder_;
    /**
     * <code>.spawnery.agent.v1alpha1.RegisterServer register_server = 2;</code>
     * @return Whether the registerServer field is set.
     */
    @java.lang.Override
    public boolean hasRegisterServer() {
      return messageCase_ == 2;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.RegisterServer register_server = 2;</code>
     * @return The registerServer.
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.RegisterServer getRegisterServer() {
      if (registerServerBuilder_ == null) {
        if (messageCase_ == 2) {
          return (cloud.spawnery.agent.pb.RegisterServer) message_;
        }
        return cloud.spawnery.agent.pb.RegisterServer.getDefaultInstance();
      } else {
        if (messageCase_ == 2) {
          return registerServerBuilder_.getMessage();
        }
        return cloud.spawnery.agent.pb.RegisterServer.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.RegisterServer register_server = 2;</code>
     */
    public Builder setRegisterServer(cloud.spawnery.agent.pb.RegisterServer value) {
      if (registerServerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        registerServerBuilder_.setMessage(value);
      }
      messageCase_ = 2;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.RegisterServer register_server = 2;</code>
     */
    public Builder setRegisterServer(
        cloud.spawnery.agent.pb.RegisterServer.Builder builderForValue) {
      if (registerServerBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        registerServerBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 2;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.RegisterServer register_server = 2;</code>
     */
    public Builder mergeRegisterServer(cloud.spawnery.agent.pb.RegisterServer value) {
      if (registerServerBuilder_ == null) {
        if (messageCase_ == 2 &&
            message_ != cloud.spawnery.agent.pb.RegisterServer.getDefaultInstance()) {
          message_ = cloud.spawnery.agent.pb.RegisterServer.newBuilder((cloud.spawnery.agent.pb.RegisterServer) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 2) {
          registerServerBuilder_.mergeFrom(value);
        } else {
          registerServerBuilder_.setMessage(value);
        }
      }
      messageCase_ = 2;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.RegisterServer register_server = 2;</code>
     */
    public Builder clearRegisterServer() {
      if (registerServerBuilder_ == null) {
        if (messageCase_ == 2) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 2) {
          messageCase_ = 0;
          message_ = null;
        }
        registerServerBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.RegisterServer register_server = 2;</code>
     */
    public cloud.spawnery.agent.pb.RegisterServer.Builder getRegisterServerBuilder() {
      return internalGetRegisterServerFieldBuilder().getBuilder();
    }
    /**
     * <code>.spawnery.agent.v1alpha1.RegisterServer register_server = 2;</code>
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.RegisterServerOrBuilder getRegisterServerOrBuilder() {
      if ((messageCase_ == 2) && (registerServerBuilder_ != null)) {
        return registerServerBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 2) {
          return (cloud.spawnery.agent.pb.RegisterServer) message_;
        }
        return cloud.spawnery.agent.pb.RegisterServer.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.RegisterServer register_server = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.RegisterServer, cloud.spawnery.agent.pb.RegisterServer.Builder, cloud.spawnery.agent.pb.RegisterServerOrBuilder> 
        internalGetRegisterServerFieldBuilder() {
      if (registerServerBuilder_ == null) {
        if (!(messageCase_ == 2)) {
          message_ = cloud.spawnery.agent.pb.RegisterServer.getDefaultInstance();
        }
        registerServerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cloud.spawnery.agent.pb.RegisterServer, cloud.spawnery.agent.pb.RegisterServer.Builder, cloud.spawnery.agent.pb.RegisterServerOrBuilder>(
                (cloud.spawnery.agent.pb.RegisterServer) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 2;
      onChanged();
      return registerServerBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.UnregisterServer, cloud.spawnery.agent.pb.UnregisterServer.Builder, cloud.spawnery.agent.pb.UnregisterServerOrBuilder> unregisterServerBuilder_;
    /**
     * <code>.spawnery.agent.v1alpha1.UnregisterServer unregister_server = 3;</code>
     * @return Whether the unregisterServer field is set.
     */
    @java.lang.Override
    public boolean hasUnregisterServer() {
      return messageCase_ == 3;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.UnregisterServer unregister_server = 3;</code>
     * @return The unregisterServer.
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.UnregisterServer getUnregisterServer() {
      if (unregisterServerBuilder_ == null) {
        if (messageCase_ == 3) {
          return (cloud.spawnery.agent.pb.UnregisterServer) message_;
        }
        return cloud.spawnery.agent.pb.UnregisterServer.getDefaultInstance();
      } else {
        if (messageCase_ == 3) {
          return unregisterServerBuilder_.getMessage();
        }
        return cloud.spawnery.agent.pb.UnregisterServer.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.UnregisterServer unregister_server = 3;</code>
     */
    public Builder setUnregisterServer(cloud.spawnery.agent.pb.UnregisterServer value) {
      if (unregisterServerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        unregisterServerBuilder_.setMessage(value);
      }
      messageCase_ = 3;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.UnregisterServer unregister_server = 3;</code>
     */
    public Builder setUnregisterServer(
        cloud.spawnery.agent.pb.UnregisterServer.Builder builderForValue) {
      if (unregisterServerBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        unregisterServerBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 3;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.UnregisterServer unregister_server = 3;</code>
     */
    public Builder mergeUnregisterServer(cloud.spawnery.agent.pb.UnregisterServer value) {
      if (unregisterServerBuilder_ == null) {
        if (messageCase_ == 3 &&
            message_ != cloud.spawnery.agent.pb.UnregisterServer.getDefaultInstance()) {
          message_ = cloud.spawnery.agent.pb.UnregisterServer.newBuilder((cloud.spawnery.agent.pb.UnregisterServer) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 3) {
          unregisterServerBuilder_.mergeFrom(value);
        } else {
          unregisterServerBuilder_.setMessage(value);
        }
      }
      messageCase_ = 3;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.UnregisterServer unregister_server = 3;</code>
     */
    public Builder clearUnregisterServer() {
      if (unregisterServerBuilder_ == null) {
        if (messageCase_ == 3) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 3) {
          messageCase_ = 0;
          message_ = null;
        }
        unregisterServerBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.UnregisterServer unregister_server = 3;</code>
     */
    public cloud.spawnery.agent.pb.UnregisterServer.Builder getUnregisterServerBuilder() {
      return internalGetUnregisterServerFieldBuilder().getBuilder();
    }
    /**
     * <code>.spawnery.agent.v1alpha1.UnregisterServer unregister_server = 3;</code>
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.UnregisterServerOrBuilder getUnregisterServerOrBuilder() {
      if ((messageCase_ == 3) && (unregisterServerBuilder_ != null)) {
        return unregisterServerBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 3) {
          return (cloud.spawnery.agent.pb.UnregisterServer) message_;
        }
        return cloud.spawnery.agent.pb.UnregisterServer.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.UnregisterServer unregister_server = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.UnregisterServer, cloud.spawnery.agent.pb.UnregisterServer.Builder, cloud.spawnery.agent.pb.UnregisterServerOrBuilder> 
        internalGetUnregisterServerFieldBuilder() {
      if (unregisterServerBuilder_ == null) {
        if (!(messageCase_ == 3)) {
          message_ = cloud.spawnery.agent.pb.UnregisterServer.getDefaultInstance();
        }
        unregisterServerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cloud.spawnery.agent.pb.UnregisterServer, cloud.spawnery.agent.pb.UnregisterServer.Builder, cloud.spawnery.agent.pb.UnregisterServerOrBuilder>(
                (cloud.spawnery.agent.pb.UnregisterServer) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 3;
      onChanged();
      return unregisterServerBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.DrainPlayers, cloud.spawnery.agent.pb.DrainPlayers.Builder, cloud.spawnery.agent.pb.DrainPlayersOrBuilder> drainPlayersBuilder_;
    /**
     * <code>.spawnery.agent.v1alpha1.DrainPlayers drain_players = 4;</code>
     * @return Whether the drainPlayers field is set.
     */
    @java.lang.Override
    public boolean hasDrainPlayers() {
      return messageCase_ == 4;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.DrainPlayers drain_players = 4;</code>
     * @return The drainPlayers.
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.DrainPlayers getDrainPlayers() {
      if (drainPlayersBuilder_ == null) {
        if (messageCase_ == 4) {
          return (cloud.spawnery.agent.pb.DrainPlayers) message_;
        }
        return cloud.spawnery.agent.pb.DrainPlayers.getDefaultInstance();
      } else {
        if (messageCase_ == 4) {
          return drainPlayersBuilder_.getMessage();
        }
        return cloud.spawnery.agent.pb.DrainPlayers.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.DrainPlayers drain_players = 4;</code>
     */
    public Builder setDrainPlayers(cloud.spawnery.agent.pb.DrainPlayers value) {
      if (drainPlayersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        drainPlayersBuilder_.setMessage(value);
      }
      messageCase_ = 4;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.DrainPlayers drain_players = 4;</code>
     */
    public Builder setDrainPlayers(
        cloud.spawnery.agent.pb.DrainPlayers.Builder builderForValue) {
      if (drainPlayersBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        drainPlayersBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 4;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.DrainPlayers drain_players = 4;</code>
     */
    public Builder mergeDrainPlayers(cloud.spawnery.agent.pb.DrainPlayers value) {
      if (drainPlayersBuilder_ == null) {
        if (messageCase_ == 4 &&
            message_ != cloud.spawnery.agent.pb.DrainPlayers.getDefaultInstance()) {
          message_ = cloud.spawnery.agent.pb.DrainPlayers.newBuilder((cloud.spawnery.agent.pb.DrainPlayers) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 4) {
          drainPlayersBuilder_.mergeFrom(value);
        } else {
          drainPlayersBuilder_.setMessage(value);
        }
      }
      messageCase_ = 4;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.DrainPlayers drain_players = 4;</code>
     */
    public Builder clearDrainPlayers() {
      if (drainPlayersBuilder_ == null) {
        if (messageCase_ == 4) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 4) {
          messageCase_ = 0;
          message_ = null;
        }
        drainPlayersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.DrainPlayers drain_players = 4;</code>
     */
    public cloud.spawnery.agent.pb.DrainPlayers.Builder getDrainPlayersBuilder() {
      return internalGetDrainPlayersFieldBuilder().getBuilder();
    }
    /**
     * <code>.spawnery.agent.v1alpha1.DrainPlayers drain_players = 4;</code>
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.DrainPlayersOrBuilder getDrainPlayersOrBuilder() {
      if ((messageCase_ == 4) && (drainPlayersBuilder_ != null)) {
        return drainPlayersBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 4) {
          return (cloud.spawnery.agent.pb.DrainPlayers) message_;
        }
        return cloud.spawnery.agent.pb.DrainPlayers.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.DrainPlayers drain_players = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.DrainPlayers, cloud.spawnery.agent.pb.DrainPlayers.Builder, cloud.spawnery.agent.pb.DrainPlayersOrBuilder> 
        internalGetDrainPlayersFieldBuilder() {
      if (drainPlayersBuilder_ == null) {
        if (!(messageCase_ == 4)) {
          message_ = cloud.spawnery.agent.pb.DrainPlayers.getDefaultInstance();
        }
        drainPlayersBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cloud.spawnery.agent.pb.DrainPlayers, cloud.spawnery.agent.pb.DrainPlayers.Builder, cloud.spawnery.agent.pb.DrainPlayersOrBuilder>(
                (cloud.spawnery.agent.pb.DrainPlayers) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 4;
      onChanged();
      return drainPlayersBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.ReportInterval, cloud.spawnery.agent.pb.ReportInterval.Builder, cloud.spawnery.agent.pb.ReportIntervalOrBuilder> reportIntervalBuilder_;
    /**
     * <code>.spawnery.agent.v1alpha1.ReportInterval report_interval = 5;</code>
     * @return Whether the reportInterval field is set.
     */
    @java.lang.Override
    public boolean hasReportInterval() {
      return messageCase_ == 5;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ReportInterval report_interval = 5;</code>
     * @return The reportInterval.
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.ReportInterval getReportInterval() {
      if (reportIntervalBuilder_ == null) {
        if (messageCase_ == 5) {
          return (cloud.spawnery.agent.pb.ReportInterval) message_;
        }
        return cloud.spawnery.agent.pb.ReportInterval.getDefaultInstance();
      } else {
        if (messageCase_ == 5) {
          return reportIntervalBuilder_.getMessage();
        }
        return cloud.spawnery.agent.pb.ReportInterval.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ReportInterval report_interval = 5;</code>
     */
    public Builder setReportInterval(cloud.spawnery.agent.pb.ReportInterval value) {
      if (reportIntervalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        reportIntervalBuilder_.setMessage(value);
      }
      messageCase_ = 5;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ReportInterval report_interval = 5;</code>
     */
    public Builder setReportInterval(
        cloud.spawnery.agent.pb.ReportInterval.Builder builderForValue) {
      if (reportIntervalBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        reportIntervalBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 5;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ReportInterval report_interval = 5;</code>
     */
    public Builder mergeReportInterval(cloud.spawnery.agent.pb.ReportInterval value) {
      if (reportIntervalBuilder_ == null) {
        if (messageCase_ == 5 &&
            message_ != cloud.spawnery.agent.pb.ReportInterval.getDefaultInstance()) {
          message_ = cloud.spawnery.agent.pb.ReportInterval.newBuilder((cloud.spawnery.agent.pb.ReportInterval) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 5) {
          reportIntervalBuilder_.mergeFrom(value);
        } else {
          reportIntervalBuilder_.setMessage(value);
        }
      }
      messageCase_ = 5;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ReportInterval report_interval = 5;</code>
     */
    public Builder clearReportInterval() {
      if (reportIntervalBuilder_ == null) {
        if (messageCase_ == 5) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 5) {
          messageCase_ = 0;
          message_ = null;
        }
        reportIntervalBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ReportInterval report_interval = 5;</code>
     */
    public cloud.spawnery.agent.pb.ReportInterval.Builder getReportIntervalBuilder() {
      return internalGetReportIntervalFieldBuilder().getBuilder();
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ReportInterval report_interval = 5;</code>
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.ReportIntervalOrBuilder getReportIntervalOrBuilder() {
      if ((messageCase_ == 5) && (reportIntervalBuilder_ != null)) {
        return reportIntervalBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 5) {
          return (cloud.spawnery.agent.pb.ReportInterval) message_;
        }
        return cloud.spawnery.agent.pb.ReportInterval.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ReportInterval report_interval = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.ReportInterval, cloud.spawnery.agent.pb.ReportInterval.Builder, cloud.spawnery.agent.pb.ReportIntervalOrBuilder> 
        internalGetReportIntervalFieldBuilder() {
      if (reportIntervalBuilder_ == null) {
        if (!(messageCase_ == 5)) {
          message_ = cloud.spawnery.agent.pb.ReportInterval.getDefaultInstance();
        }
        reportIntervalBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cloud.spawnery.agent.pb.ReportInterval, cloud.spawnery.agent.pb.ReportInterval.Builder, cloud.spawnery.agent.pb.ReportIntervalOrBuilder>(
                (cloud.spawnery.agent.pb.ReportInterval) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 5;
      onChanged();
      return reportIntervalBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.SessionDeadline, cloud.spawnery.agent.pb.SessionDeadline.Builder, cloud.spawnery.agent.pb.SessionDeadlineOrBuilder> sessionDeadlineBuilder_;
    /**
     * <code>.spawnery.agent.v1alpha1.SessionDeadline session_deadline = 6;</code>
     * @return Whether the sessionDeadline field is set.
     */
    @java.lang.Override
    public boolean hasSessionDeadline() {
      return messageCase_ == 6;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.SessionDeadline session_deadline = 6;</code>
     * @return The sessionDeadline.
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.SessionDeadline getSessionDeadline() {
      if (sessionDeadlineBuilder_ == null) {
        if (messageCase_ == 6) {
          return (cloud.spawnery.agent.pb.SessionDeadline) message_;
        }
        return cloud.spawnery.agent.pb.SessionDeadline.getDefaultInstance();
      } else {
        if (messageCase_ == 6) {
          return sessionDeadlineBuilder_.getMessage();
        }
        return cloud.spawnery.agent.pb.SessionDeadline.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.SessionDeadline session_deadline = 6;</code>
     */
    public Builder setSessionDeadline(cloud.spawnery.agent.pb.SessionDeadline value) {
      if (sessionDeadlineBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        sessionDeadlineBuilder_.setMessage(value);
      }
      messageCase_ = 6;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.SessionDeadline session_deadline = 6;</code>
     */
    public Builder setSessionDeadline(
        cloud.spawnery.agent.pb.SessionDeadline.Builder builderForValue) {
      if (sessionDeadlineBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        sessionDeadlineBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 6;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.SessionDeadline session_deadline = 6;</code>
     */
    public Builder mergeSessionDeadline(cloud.spawnery.agent.pb.SessionDeadline value) {
      if (sessionDeadlineBuilder_ == null) {
        if (messageCase_ == 6 &&
            message_ != cloud.spawnery.agent.pb.SessionDeadline.getDefaultInstance()) {
          message_ = cloud.spawnery.agent.pb.SessionDeadline.newBuilder((cloud.spawnery.agent.pb.SessionDeadline) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 6) {
          sessionDeadlineBuilder_.mergeFrom(value);
        } else {
          sessionDeadlineBuilder_.setMessage(value);
        }
      }
      messageCase_ = 6;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.SessionDeadline session_deadline = 6;</code>
     */
    public Builder clearSessionDeadline() {
      if (sessionDeadlineBuilder_ == null) {
        if (messageCase_ == 6) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 6) {
          messageCase_ = 0;
          message_ = null;
        }
        sessionDeadlineBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.SessionDeadline session_deadline = 6;</code>
     */
    public cloud.spawnery.agent.pb.SessionDeadline.Builder getSessionDeadlineBuilder() {
      return internalGetSessionDeadlineFieldBuilder().getBuilder();
    }
    /**
     * <code>.spawnery.agent.v1alpha1.SessionDeadline session_deadline = 6;</code>
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.SessionDeadlineOrBuilder getSessionDeadlineOrBuilder() {
      if ((messageCase_ == 6) && (sessionDeadlineBuilder_ != null)) {
        return sessionDeadlineBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 6) {
          return (cloud.spawnery.agent.pb.SessionDeadline) message_;
        }
        return cloud.spawnery.agent.pb.SessionDeadline.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.SessionDeadline session_deadline = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.SessionDeadline, cloud.spawnery.agent.pb.SessionDeadline.Builder, cloud.spawnery.agent.pb.SessionDeadlineOrBuilder> 
        internalGetSessionDeadlineFieldBuilder() {
      if (sessionDeadlineBuilder_ == null) {
        if (!(messageCase_ == 6)) {
          message_ = cloud.spawnery.agent.pb.SessionDeadline.getDefaultInstance();
        }
        sessionDeadlineBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cloud.spawnery.agent.pb.SessionDeadline, cloud.spawnery.agent.pb.SessionDeadline.Builder, cloud.spawnery.agent.pb.SessionDeadlineOrBuilder>(
                (cloud.spawnery.agent.pb.SessionDeadline) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 6;
      onChanged();
      return sessionDeadlineBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.SetReady, cloud.spawnery.agent.pb.SetReady.Builder, cloud.spawnery.agent.pb.SetReadyOrBuilder> setReadyBuilder_;
    /**
     * <code>.spawnery.agent.v1alpha1.SetReady set_ready = 7;</code>
     * @return Whether the setReady field is set.
     */
    @java.lang.Override
    public boolean hasSetReady() {
      return messageCase_ == 7;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.SetReady set_ready = 7;</code>
     * @return The setReady.
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.SetReady getSetReady() {
      if (setReadyBuilder_ == null) {
        if (messageCase_ == 7) {
          return (cloud.spawnery.agent.pb.SetReady) message_;
        }
        return cloud.spawnery.agent.pb.SetReady.getDefaultInstance();
      } else {
        if (messageCase_ == 7) {
          return setReadyBuilder_.getMessage();
        }
        return cloud.spawnery.agent.pb.SetReady.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.SetReady set_ready = 7;</code>
     */
    public Builder setSetReady(cloud.spawnery.agent.pb.SetReady value) {
      if (setReadyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        setReadyBuilder_.setMessage(value);
      }
      messageCase_ = 7;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.SetReady set_ready = 7;</code>
     */
    public Builder setSetReady(
        cloud.spawnery.agent.pb.SetReady.Builder builderForValue) {
      if (setReadyBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        setReadyBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 7;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.SetReady set_ready = 7;</code>
     */
    public Builder mergeSetReady(cloud.spawnery.agent.pb.SetReady value) {
      if (setReadyBuilder_ == null) {
        if (messageCase_ == 7 &&
            message_ != cloud.spawnery.agent.pb.SetReady.getDefaultInstance()) {
          message_ = cloud.spawnery.agent.pb.SetReady.newBuilder((cloud.spawnery.agent.pb.SetReady) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 7) {
          setReadyBuilder_.mergeFrom(value);
        } else {
          setReadyBuilder_.setMessage(value);
        }
      }
      messageCase_ = 7;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.SetReady set_ready = 7;</code>
     */
    public Builder clearSetReady() {
      if (setReadyBuilder_ == null) {
        if (messageCase_ == 7) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 7) {
          messageCase_ = 0;
          message_ = null;
        }
        setReadyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.SetReady set_ready = 7;</code>
     */
    public cloud.spawnery.agent.pb.SetReady.Builder getSetReadyBuilder() {
      return internalGetSetReadyFieldBuilder().getBuilder();
    }
    /**
     * <code>.spawnery.agent.v1alpha1.SetReady set_ready = 7;</code>
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.SetReadyOrBuilder getSetReadyOrBuilder() {
      if ((messageCase_ == 7) && (setReadyBuilder_ != null)) {
        return setReadyBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 7) {
          return (cloud.spawnery.agent.pb.SetReady) message_;
        }
        return cloud.spawnery.agent.pb.SetReady.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.SetReady set_ready = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.SetReady, cloud.spawnery.agent.pb.SetReady.Builder, cloud.spawnery.agent.pb.SetReadyOrBuilder> 
        internalGetSetReadyFieldBuilder() {
      if (setReadyBuilder_ == null) {
        if (!(messageCase_ == 7)) {
          message_ = cloud.spawnery.agent.pb.SetReady.getDefaultInstance();
        }
        setReadyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cloud.spawnery.agent.pb.SetReady, cloud.spawnery.agent.pb.SetReady.Builder, cloud.spawnery.agent.pb.SetReadyOrBuilder>(
                (cloud.spawnery.agent.pb.SetReady) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 7;
      onChanged();
      return setReadyBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.NetworkState, cloud.spawnery.agent.pb.NetworkState.Builder, cloud.spawnery.agent.pb.NetworkStateOrBuilder> networkStateBuilder_;
    /**
     * <code>.spawnery.agent.v1alpha1.NetworkState network_state = 8;</code>
     * @return Whether the networkState field is set.
     */
    @java.lang.Override
    public boolean hasNetworkState() {
      return messageCase_ == 8;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.NetworkState network_state = 8;</code>
     * @return The networkState.
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.NetworkState getNetworkState() {
      if (networkStateBuilder_ == null) {
        if (messageCase_ == 8) {
          return (cloud.spawnery.agent.pb.NetworkState) message_;
        }
        return cloud.spawnery.agent.pb.NetworkState.getDefaultInstance();
      } else {
        if (messageCase_ == 8) {
          return networkStateBuilder_.getMessage();
        }
        return cloud.spawnery.agent.pb.NetworkState.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.NetworkState network_state = 8;</code>
     */
    public Builder setNetworkState(cloud.spawnery.agent.pb.NetworkState value) {
      if (networkStateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        networkStateBuilder_.setMessage(value);
      }
      messageCase_ = 8;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.NetworkState network_state = 8;</code>
     */
    public Builder setNetworkState(
        cloud.spawnery.agent.pb.NetworkState.Builder builderForValue) {
      if (networkStateBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        networkStateBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 8;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.NetworkState network_state = 8;</code>
     */
    public Builder mergeNetworkState(cloud.spawnery.agent.pb.NetworkState value) {
      if (networkStateBuilder_ == null) {
        if (messageCase_ == 8 &&
            message_ != cloud.spawnery.agent.pb.NetworkState.getDefaultInstance()) {
          message_ = cloud.spawnery.agent.pb.NetworkState.newBuilder((cloud.spawnery.agent.pb.NetworkState) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 8) {
          networkStateBuilder_.mergeFrom(value);
        } else {
          networkStateBuilder_.setMessage(value);
        }
      }
      messageCase_ = 8;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.NetworkState network_state = 8;</code>
     */
    public Builder clearNetworkState() {
      if (networkStateBuilder_ == null) {
        if (messageCase_ == 8) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 8) {
          messageCase_ = 0;
          message_ = null;
        }
        networkStateBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.NetworkState network_state = 8;</code>
     */
    public cloud.spawnery.agent.pb.NetworkState.Builder getNetworkStateBuilder() {
      return internalGetNetworkStateFieldBuilder().getBuilder();
    }
    /**
     * <code>.spawnery.agent.v1alpha1.NetworkState network_state = 8;</code>
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.NetworkStateOrBuilder getNetworkStateOrBuilder() {
      if ((messageCase_ == 8) && (networkStateBuilder_ != null)) {
        return networkStateBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 8) {
          return (cloud.spawnery.agent.pb.NetworkState) message_;
        }
        return cloud.spawnery.agent.pb.NetworkState.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.NetworkState network_state = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.NetworkState, cloud.spawnery.agent.pb.NetworkState.Builder, cloud.spawnery.agent.pb.NetworkStateOrBuilder> 
        internalGetNetworkStateFieldBuilder() {
      if (networkStateBuilder_ == null) {
        if (!(messageCase_ == 8)) {
          message_ = cloud.spawnery.agent.pb.NetworkState.getDefaultInstance();
        }
        networkStateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cloud.spawnery.agent.pb.NetworkState, cloud.spawnery.agent.pb.NetworkState.Builder, cloud.spawnery.agent.pb.NetworkStateOrBuilder>(
                (cloud.spawnery.agent.pb.NetworkState) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 8;
      onChanged();
      return networkStateBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.CloudResponse, cloud.spawnery.agent.pb.CloudResponse.Builder, cloud.spawnery.agent.pb.CloudResponseOrBuilder> cloudResponseBuilder_;
    /**
     * <code>.spawnery.agent.v1alpha1.CloudResponse cloud_response = 9;</code>
     * @return Whether the cloudResponse field is set.
     */
    @java.lang.Override
    public boolean hasCloudResponse() {
      return messageCase_ == 9;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.CloudResponse cloud_response = 9;</code>
     * @return The cloudResponse.
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.CloudResponse getCloudResponse() {
      if (cloudResponseBuilder_ == null) {
        if (messageCase_ == 9) {
          return (cloud.spawnery.agent.pb.CloudResponse) message_;
        }
        return cloud.spawnery.agent.pb.CloudResponse.getDefaultInstance();
      } else {
        if (messageCase_ == 9) {
          return cloudResponseBuilder_.getMessage();
        }
        return cloud.spawnery.agent.pb.CloudResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.CloudResponse cloud_response = 9;</code>
     */
    public Builder setCloudResponse(cloud.spawnery.agent.pb.CloudResponse value) {
      if (cloudResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        cloudResponseBuilder_.setMessage(value);
      }
      messageCase_ = 9;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.CloudResponse cloud_response = 9;</code>
     */
    public Builder setCloudResponse(
        cloud.spawnery.agent.pb.CloudResponse.Builder builderForValue) {
      if (cloudResponseBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        cloudResponseBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 9;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.CloudResponse cloud_response = 9;</code>
     */
    public Builder mergeCloudResponse(cloud.spawnery.agent.pb.CloudResponse value) {
      if (cloudResponseBuilder_ == null) {
        if (messageCase_ == 9 &&
            message_ != cloud.spawnery.agent.pb.CloudResponse.getDefaultInstance()) {
          message_ = cloud.spawnery.agent.pb.CloudResponse.newBuilder((cloud.spawnery.agent.pb.CloudResponse) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 9) {
          cloudResponseBuilder_.mergeFrom(value);
        } else {
          cloudResponseBuilder_.setMessage(value);
        }
      }
      messageCase_ = 9;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.CloudResponse cloud_response = 9;</code>
     */
    public Builder clearCloudResponse() {
      if (cloudResponseBuilder_ == null) {
        if (messageCase_ == 9) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 9) {
          messageCase_ = 0;
          message_ = null;
        }
        cloudResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.CloudResponse cloud_response = 9;</code>
     */
    public cloud.spawnery.agent.pb.CloudResponse.Builder getCloudResponseBuilder() {
      return internalGetCloudResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.spawnery.agent.v1alpha1.CloudResponse cloud_response = 9;</code>
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.CloudResponseOrBuilder getCloudResponseOrBuilder() {
      if ((messageCase_ == 9) && (cloudResponseBuilder_ != null)) {
        return cloudResponseBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 9) {
          return (cloud.spawnery.agent.pb.CloudResponse) message_;
        }
        return cloud.spawnery.agent.pb.CloudResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.CloudResponse cloud_response = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.CloudResponse, cloud.spawnery.agent.pb.CloudResponse.Builder, cloud.spawnery.agent.pb.CloudResponseOrBuilder> 
        internalGetCloudResponseFieldBuilder() {
      if (cloudResponseBuilder_ == null) {
        if (!(messageCase_ == 9)) {
          message_ = cloud.spawnery.agent.pb.CloudResponse.getDefaultInstance();
        }
        cloudResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cloud.spawnery.agent.pb.CloudResponse, cloud.spawnery.agent.pb.CloudResponse.Builder, cloud.spawnery.agent.pb.CloudResponseOrBuilder>(
                (cloud.spawnery.agent.pb.CloudResponse) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 9;
      onChanged();
      return cloudResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.MovePlayer, cloud.spawnery.agent.pb.MovePlayer.Builder, cloud.spawnery.agent.pb.MovePlayerOrBuilder> movePlayerBuilder_;
    /**
     * <code>.spawnery.agent.v1alpha1.MovePlayer move_player = 10;</code>
     * @return Whether the movePlayer field is set.
     */
    @java.lang.Override
    public boolean hasMovePlayer() {
      return messageCase_ == 10;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.MovePlayer move_player = 10;</code>
     * @return The movePlayer.
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.MovePlayer getMovePlayer() {
      if (movePlayerBuilder_ == null) {
        if (messageCase_ == 10) {
          return (cloud.spawnery.agent.pb.MovePlayer) message_;
        }
        return cloud.spawnery.agent.pb.MovePlayer.getDefaultInstance();
      } else {
        if (messageCase_ == 10) {
          return movePlayerBuilder_.getMessage();
        }
        return cloud.spawnery.agent.pb.MovePlayer.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.MovePlayer move_player = 10;</code>
     */
    public Builder setMovePlayer(cloud.spawnery.agent.pb.MovePlayer value) {
      if (movePlayerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        movePlayerBuilder_.setMessage(value);
      }
      messageCase_ = 10;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.MovePlayer move_player = 10;</code>
     */
    public Builder setMovePlayer(
        cloud.spawnery.agent.pb.MovePlayer.Builder builderForValue) {
      if (movePlayerBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        movePlayerBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 10;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.MovePlayer move_player = 10;</code>
     */
    public Builder mergeMovePlayer(cloud.spawnery.agent.pb.MovePlayer value) {
      if (movePlayerBuilder_ == null) {
        if (messageCase_ == 10 &&
            message_ != cloud.spawnery.agent.pb.MovePlayer.getDefaultInstance()) {
          message_ = cloud.spawnery.agent.pb.MovePlayer.newBuilder((cloud.spawnery.agent.pb.MovePlayer) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 10) {
          movePlayerBuilder_.mergeFrom(value);
        } else {
          movePlayerBuilder_.setMessage(value);
        }
      }
      messageCase_ = 10;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.MovePlayer move_player = 10;</code>
     */
    public Builder clearMovePlayer() {
      if (movePlayerBuilder_ == null) {
        if (messageCase_ == 10) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 10) {
          messageCase_ = 0;
          message_ = null;
        }
        movePlayerBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.MovePlayer move_player = 10;</code>
     */
    public cloud.spawnery.agent.pb.MovePlayer.Builder getMovePlayerBuilder() {
      return internalGetMovePlayerFieldBuilder().getBuilder();
    }
    /**
     * <code>.spawnery.agent.v1alpha1.MovePlayer move_player = 10;</code>
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.MovePlayerOrBuilder getMovePlayerOrBuilder() {
      if ((messageCase_ == 10) && (movePlayerBuilder_ != null)) {
        return movePlayerBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 10) {
          return (cloud.spawnery.agent.pb.MovePlayer) message_;
        }
        return cloud.spawnery.agent.pb.MovePlayer.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.MovePlayer move_player = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.MovePlayer, cloud.spawnery.agent.pb.MovePlayer.Builder, cloud.spawnery.agent.pb.MovePlayerOrBuilder> 
        internalGetMovePlayerFieldBuilder() {
      if (movePlayerBuilder_ == null) {
        if (!(messageCase_ == 10)) {
          message_ = cloud.spawnery.agent.pb.MovePlayer.getDefaultInstance();
        }
        movePlayerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cloud.spawnery.agent.pb.MovePlayer, cloud.spawnery.agent.pb.MovePlayer.Builder, cloud.spawnery.agent.pb.MovePlayerOrBuilder>(
                (cloud.spawnery.agent.pb.MovePlayer) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 10;
      onChanged();
      return movePlayerBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:spawnery.agent.v1alpha1.OperatorToProxy)
  }

  // @@protoc_insertion_point(class_scope:spawnery.agent.v1alpha1.OperatorToProxy)
  private static final cloud.spawnery.agent.pb.OperatorToProxy DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.spawnery.agent.pb.OperatorToProxy();
  }

  public static cloud.spawnery.agent.pb.OperatorToProxy getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OperatorToProxy>
      PARSER = new com.google.protobuf.AbstractParser<OperatorToProxy>() {
    @java.lang.Override
    public OperatorToProxy parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<OperatorToProxy> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OperatorToProxy> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.spawnery.agent.pb.OperatorToProxy getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

