// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface OperatorToProxyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.OperatorToProxy)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.spawnery.agent.v1alpha1.FullSync full_sync = 1;</code>
   * @return Whether the fullSync field is set.
   */
  boolean hasFullSync();
  /**
   * <code>.spawnery.agent.v1alpha1.FullSync full_sync = 1;</code>
   * @return The fullSync.
   */
  cloud.spawnery.agent.pb.FullSync getFullSync();
  /**
   * <code>.spawnery.agent.v1alpha1.FullSync full_sync = 1;</code>
   */
  cloud.spawnery.agent.pb.FullSyncOrBuilder getFullSyncOrBuilder();

  /**
   * <code>.spawnery.agent.v1alpha1.RegisterServer register_server = 2;</code>
   * @return Whether the registerServer field is set.
   */
  boolean hasRegisterServer();
  /**
   * <code>.spawnery.agent.v1alpha1.RegisterServer register_server = 2;</code>
   * @return The registerServer.
   */
  cloud.spawnery.agent.pb.RegisterServer getRegisterServer();
  /**
   * <code>.spawnery.agent.v1alpha1.RegisterServer register_server = 2;</code>
   */
  cloud.spawnery.agent.pb.RegisterServerOrBuilder getRegisterServerOrBuilder();

  /**
   * <code>.spawnery.agent.v1alpha1.UnregisterServer unregister_server = 3;</code>
   * @return Whether the unregisterServer field is set.
   */
  boolean hasUnregisterServer();
  /**
   * <code>.spawnery.agent.v1alpha1.UnregisterServer unregister_server = 3;</code>
   * @return The unregisterServer.
   */
  cloud.spawnery.agent.pb.UnregisterServer getUnregisterServer();
  /**
   * <code>.spawnery.agent.v1alpha1.UnregisterServer unregister_server = 3;</code>
   */
  cloud.spawnery.agent.pb.UnregisterServerOrBuilder getUnregisterServerOrBuilder();

  /**
   * <code>.spawnery.agent.v1alpha1.DrainPlayers drain_players = 4;</code>
   * @return Whether the drainPlayers field is set.
   */
  boolean hasDrainPlayers();
  /**
   * <code>.spawnery.agent.v1alpha1.DrainPlayers drain_players = 4;</code>
   * @return The drainPlayers.
   */
  cloud.spawnery.agent.pb.DrainPlayers getDrainPlayers();
  /**
   * <code>.spawnery.agent.v1alpha1.DrainPlayers drain_players = 4;</code>
   */
  cloud.spawnery.agent.pb.DrainPlayersOrBuilder getDrainPlayersOrBuilder();

  /**
   * <code>.spawnery.agent.v1alpha1.ReportInterval report_interval = 5;</code>
   * @return Whether the reportInterval field is set.
   */
  boolean hasReportInterval();
  /**
   * <code>.spawnery.agent.v1alpha1.ReportInterval report_interval = 5;</code>
   * @return The reportInterval.
   */
  cloud.spawnery.agent.pb.ReportInterval getReportInterval();
  /**
   * <code>.spawnery.agent.v1alpha1.ReportInterval report_interval = 5;</code>
   */
  cloud.spawnery.agent.pb.ReportIntervalOrBuilder getReportIntervalOrBuilder();

  /**
   * <code>.spawnery.agent.v1alpha1.SessionDeadline session_deadline = 6;</code>
   * @return Whether the sessionDeadline field is set.
   */
  boolean hasSessionDeadline();
  /**
   * <code>.spawnery.agent.v1alpha1.SessionDeadline session_deadline = 6;</code>
   * @return The sessionDeadline.
   */
  cloud.spawnery.agent.pb.SessionDeadline getSessionDeadline();
  /**
   * <code>.spawnery.agent.v1alpha1.SessionDeadline session_deadline = 6;</code>
   */
  cloud.spawnery.agent.pb.SessionDeadlineOrBuilder getSessionDeadlineOrBuilder();

  cloud.spawnery.agent.pb.OperatorToProxy.MessageCase getMessageCase();
}
