// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface OperatorToServerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.OperatorToServer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.spawnery.agent.v1alpha1.ReportInterval report_interval = 1;</code>
   * @return Whether the reportInterval field is set.
   */
  boolean hasReportInterval();
  /**
   * <code>.spawnery.agent.v1alpha1.ReportInterval report_interval = 1;</code>
   * @return The reportInterval.
   */
  cloud.spawnery.agent.pb.ReportInterval getReportInterval();
  /**
   * <code>.spawnery.agent.v1alpha1.ReportInterval report_interval = 1;</code>
   */
  cloud.spawnery.agent.pb.ReportIntervalOrBuilder getReportIntervalOrBuilder();

  /**
   * <code>.spawnery.agent.v1alpha1.SessionDeadline session_deadline = 2;</code>
   * @return Whether the sessionDeadline field is set.
   */
  boolean hasSessionDeadline();
  /**
   * <code>.spawnery.agent.v1alpha1.SessionDeadline session_deadline = 2;</code>
   * @return The sessionDeadline.
   */
  cloud.spawnery.agent.pb.SessionDeadline getSessionDeadline();
  /**
   * <code>.spawnery.agent.v1alpha1.SessionDeadline session_deadline = 2;</code>
   */
  cloud.spawnery.agent.pb.SessionDeadlineOrBuilder getSessionDeadlineOrBuilder();

  /**
   * <code>.spawnery.agent.v1alpha1.NetworkState network_state = 3;</code>
   * @return Whether the networkState field is set.
   */
  boolean hasNetworkState();
  /**
   * <code>.spawnery.agent.v1alpha1.NetworkState network_state = 3;</code>
   * @return The networkState.
   */
  cloud.spawnery.agent.pb.NetworkState getNetworkState();
  /**
   * <code>.spawnery.agent.v1alpha1.NetworkState network_state = 3;</code>
   */
  cloud.spawnery.agent.pb.NetworkStateOrBuilder getNetworkStateOrBuilder();

  /**
   * <code>.spawnery.agent.v1alpha1.CloudResponse cloud_response = 4;</code>
   * @return Whether the cloudResponse field is set.
   */
  boolean hasCloudResponse();
  /**
   * <code>.spawnery.agent.v1alpha1.CloudResponse cloud_response = 4;</code>
   * @return The cloudResponse.
   */
  cloud.spawnery.agent.pb.CloudResponse getCloudResponse();
  /**
   * <code>.spawnery.agent.v1alpha1.CloudResponse cloud_response = 4;</code>
   */
  cloud.spawnery.agent.pb.CloudResponseOrBuilder getCloudResponseOrBuilder();

  /**
   * <code>.spawnery.agent.v1alpha1.CloudEvent cloud_event = 5;</code>
   * @return Whether the cloudEvent field is set.
   */
  boolean hasCloudEvent();
  /**
   * <code>.spawnery.agent.v1alpha1.CloudEvent cloud_event = 5;</code>
   * @return The cloudEvent.
   */
  cloud.spawnery.agent.pb.CloudEvent getCloudEvent();
  /**
   * <code>.spawnery.agent.v1alpha1.CloudEvent cloud_event = 5;</code>
   */
  cloud.spawnery.agent.pb.CloudEventOrBuilder getCloudEventOrBuilder();

  cloud.spawnery.agent.pb.OperatorToServer.MessageCase getMessageCase();
}
