// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface OperatorToServerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.OperatorToServer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.spawnery.agent.v1alpha1.ReportInterval report_interval = 1;</code>
   * @return Whether the reportInterval field is set.
   */
  boolean hasReportInterval();
  /**
   * <code>.spawnery.agent.v1alpha1.ReportInterval report_interval = 1;</code>
   * @return The reportInterval.
   */
  cloud.spawnery.agent.pb.ReportInterval getReportInterval();
  /**
   * <code>.spawnery.agent.v1alpha1.ReportInterval report_interval = 1;</code>
   */
  cloud.spawnery.agent.pb.ReportIntervalOrBuilder getReportIntervalOrBuilder();

  /**
   * <code>.spawnery.agent.v1alpha1.SessionDeadline session_deadline = 2;</code>
   * @return Whether the sessionDeadline field is set.
   */
  boolean hasSessionDeadline();
  /**
   * <code>.spawnery.agent.v1alpha1.SessionDeadline session_deadline = 2;</code>
   * @return The sessionDeadline.
   */
  cloud.spawnery.agent.pb.SessionDeadline getSessionDeadline();
  /**
   * <code>.spawnery.agent.v1alpha1.SessionDeadline session_deadline = 2;</code>
   */
  cloud.spawnery.agent.pb.SessionDeadlineOrBuilder getSessionDeadlineOrBuilder();

  cloud.spawnery.agent.pb.OperatorToServer.MessageCase getMessageCase();
}
