// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface PlayerCountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.PlayerCount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 players = 1;</code>
   * @return The players.
   */
  int getPlayers();

  /**
   * <code>int32 slots = 2;</code>
   * @return The slots.
   */
  int getSlots();
}
