// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

/**
 * <pre>
 * PlayerRoster is who this proxy is serving, by identity.
 *
 * It exists because the operator had no source for one. PlayerJoinedServer
 * carries a username and is accepted and ignored; PlayerCount and
 * BackendPlayers are counts. So the operator could say how many people were on
 * a backend and never who, and an API promising a player list had nothing to
 * answer from.
 *
 * **Beside BackendPlayers rather than replacing it, deliberately.** That
 * message is load-bearing for the drain, and its own comment reasons carefully
 * about which players it counts --
 * ConnectedPlayer.getConnectionInFlightOrConnectedServer, so that a player
 * still handshaking is included. Deriving it from this one would put the
 * drain's correctness at the mercy of a change made for a reporting feature.
 * The two are built from one read of the same roster on the same tick, and
 * only this one is new.
 *
 * A state and not an event, like every other report here: each message carries
 * the whole roster, so a dropped one costs a report interval of freshness
 * rather than leaving somebody stranded on a list forever. A player absent
 * from the roster is a player this proxy no longer has.
 * </pre>
 *
 * Protobuf type {@code spawnery.agent.v1alpha1.PlayerRoster}
 */
@com.google.protobuf.Generated
public final class PlayerRoster extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:spawnery.agent.v1alpha1.PlayerRoster)
    PlayerRosterOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "PlayerRoster");
  }
  // Use PlayerRoster.newBuilder() to construct.
  private PlayerRoster(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PlayerRoster() {
    players_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_PlayerRoster_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_PlayerRoster_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_PlayerRoster_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.spawnery.agent.pb.PlayerRoster.class, cloud.spawnery.agent.pb.PlayerRoster.Builder.class);
  }

  public static final int PLAYERS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<cloud.spawnery.agent.pb.RosterEntry> players_;
  /**
   * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 1;</code>
   */
  @java.lang.Override
  public java.util.List<cloud.spawnery.agent.pb.RosterEntry> getPlayersList() {
    return players_;
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends cloud.spawnery.agent.pb.RosterEntryOrBuilder> 
      getPlayersOrBuilderList() {
    return players_;
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 1;</code>
   */
  @java.lang.Override
  public int getPlayersCount() {
    return players_.size();
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 1;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.RosterEntry getPlayers(int index) {
    return players_.get(index);
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 1;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.RosterEntryOrBuilder getPlayersOrBuilder(
      int index) {
    return players_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < players_.size(); i++) {
      output.writeMessage(1, players_.get(i));
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;

        {
          final int count = players_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(players_.get(i));
          }
          size += 1 * count;
        }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.spawnery.agent.pb.PlayerRoster)) {
      return super.equals(obj);
    }
    cloud.spawnery.agent.pb.PlayerRoster other = (cloud.spawnery.agent.pb.PlayerRoster) obj;

    if (!getPlayersList()
        .equals(other.getPlayersList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPlayersCount() > 0) {
      hash = (37 * hash) + PLAYERS_FIELD_NUMBER;
      hash = (53 * hash) + getPlayersList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.spawnery.agent.pb.PlayerRoster parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.PlayerRoster parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.PlayerRoster parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.PlayerRoster parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.PlayerRoster parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.PlayerRoster parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.PlayerRoster parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.PlayerRoster parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.spawnery.agent.pb.PlayerRoster parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.spawnery.agent.pb.PlayerRoster parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.PlayerRoster parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.PlayerRoster parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.spawnery.agent.pb.PlayerRoster prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * PlayerRoster is who this proxy is serving, by identity.
   *
   * It exists because the operator had no source for one. PlayerJoinedServer
   * carries a username and is accepted and ignored; PlayerCount and
   * BackendPlayers are counts. So the operator could say how many people were on
   * a backend and never who, and an API promising a player list had nothing to
   * answer from.
   *
   * **Beside BackendPlayers rather than replacing it, deliberately.** That
   * message is load-bearing for the drain, and its own comment reasons carefully
   * about which players it counts --
   * ConnectedPlayer.getConnectionInFlightOrConnectedServer, so that a player
   * still handshaking is included. Deriving it from this one would put the
   * drain's correctness at the mercy of a change made for a reporting feature.
   * The two are built from one read of the same roster on the same tick, and
   * only this one is new.
   *
   * A state and not an event, like every other report here: each message carries
   * the whole roster, so a dropped one costs a report interval of freshness
   * rather than leaving somebody stranded on a list forever. A player absent
   * from the roster is a player this proxy no longer has.
   * </pre>
   *
   * Protobuf type {@code spawnery.agent.v1alpha1.PlayerRoster}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:spawnery.agent.v1alpha1.PlayerRoster)
      cloud.spawnery.agent.pb.PlayerRosterOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_PlayerRoster_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_PlayerRoster_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.spawnery.agent.pb.PlayerRoster.class, cloud.spawnery.agent.pb.PlayerRoster.Builder.class);
    }

    // Construct using cloud.spawnery.agent.pb.PlayerRoster.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (playersBuilder_ == null) {
        players_ = java.util.Collections.emptyList();
      } else {
        players_ = null;
        playersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_PlayerRoster_descriptor;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.PlayerRoster getDefaultInstanceForType() {
      return cloud.spawnery.agent.pb.PlayerRoster.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.PlayerRoster build() {
      cloud.spawnery.agent.pb.PlayerRoster result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.PlayerRoster buildPartial() {
      cloud.spawnery.agent.pb.PlayerRoster result = new cloud.spawnery.agent.pb.PlayerRoster(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(cloud.spawnery.agent.pb.PlayerRoster result) {
      if (playersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          players_ = java.util.Collections.unmodifiableList(players_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.players_ = players_;
      } else {
        result.players_ = playersBuilder_.build();
      }
    }

    private void buildPartial0(cloud.spawnery.agent.pb.PlayerRoster result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.spawnery.agent.pb.PlayerRoster) {
        return mergeFrom((cloud.spawnery.agent.pb.PlayerRoster)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.spawnery.agent.pb.PlayerRoster other) {
      if (other == cloud.spawnery.agent.pb.PlayerRoster.getDefaultInstance()) return this;
      if (playersBuilder_ == null) {
        if (!other.players_.isEmpty()) {
          if (players_.isEmpty()) {
            players_ = other.players_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePlayersIsMutable();
            players_.addAll(other.players_);
          }
          onChanged();
        }
      } else {
        if (!other.players_.isEmpty()) {
          if (playersBuilder_.isEmpty()) {
            playersBuilder_.dispose();
            playersBuilder_ = null;
            players_ = other.players_;
            bitField0_ = (bitField0_ & ~0x00000001);
            playersBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetPlayersFieldBuilder() : null;
          } else {
            playersBuilder_.addAllMessages(other.players_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              cloud.spawnery.agent.pb.RosterEntry m =
                  input.readMessage(
                      cloud.spawnery.agent.pb.RosterEntry.parser(),
                      extensionRegistry);
              if (playersBuilder_ == null) {
                ensurePlayersIsMutable();
                players_.add(m);
              } else {
                playersBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<cloud.spawnery.agent.pb.RosterEntry> players_ =
      java.util.Collections.emptyList();
    private void ensurePlayersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        players_ = new java.util.ArrayList<cloud.spawnery.agent.pb.RosterEntry>(players_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.spawnery.agent.pb.RosterEntry, cloud.spawnery.agent.pb.RosterEntry.Builder, cloud.spawnery.agent.pb.RosterEntryOrBuilder> playersBuilder_;

    /**
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 1;</code>
     */
    public java.util.List<cloud.spawnery.agent.pb.RosterEntry> getPlayersList() {
      if (playersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(players_);
      } else {
        return playersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 1;</code>
     */
    public int getPlayersCount() {
      if (playersBuilder_ == null) {
        return players_.size();
      } else {
        return playersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 1;</code>
     */
    public cloud.spawnery.agent.pb.RosterEntry getPlayers(int index) {
      if (playersBuilder_ == null) {
        return players_.get(index);
      } else {
        return playersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 1;</code>
     */
    public Builder setPlayers(
        int index, cloud.spawnery.agent.pb.RosterEntry value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.set(index, value);
        onChanged();
      } else {
        playersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 1;</code>
     */
    public Builder setPlayers(
        int index, cloud.spawnery.agent.pb.RosterEntry.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.set(index, builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 1;</code>
     */
    public Builder addPlayers(cloud.spawnery.agent.pb.RosterEntry value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.add(value);
        onChanged();
      } else {
        playersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 1;</code>
     */
    public Builder addPlayers(
        int index, cloud.spawnery.agent.pb.RosterEntry value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.add(index, value);
        onChanged();
      } else {
        playersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 1;</code>
     */
    public Builder addPlayers(
        cloud.spawnery.agent.pb.RosterEntry.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.add(builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 1;</code>
     */
    public Builder addPlayers(
        int index, cloud.spawnery.agent.pb.RosterEntry.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.add(index, builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 1;</code>
     */
    public Builder addAllPlayers(
        java.lang.Iterable<? extends cloud.spawnery.agent.pb.RosterEntry> values) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, players_);
        onChanged();
      } else {
        playersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 1;</code>
     */
    public Builder clearPlayers() {
      if (playersBuilder_ == null) {
        players_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        playersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 1;</code>
     */
    public Builder removePlayers(int index) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.remove(index);
        onChanged();
      } else {
        playersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 1;</code>
     */
    public cloud.spawnery.agent.pb.RosterEntry.Builder getPlayersBuilder(
        int index) {
      return internalGetPlayersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 1;</code>
     */
    public cloud.spawnery.agent.pb.RosterEntryOrBuilder getPlayersOrBuilder(
        int index) {
      if (playersBuilder_ == null) {
        return players_.get(index);  } else {
        return playersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 1;</code>
     */
    public java.util.List<? extends cloud.spawnery.agent.pb.RosterEntryOrBuilder> 
         getPlayersOrBuilderList() {
      if (playersBuilder_ != null) {
        return playersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(players_);
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 1;</code>
     */
    public cloud.spawnery.agent.pb.RosterEntry.Builder addPlayersBuilder() {
      return internalGetPlayersFieldBuilder().addBuilder(
          cloud.spawnery.agent.pb.RosterEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 1;</code>
     */
    public cloud.spawnery.agent.pb.RosterEntry.Builder addPlayersBuilder(
        int index) {
      return internalGetPlayersFieldBuilder().addBuilder(
          index, cloud.spawnery.agent.pb.RosterEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.RosterEntry players = 1;</code>
     */
    public java.util.List<cloud.spawnery.agent.pb.RosterEntry.Builder> 
         getPlayersBuilderList() {
      return internalGetPlayersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.spawnery.agent.pb.RosterEntry, cloud.spawnery.agent.pb.RosterEntry.Builder, cloud.spawnery.agent.pb.RosterEntryOrBuilder> 
        internalGetPlayersFieldBuilder() {
      if (playersBuilder_ == null) {
        playersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            cloud.spawnery.agent.pb.RosterEntry, cloud.spawnery.agent.pb.RosterEntry.Builder, cloud.spawnery.agent.pb.RosterEntryOrBuilder>(
                players_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        players_ = null;
      }
      return playersBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:spawnery.agent.v1alpha1.PlayerRoster)
  }

  // @@protoc_insertion_point(class_scope:spawnery.agent.v1alpha1.PlayerRoster)
  private static final cloud.spawnery.agent.pb.PlayerRoster DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.spawnery.agent.pb.PlayerRoster();
  }

  public static cloud.spawnery.agent.pb.PlayerRoster getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PlayerRoster>
      PARSER = new com.google.protobuf.AbstractParser<PlayerRoster>() {
    @java.lang.Override
    public PlayerRoster parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PlayerRoster> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PlayerRoster> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.spawnery.agent.pb.PlayerRoster getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

