// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

/**
 * <pre>
 * PlayerCount is the periodic report.
 *
 * A proxy reports its configured player limit as slots, not zero: the
 * registry discards any report where players exceed slots.
 * </pre>
 *
 * Protobuf type {@code spawnery.agent.v1alpha1.PlayerCount}
 */
@com.google.protobuf.Generated
public final class PlayerCount extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:spawnery.agent.v1alpha1.PlayerCount)
    PlayerCountOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "PlayerCount");
  }
  // Use PlayerCount.newBuilder() to construct.
  private PlayerCount(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PlayerCount() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_PlayerCount_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_PlayerCount_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_PlayerCount_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.spawnery.agent.pb.PlayerCount.class, cloud.spawnery.agent.pb.PlayerCount.Builder.class);
  }

  public static final int PLAYERS_FIELD_NUMBER = 1;
  private int players_ = 0;
  /**
   * <code>int32 players = 1;</code>
   * @return The players.
   */
  @java.lang.Override
  public int getPlayers() {
    return players_;
  }

  public static final int SLOTS_FIELD_NUMBER = 2;
  private int slots_ = 0;
  /**
   * <code>int32 slots = 2;</code>
   * @return The slots.
   */
  @java.lang.Override
  public int getSlots() {
    return slots_;
  }

  public static final int TPS_FIELD_NUMBER = 3;
  private double tps_ = 0D;
  /**
   * <pre>
   * Server agents only: the server's one-minute TPS average and its mean tick
   * duration in milliseconds. 0 means not reported.
   * </pre>
   *
   * <code>double tps = 3;</code>
   * @return The tps.
   */
  @java.lang.Override
  public double getTps() {
    return tps_;
  }

  public static final int MSPT_FIELD_NUMBER = 4;
  private double mspt_ = 0D;
  /**
   * <code>double mspt = 4;</code>
   * @return The mspt.
   */
  @java.lang.Override
  public double getMspt() {
    return mspt_;
  }

  public static final int PLAYABLE_SLOTS_FIELD_NUMBER = 5;
  private int playableSlots_ = 0;
  /**
   * <pre>
   * Server agents only: the seats the plugin says count as capacity. 0 means
   * it said nothing, and the group's spec.playableSlots decides. Not carried
   * in slots, because players beyond the playable seats are legitimate.
   * </pre>
   *
   * <code>int32 playable_slots = 5;</code>
   * @return The playableSlots.
   */
  @java.lang.Override
  public int getPlayableSlots() {
    return playableSlots_;
  }

  public static final int HEAP_USED_BYTES_FIELD_NUMBER = 6;
  private long heapUsedBytes_ = 0L;
  /**
   * <pre>
   * Both agents: the JVM heap in use and its maximum, in bytes. 0 means not
   * reported.
   * </pre>
   *
   * <code>int64 heap_used_bytes = 6;</code>
   * @return The heapUsedBytes.
   */
  @java.lang.Override
  public long getHeapUsedBytes() {
    return heapUsedBytes_;
  }

  public static final int HEAP_MAX_BYTES_FIELD_NUMBER = 7;
  private long heapMaxBytes_ = 0L;
  /**
   * <code>int64 heap_max_bytes = 7;</code>
   * @return The heapMaxBytes.
   */
  @java.lang.Override
  public long getHeapMaxBytes() {
    return heapMaxBytes_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (players_ != 0) {
      output.writeInt32(1, players_);
    }
    if (slots_ != 0) {
      output.writeInt32(2, slots_);
    }
    if (java.lang.Double.doubleToRawLongBits(tps_) != 0) {
      output.writeDouble(3, tps_);
    }
    if (java.lang.Double.doubleToRawLongBits(mspt_) != 0) {
      output.writeDouble(4, mspt_);
    }
    if (playableSlots_ != 0) {
      output.writeInt32(5, playableSlots_);
    }
    if (heapUsedBytes_ != 0L) {
      output.writeInt64(6, heapUsedBytes_);
    }
    if (heapMaxBytes_ != 0L) {
      output.writeInt64(7, heapMaxBytes_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (players_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, players_);
    }
    if (slots_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, slots_);
    }
    if (java.lang.Double.doubleToRawLongBits(tps_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, tps_);
    }
    if (java.lang.Double.doubleToRawLongBits(mspt_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, mspt_);
    }
    if (playableSlots_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, playableSlots_);
    }
    if (heapUsedBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, heapUsedBytes_);
    }
    if (heapMaxBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, heapMaxBytes_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.spawnery.agent.pb.PlayerCount)) {
      return super.equals(obj);
    }
    cloud.spawnery.agent.pb.PlayerCount other = (cloud.spawnery.agent.pb.PlayerCount) obj;

    if (getPlayers()
        != other.getPlayers()) return false;
    if (getSlots()
        != other.getSlots()) return false;
    if (java.lang.Double.doubleToLongBits(getTps())
        != java.lang.Double.doubleToLongBits(
            other.getTps())) return false;
    if (java.lang.Double.doubleToLongBits(getMspt())
        != java.lang.Double.doubleToLongBits(
            other.getMspt())) return false;
    if (getPlayableSlots()
        != other.getPlayableSlots()) return false;
    if (getHeapUsedBytes()
        != other.getHeapUsedBytes()) return false;
    if (getHeapMaxBytes()
        != other.getHeapMaxBytes()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PLAYERS_FIELD_NUMBER;
    hash = (53 * hash) + getPlayers();
    hash = (37 * hash) + SLOTS_FIELD_NUMBER;
    hash = (53 * hash) + getSlots();
    hash = (37 * hash) + TPS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTps()));
    hash = (37 * hash) + MSPT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMspt()));
    hash = (37 * hash) + PLAYABLE_SLOTS_FIELD_NUMBER;
    hash = (53 * hash) + getPlayableSlots();
    hash = (37 * hash) + HEAP_USED_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getHeapUsedBytes());
    hash = (37 * hash) + HEAP_MAX_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getHeapMaxBytes());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.spawnery.agent.pb.PlayerCount parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.PlayerCount parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.PlayerCount parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.PlayerCount parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.PlayerCount parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.PlayerCount parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.PlayerCount parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.PlayerCount parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.spawnery.agent.pb.PlayerCount parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.spawnery.agent.pb.PlayerCount parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.PlayerCount parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.PlayerCount parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.spawnery.agent.pb.PlayerCount prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * PlayerCount is the periodic report.
   *
   * A proxy reports its configured player limit as slots, not zero: the
   * registry discards any report where players exceed slots.
   * </pre>
   *
   * Protobuf type {@code spawnery.agent.v1alpha1.PlayerCount}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:spawnery.agent.v1alpha1.PlayerCount)
      cloud.spawnery.agent.pb.PlayerCountOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_PlayerCount_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_PlayerCount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.spawnery.agent.pb.PlayerCount.class, cloud.spawnery.agent.pb.PlayerCount.Builder.class);
    }

    // Construct using cloud.spawnery.agent.pb.PlayerCount.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      players_ = 0;
      slots_ = 0;
      tps_ = 0D;
      mspt_ = 0D;
      playableSlots_ = 0;
      heapUsedBytes_ = 0L;
      heapMaxBytes_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_PlayerCount_descriptor;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.PlayerCount getDefaultInstanceForType() {
      return cloud.spawnery.agent.pb.PlayerCount.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.PlayerCount build() {
      cloud.spawnery.agent.pb.PlayerCount result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.PlayerCount buildPartial() {
      cloud.spawnery.agent.pb.PlayerCount result = new cloud.spawnery.agent.pb.PlayerCount(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(cloud.spawnery.agent.pb.PlayerCount result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.players_ = players_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.slots_ = slots_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.tps_ = tps_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.mspt_ = mspt_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.playableSlots_ = playableSlots_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.heapUsedBytes_ = heapUsedBytes_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.heapMaxBytes_ = heapMaxBytes_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.spawnery.agent.pb.PlayerCount) {
        return mergeFrom((cloud.spawnery.agent.pb.PlayerCount)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.spawnery.agent.pb.PlayerCount other) {
      if (other == cloud.spawnery.agent.pb.PlayerCount.getDefaultInstance()) return this;
      if (other.getPlayers() != 0) {
        setPlayers(other.getPlayers());
      }
      if (other.getSlots() != 0) {
        setSlots(other.getSlots());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getTps()) != 0) {
        setTps(other.getTps());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getMspt()) != 0) {
        setMspt(other.getMspt());
      }
      if (other.getPlayableSlots() != 0) {
        setPlayableSlots(other.getPlayableSlots());
      }
      if (other.getHeapUsedBytes() != 0L) {
        setHeapUsedBytes(other.getHeapUsedBytes());
      }
      if (other.getHeapMaxBytes() != 0L) {
        setHeapMaxBytes(other.getHeapMaxBytes());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              players_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              slots_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 25: {
              tps_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              mspt_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 40: {
              playableSlots_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              heapUsedBytes_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              heapMaxBytes_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int players_ ;
    /**
     * <code>int32 players = 1;</code>
     * @return The players.
     */
    @java.lang.Override
    public int getPlayers() {
      return players_;
    }
    /**
     * <code>int32 players = 1;</code>
     * @param value The players to set.
     * @return This builder for chaining.
     */
    public Builder setPlayers(int value) {

      players_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 players = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayers() {
      bitField0_ = (bitField0_ & ~0x00000001);
      players_ = 0;
      onChanged();
      return this;
    }

    private int slots_ ;
    /**
     * <code>int32 slots = 2;</code>
     * @return The slots.
     */
    @java.lang.Override
    public int getSlots() {
      return slots_;
    }
    /**
     * <code>int32 slots = 2;</code>
     * @param value The slots to set.
     * @return This builder for chaining.
     */
    public Builder setSlots(int value) {

      slots_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 slots = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSlots() {
      bitField0_ = (bitField0_ & ~0x00000002);
      slots_ = 0;
      onChanged();
      return this;
    }

    private double tps_ ;
    /**
     * <pre>
     * Server agents only: the server's one-minute TPS average and its mean tick
     * duration in milliseconds. 0 means not reported.
     * </pre>
     *
     * <code>double tps = 3;</code>
     * @return The tps.
     */
    @java.lang.Override
    public double getTps() {
      return tps_;
    }
    /**
     * <pre>
     * Server agents only: the server's one-minute TPS average and its mean tick
     * duration in milliseconds. 0 means not reported.
     * </pre>
     *
     * <code>double tps = 3;</code>
     * @param value The tps to set.
     * @return This builder for chaining.
     */
    public Builder setTps(double value) {

      tps_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Server agents only: the server's one-minute TPS average and its mean tick
     * duration in milliseconds. 0 means not reported.
     * </pre>
     *
     * <code>double tps = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTps() {
      bitField0_ = (bitField0_ & ~0x00000004);
      tps_ = 0D;
      onChanged();
      return this;
    }

    private double mspt_ ;
    /**
     * <code>double mspt = 4;</code>
     * @return The mspt.
     */
    @java.lang.Override
    public double getMspt() {
      return mspt_;
    }
    /**
     * <code>double mspt = 4;</code>
     * @param value The mspt to set.
     * @return This builder for chaining.
     */
    public Builder setMspt(double value) {

      mspt_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>double mspt = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMspt() {
      bitField0_ = (bitField0_ & ~0x00000008);
      mspt_ = 0D;
      onChanged();
      return this;
    }

    private int playableSlots_ ;
    /**
     * <pre>
     * Server agents only: the seats the plugin says count as capacity. 0 means
     * it said nothing, and the group's spec.playableSlots decides. Not carried
     * in slots, because players beyond the playable seats are legitimate.
     * </pre>
     *
     * <code>int32 playable_slots = 5;</code>
     * @return The playableSlots.
     */
    @java.lang.Override
    public int getPlayableSlots() {
      return playableSlots_;
    }
    /**
     * <pre>
     * Server agents only: the seats the plugin says count as capacity. 0 means
     * it said nothing, and the group's spec.playableSlots decides. Not carried
     * in slots, because players beyond the playable seats are legitimate.
     * </pre>
     *
     * <code>int32 playable_slots = 5;</code>
     * @param value The playableSlots to set.
     * @return This builder for chaining.
     */
    public Builder setPlayableSlots(int value) {

      playableSlots_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Server agents only: the seats the plugin says count as capacity. 0 means
     * it said nothing, and the group's spec.playableSlots decides. Not carried
     * in slots, because players beyond the playable seats are legitimate.
     * </pre>
     *
     * <code>int32 playable_slots = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayableSlots() {
      bitField0_ = (bitField0_ & ~0x00000010);
      playableSlots_ = 0;
      onChanged();
      return this;
    }

    private long heapUsedBytes_ ;
    /**
     * <pre>
     * Both agents: the JVM heap in use and its maximum, in bytes. 0 means not
     * reported.
     * </pre>
     *
     * <code>int64 heap_used_bytes = 6;</code>
     * @return The heapUsedBytes.
     */
    @java.lang.Override
    public long getHeapUsedBytes() {
      return heapUsedBytes_;
    }
    /**
     * <pre>
     * Both agents: the JVM heap in use and its maximum, in bytes. 0 means not
     * reported.
     * </pre>
     *
     * <code>int64 heap_used_bytes = 6;</code>
     * @param value The heapUsedBytes to set.
     * @return This builder for chaining.
     */
    public Builder setHeapUsedBytes(long value) {

      heapUsedBytes_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Both agents: the JVM heap in use and its maximum, in bytes. 0 means not
     * reported.
     * </pre>
     *
     * <code>int64 heap_used_bytes = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeapUsedBytes() {
      bitField0_ = (bitField0_ & ~0x00000020);
      heapUsedBytes_ = 0L;
      onChanged();
      return this;
    }

    private long heapMaxBytes_ ;
    /**
     * <code>int64 heap_max_bytes = 7;</code>
     * @return The heapMaxBytes.
     */
    @java.lang.Override
    public long getHeapMaxBytes() {
      return heapMaxBytes_;
    }
    /**
     * <code>int64 heap_max_bytes = 7;</code>
     * @param value The heapMaxBytes to set.
     * @return This builder for chaining.
     */
    public Builder setHeapMaxBytes(long value) {

      heapMaxBytes_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int64 heap_max_bytes = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeapMaxBytes() {
      bitField0_ = (bitField0_ & ~0x00000040);
      heapMaxBytes_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:spawnery.agent.v1alpha1.PlayerCount)
  }

  // @@protoc_insertion_point(class_scope:spawnery.agent.v1alpha1.PlayerCount)
  private static final cloud.spawnery.agent.pb.PlayerCount DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.spawnery.agent.pb.PlayerCount();
  }

  public static cloud.spawnery.agent.pb.PlayerCount getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PlayerCount>
      PARSER = new com.google.protobuf.AbstractParser<PlayerCount>() {
    @java.lang.Override
    public PlayerCount parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PlayerCount> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PlayerCount> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.spawnery.agent.pb.PlayerCount getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

