// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface ProxyStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.ProxyState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The ProxyGroup the pod belongs to.
   * </pre>
   *
   * <code>string group = 2;</code>
   * @return The group.
   */
  java.lang.String getGroup();
  /**
   * <pre>
   * The ProxyGroup the pod belongs to.
   * </pre>
   *
   * <code>string group = 2;</code>
   * @return The bytes for group.
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <code>bool ready = 3;</code>
   * @return The ready.
   */
  boolean getReady();

  /**
   * <pre>
   * Taking no new connections.
   * </pre>
   *
   * <code>bool draining = 4;</code>
   * @return The draining.
   */
  boolean getDraining();

  /**
   * <code>int32 players = 5;</code>
   * @return The players.
   */
  int getPlayers();
}
