// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface ProxyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.ProxyMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.spawnery.agent.v1alpha1.Hello hello = 1;</code>
   * @return Whether the hello field is set.
   */
  boolean hasHello();
  /**
   * <code>.spawnery.agent.v1alpha1.Hello hello = 1;</code>
   * @return The hello.
   */
  cloud.spawnery.agent.pb.Hello getHello();
  /**
   * <code>.spawnery.agent.v1alpha1.Hello hello = 1;</code>
   */
  cloud.spawnery.agent.pb.HelloOrBuilder getHelloOrBuilder();

  /**
   * <code>.spawnery.agent.v1alpha1.PlayerCount player_count = 2;</code>
   * @return Whether the playerCount field is set.
   */
  boolean hasPlayerCount();
  /**
   * <code>.spawnery.agent.v1alpha1.PlayerCount player_count = 2;</code>
   * @return The playerCount.
   */
  cloud.spawnery.agent.pb.PlayerCount getPlayerCount();
  /**
   * <code>.spawnery.agent.v1alpha1.PlayerCount player_count = 2;</code>
   */
  cloud.spawnery.agent.pb.PlayerCountOrBuilder getPlayerCountOrBuilder();

  /**
   * <code>.spawnery.agent.v1alpha1.PlayerJoinedServer player_joined_server = 3;</code>
   * @return Whether the playerJoinedServer field is set.
   */
  boolean hasPlayerJoinedServer();
  /**
   * <code>.spawnery.agent.v1alpha1.PlayerJoinedServer player_joined_server = 3;</code>
   * @return The playerJoinedServer.
   */
  cloud.spawnery.agent.pb.PlayerJoinedServer getPlayerJoinedServer();
  /**
   * <code>.spawnery.agent.v1alpha1.PlayerJoinedServer player_joined_server = 3;</code>
   */
  cloud.spawnery.agent.pb.PlayerJoinedServerOrBuilder getPlayerJoinedServerOrBuilder();

  /**
   * <code>.spawnery.agent.v1alpha1.Heartbeat heartbeat = 4;</code>
   * @return Whether the heartbeat field is set.
   */
  boolean hasHeartbeat();
  /**
   * <code>.spawnery.agent.v1alpha1.Heartbeat heartbeat = 4;</code>
   * @return The heartbeat.
   */
  cloud.spawnery.agent.pb.Heartbeat getHeartbeat();
  /**
   * <code>.spawnery.agent.v1alpha1.Heartbeat heartbeat = 4;</code>
   */
  cloud.spawnery.agent.pb.HeartbeatOrBuilder getHeartbeatOrBuilder();

  cloud.spawnery.agent.pb.ProxyMessage.MessageCase getMessageCase();
}
