// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface RestorePointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.RestorePoint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 generation = 1;</code>
   * @return The generation.
   */
  long getGeneration();

  /**
   * <pre>
   * When the node took the snapshot, not when it reached the object store.
   * </pre>
   *
   * <code>int64 taken_unix_millis = 2;</code>
   * @return The takenUnixMillis.
   */
  long getTakenUnixMillis();

  /**
   * <pre>
   * The world as it stands; a restore cannot pick it.
   * </pre>
   *
   * <code>bool current = 3;</code>
   * @return The current.
   */
  boolean getCurrent();
}
