// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface RetireResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.RetireResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The server that is now retiring, echoed so a caller that asked by a name
   * it built from a string sees what the operator matched.
   * </pre>
   *
   * <code>string server = 1;</code>
   * @return The server.
   */
  java.lang.String getServer();
  /**
   * <pre>
   * The server that is now retiring, echoed so a caller that asked by a name
   * it built from a string sees what the operator matched.
   * </pre>
   *
   * <code>string server = 1;</code>
   * @return The bytes for server.
   */
  com.google.protobuf.ByteString
      getServerBytes();
}
