// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface RetireRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.RetireRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string server = 1;</code>
   * @return The server.
   */
  java.lang.String getServer();
  /**
   * <code>string server = 1;</code>
   * @return The bytes for server.
   */
  com.google.protobuf.ByteString
      getServerBytes();
}
