// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface RosterEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.RosterEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The Minecraft UUID, the only stable identity here.
   * </pre>
   *
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <pre>
   * The Minecraft UUID, the only stable identity here.
   * </pre>
   *
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <pre>
   * The username. The operator holds it in memory only -- no CR, no etcd, no
   * metric label.
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The username. The operator holds it in memory only -- no CR, no etcd, no
   * metric label.
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The backend this player is on, or on their way to, empty when neither.
   * The same field BackendPlayers counts.
   * </pre>
   *
   * <code>string server = 3;</code>
   * @return The server.
   */
  java.lang.String getServer();
  /**
   * <pre>
   * The backend this player is on, or on their way to, empty when neither.
   * The same field BackendPlayers counts.
   * </pre>
   *
   * <code>string server = 3;</code>
   * @return The bytes for server.
   */
  com.google.protobuf.ByteString
      getServerBytes();
}
