// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface ScaleResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.ScaleResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 replicas = 1;</code>
   * @return The replicas.
   */
  int getReplicas();

  /**
   * <code>int64 expires_at_unix = 2;</code>
   * @return The expiresAtUnix.
   */
  long getExpiresAtUnix();
}
