// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface ServerStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.ServerState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string group = 2;</code>
   * @return The group.
   */
  java.lang.String getGroup();
  /**
   * <code>string group = 2;</code>
   * @return The bytes for group.
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <pre>
   * The operator's phase spelling -- see NetworkState on why this is a string.
   * </pre>
   *
   * <code>string phase = 3;</code>
   * @return The phase.
   */
  java.lang.String getPhase();
  /**
   * <pre>
   * The operator's phase spelling -- see NetworkState on why this is a string.
   * </pre>
   *
   * <code>string phase = 3;</code>
   * @return The bytes for phase.
   */
  com.google.protobuf.ByteString
      getPhaseBytes();

  /**
   * <code>int32 players = 4;</code>
   * @return The players.
   */
  int getPlayers();

  /**
   * <code>int32 slots = 5;</code>
   * @return The slots.
   */
  int getSlots();

  /**
   * <pre>
   * Whether the proxies have this server in their routing tables. A server can
   * be Ready and not registered -- that is the first half of a drain -- so a
   * plugin choosing where to send somebody wants this and not the phase.
   * </pre>
   *
   * <code>bool registered = 6;</code>
   * @return The registered.
   */
  boolean getRegistered();

  /**
   * <pre>
   * What this server last said about itself, and nothing the operator decided.
   * See AnnounceRequest. Both are empty for a server that has announced
   * nothing, which is every server until something on it says otherwise --
   * absent and "announced nothing" are the same state here on purpose, because
   * a plugin that has to tell them apart is asking about the agent rather than
   * about the game.
   * </pre>
   *
   * <code>string state = 7;</code>
   * @return The state.
   */
  java.lang.String getState();
  /**
   * <pre>
   * What this server last said about itself, and nothing the operator decided.
   * See AnnounceRequest. Both are empty for a server that has announced
   * nothing, which is every server until something on it says otherwise --
   * absent and "announced nothing" are the same state here on purpose, because
   * a plugin that has to tell them apart is asking about the agent rather than
   * about the game.
   * </pre>
   *
   * <code>string state = 7;</code>
   * @return The bytes for state.
   */
  com.google.protobuf.ByteString
      getStateBytes();

  /**
   * <code>map&lt;string, string&gt; attributes = 8;</code>
   */
  int getAttributesCount();
  /**
   * <code>map&lt;string, string&gt; attributes = 8;</code>
   */
  boolean containsAttributes(
      java.lang.String key);
  /**
   * Use {@link #getAttributesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getAttributes();
  /**
   * <code>map&lt;string, string&gt; attributes = 8;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getAttributesMap();
  /**
   * <code>map&lt;string, string&gt; attributes = 8;</code>
   */
  /* nullable */
java.lang.String getAttributesOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; attributes = 8;</code>
   */
  java.lang.String getAttributesOrThrow(
      java.lang.String key);
}
