// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface ServerMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.ServerMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.spawnery.agent.v1alpha1.Hello hello = 1;</code>
   * @return Whether the hello field is set.
   */
  boolean hasHello();
  /**
   * <code>.spawnery.agent.v1alpha1.Hello hello = 1;</code>
   * @return The hello.
   */
  cloud.spawnery.agent.pb.Hello getHello();
  /**
   * <code>.spawnery.agent.v1alpha1.Hello hello = 1;</code>
   */
  cloud.spawnery.agent.pb.HelloOrBuilder getHelloOrBuilder();

  /**
   * <code>.spawnery.agent.v1alpha1.Ready ready = 2;</code>
   * @return Whether the ready field is set.
   */
  boolean hasReady();
  /**
   * <code>.spawnery.agent.v1alpha1.Ready ready = 2;</code>
   * @return The ready.
   */
  cloud.spawnery.agent.pb.Ready getReady();
  /**
   * <code>.spawnery.agent.v1alpha1.Ready ready = 2;</code>
   */
  cloud.spawnery.agent.pb.ReadyOrBuilder getReadyOrBuilder();

  /**
   * <code>.spawnery.agent.v1alpha1.PlayerCount player_count = 3;</code>
   * @return Whether the playerCount field is set.
   */
  boolean hasPlayerCount();
  /**
   * <code>.spawnery.agent.v1alpha1.PlayerCount player_count = 3;</code>
   * @return The playerCount.
   */
  cloud.spawnery.agent.pb.PlayerCount getPlayerCount();
  /**
   * <code>.spawnery.agent.v1alpha1.PlayerCount player_count = 3;</code>
   */
  cloud.spawnery.agent.pb.PlayerCountOrBuilder getPlayerCountOrBuilder();

  /**
   * <code>.spawnery.agent.v1alpha1.CloudRequest cloud_request = 4;</code>
   * @return Whether the cloudRequest field is set.
   */
  boolean hasCloudRequest();
  /**
   * <code>.spawnery.agent.v1alpha1.CloudRequest cloud_request = 4;</code>
   * @return The cloudRequest.
   */
  cloud.spawnery.agent.pb.CloudRequest getCloudRequest();
  /**
   * <code>.spawnery.agent.v1alpha1.CloudRequest cloud_request = 4;</code>
   */
  cloud.spawnery.agent.pb.CloudRequestOrBuilder getCloudRequestOrBuilder();

  cloud.spawnery.agent.pb.ServerMessage.MessageCase getMessageCase();
}
