// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

/**
 * Protobuf type {@code spawnery.agent.v1alpha1.ServerMessage}
 */
@com.google.protobuf.Generated
public final class ServerMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:spawnery.agent.v1alpha1.ServerMessage)
    ServerMessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "ServerMessage");
  }
  // Use ServerMessage.newBuilder() to construct.
  private ServerMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ServerMessage() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_ServerMessage_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_ServerMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_ServerMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.spawnery.agent.pb.ServerMessage.class, cloud.spawnery.agent.pb.ServerMessage.Builder.class);
  }

  private int messageCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object message_;
  public enum MessageCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    HELLO(1),
    READY(2),
    PLAYER_COUNT(3),
    MESSAGE_NOT_SET(0);
    private final int value;
    private MessageCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageCase valueOf(int value) {
      return forNumber(value);
    }

    public static MessageCase forNumber(int value) {
      switch (value) {
        case 1: return HELLO;
        case 2: return READY;
        case 3: return PLAYER_COUNT;
        case 0: return MESSAGE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MessageCase
  getMessageCase() {
    return MessageCase.forNumber(
        messageCase_);
  }

  public static final int HELLO_FIELD_NUMBER = 1;
  /**
   * <code>.spawnery.agent.v1alpha1.Hello hello = 1;</code>
   * @return Whether the hello field is set.
   */
  @java.lang.Override
  public boolean hasHello() {
    return messageCase_ == 1;
  }
  /**
   * <code>.spawnery.agent.v1alpha1.Hello hello = 1;</code>
   * @return The hello.
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.Hello getHello() {
    if (messageCase_ == 1) {
       return (cloud.spawnery.agent.pb.Hello) message_;
    }
    return cloud.spawnery.agent.pb.Hello.getDefaultInstance();
  }
  /**
   * <code>.spawnery.agent.v1alpha1.Hello hello = 1;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.HelloOrBuilder getHelloOrBuilder() {
    if (messageCase_ == 1) {
       return (cloud.spawnery.agent.pb.Hello) message_;
    }
    return cloud.spawnery.agent.pb.Hello.getDefaultInstance();
  }

  public static final int READY_FIELD_NUMBER = 2;
  /**
   * <code>.spawnery.agent.v1alpha1.Ready ready = 2;</code>
   * @return Whether the ready field is set.
   */
  @java.lang.Override
  public boolean hasReady() {
    return messageCase_ == 2;
  }
  /**
   * <code>.spawnery.agent.v1alpha1.Ready ready = 2;</code>
   * @return The ready.
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.Ready getReady() {
    if (messageCase_ == 2) {
       return (cloud.spawnery.agent.pb.Ready) message_;
    }
    return cloud.spawnery.agent.pb.Ready.getDefaultInstance();
  }
  /**
   * <code>.spawnery.agent.v1alpha1.Ready ready = 2;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.ReadyOrBuilder getReadyOrBuilder() {
    if (messageCase_ == 2) {
       return (cloud.spawnery.agent.pb.Ready) message_;
    }
    return cloud.spawnery.agent.pb.Ready.getDefaultInstance();
  }

  public static final int PLAYER_COUNT_FIELD_NUMBER = 3;
  /**
   * <code>.spawnery.agent.v1alpha1.PlayerCount player_count = 3;</code>
   * @return Whether the playerCount field is set.
   */
  @java.lang.Override
  public boolean hasPlayerCount() {
    return messageCase_ == 3;
  }
  /**
   * <code>.spawnery.agent.v1alpha1.PlayerCount player_count = 3;</code>
   * @return The playerCount.
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.PlayerCount getPlayerCount() {
    if (messageCase_ == 3) {
       return (cloud.spawnery.agent.pb.PlayerCount) message_;
    }
    return cloud.spawnery.agent.pb.PlayerCount.getDefaultInstance();
  }
  /**
   * <code>.spawnery.agent.v1alpha1.PlayerCount player_count = 3;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.PlayerCountOrBuilder getPlayerCountOrBuilder() {
    if (messageCase_ == 3) {
       return (cloud.spawnery.agent.pb.PlayerCount) message_;
    }
    return cloud.spawnery.agent.pb.PlayerCount.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageCase_ == 1) {
      output.writeMessage(1, (cloud.spawnery.agent.pb.Hello) message_);
    }
    if (messageCase_ == 2) {
      output.writeMessage(2, (cloud.spawnery.agent.pb.Ready) message_);
    }
    if (messageCase_ == 3) {
      output.writeMessage(3, (cloud.spawnery.agent.pb.PlayerCount) message_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (messageCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (cloud.spawnery.agent.pb.Hello) message_);
    }
    if (messageCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (cloud.spawnery.agent.pb.Ready) message_);
    }
    if (messageCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (cloud.spawnery.agent.pb.PlayerCount) message_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.spawnery.agent.pb.ServerMessage)) {
      return super.equals(obj);
    }
    cloud.spawnery.agent.pb.ServerMessage other = (cloud.spawnery.agent.pb.ServerMessage) obj;

    if (!getMessageCase().equals(other.getMessageCase())) return false;
    switch (messageCase_) {
      case 1:
        if (!getHello()
            .equals(other.getHello())) return false;
        break;
      case 2:
        if (!getReady()
            .equals(other.getReady())) return false;
        break;
      case 3:
        if (!getPlayerCount()
            .equals(other.getPlayerCount())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (messageCase_) {
      case 1:
        hash = (37 * hash) + HELLO_FIELD_NUMBER;
        hash = (53 * hash) + getHello().hashCode();
        break;
      case 2:
        hash = (37 * hash) + READY_FIELD_NUMBER;
        hash = (53 * hash) + getReady().hashCode();
        break;
      case 3:
        hash = (37 * hash) + PLAYER_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + getPlayerCount().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.spawnery.agent.pb.ServerMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.ServerMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.ServerMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.ServerMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.ServerMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.ServerMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.ServerMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.ServerMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.spawnery.agent.pb.ServerMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.spawnery.agent.pb.ServerMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.ServerMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.ServerMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.spawnery.agent.pb.ServerMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code spawnery.agent.v1alpha1.ServerMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:spawnery.agent.v1alpha1.ServerMessage)
      cloud.spawnery.agent.pb.ServerMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_ServerMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_ServerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.spawnery.agent.pb.ServerMessage.class, cloud.spawnery.agent.pb.ServerMessage.Builder.class);
    }

    // Construct using cloud.spawnery.agent.pb.ServerMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (helloBuilder_ != null) {
        helloBuilder_.clear();
      }
      if (readyBuilder_ != null) {
        readyBuilder_.clear();
      }
      if (playerCountBuilder_ != null) {
        playerCountBuilder_.clear();
      }
      messageCase_ = 0;
      message_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_ServerMessage_descriptor;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.ServerMessage getDefaultInstanceForType() {
      return cloud.spawnery.agent.pb.ServerMessage.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.ServerMessage build() {
      cloud.spawnery.agent.pb.ServerMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.ServerMessage buildPartial() {
      cloud.spawnery.agent.pb.ServerMessage result = new cloud.spawnery.agent.pb.ServerMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(cloud.spawnery.agent.pb.ServerMessage result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(cloud.spawnery.agent.pb.ServerMessage result) {
      result.messageCase_ = messageCase_;
      result.message_ = this.message_;
      if (messageCase_ == 1 &&
          helloBuilder_ != null) {
        result.message_ = helloBuilder_.build();
      }
      if (messageCase_ == 2 &&
          readyBuilder_ != null) {
        result.message_ = readyBuilder_.build();
      }
      if (messageCase_ == 3 &&
          playerCountBuilder_ != null) {
        result.message_ = playerCountBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.spawnery.agent.pb.ServerMessage) {
        return mergeFrom((cloud.spawnery.agent.pb.ServerMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.spawnery.agent.pb.ServerMessage other) {
      if (other == cloud.spawnery.agent.pb.ServerMessage.getDefaultInstance()) return this;
      switch (other.getMessageCase()) {
        case HELLO: {
          mergeHello(other.getHello());
          break;
        }
        case READY: {
          mergeReady(other.getReady());
          break;
        }
        case PLAYER_COUNT: {
          mergePlayerCount(other.getPlayerCount());
          break;
        }
        case MESSAGE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetHelloFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetReadyFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetPlayerCountFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 3;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int messageCase_ = 0;
    private java.lang.Object message_;
    public MessageCase
        getMessageCase() {
      return MessageCase.forNumber(
          messageCase_);
    }

    public Builder clearMessage() {
      messageCase_ = 0;
      message_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.Hello, cloud.spawnery.agent.pb.Hello.Builder, cloud.spawnery.agent.pb.HelloOrBuilder> helloBuilder_;
    /**
     * <code>.spawnery.agent.v1alpha1.Hello hello = 1;</code>
     * @return Whether the hello field is set.
     */
    @java.lang.Override
    public boolean hasHello() {
      return messageCase_ == 1;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.Hello hello = 1;</code>
     * @return The hello.
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.Hello getHello() {
      if (helloBuilder_ == null) {
        if (messageCase_ == 1) {
          return (cloud.spawnery.agent.pb.Hello) message_;
        }
        return cloud.spawnery.agent.pb.Hello.getDefaultInstance();
      } else {
        if (messageCase_ == 1) {
          return helloBuilder_.getMessage();
        }
        return cloud.spawnery.agent.pb.Hello.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.Hello hello = 1;</code>
     */
    public Builder setHello(cloud.spawnery.agent.pb.Hello value) {
      if (helloBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        helloBuilder_.setMessage(value);
      }
      messageCase_ = 1;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.Hello hello = 1;</code>
     */
    public Builder setHello(
        cloud.spawnery.agent.pb.Hello.Builder builderForValue) {
      if (helloBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        helloBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 1;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.Hello hello = 1;</code>
     */
    public Builder mergeHello(cloud.spawnery.agent.pb.Hello value) {
      if (helloBuilder_ == null) {
        if (messageCase_ == 1 &&
            message_ != cloud.spawnery.agent.pb.Hello.getDefaultInstance()) {
          message_ = cloud.spawnery.agent.pb.Hello.newBuilder((cloud.spawnery.agent.pb.Hello) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 1) {
          helloBuilder_.mergeFrom(value);
        } else {
          helloBuilder_.setMessage(value);
        }
      }
      messageCase_ = 1;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.Hello hello = 1;</code>
     */
    public Builder clearHello() {
      if (helloBuilder_ == null) {
        if (messageCase_ == 1) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 1) {
          messageCase_ = 0;
          message_ = null;
        }
        helloBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.Hello hello = 1;</code>
     */
    public cloud.spawnery.agent.pb.Hello.Builder getHelloBuilder() {
      return internalGetHelloFieldBuilder().getBuilder();
    }
    /**
     * <code>.spawnery.agent.v1alpha1.Hello hello = 1;</code>
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.HelloOrBuilder getHelloOrBuilder() {
      if ((messageCase_ == 1) && (helloBuilder_ != null)) {
        return helloBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 1) {
          return (cloud.spawnery.agent.pb.Hello) message_;
        }
        return cloud.spawnery.agent.pb.Hello.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.Hello hello = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.Hello, cloud.spawnery.agent.pb.Hello.Builder, cloud.spawnery.agent.pb.HelloOrBuilder> 
        internalGetHelloFieldBuilder() {
      if (helloBuilder_ == null) {
        if (!(messageCase_ == 1)) {
          message_ = cloud.spawnery.agent.pb.Hello.getDefaultInstance();
        }
        helloBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cloud.spawnery.agent.pb.Hello, cloud.spawnery.agent.pb.Hello.Builder, cloud.spawnery.agent.pb.HelloOrBuilder>(
                (cloud.spawnery.agent.pb.Hello) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 1;
      onChanged();
      return helloBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.Ready, cloud.spawnery.agent.pb.Ready.Builder, cloud.spawnery.agent.pb.ReadyOrBuilder> readyBuilder_;
    /**
     * <code>.spawnery.agent.v1alpha1.Ready ready = 2;</code>
     * @return Whether the ready field is set.
     */
    @java.lang.Override
    public boolean hasReady() {
      return messageCase_ == 2;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.Ready ready = 2;</code>
     * @return The ready.
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.Ready getReady() {
      if (readyBuilder_ == null) {
        if (messageCase_ == 2) {
          return (cloud.spawnery.agent.pb.Ready) message_;
        }
        return cloud.spawnery.agent.pb.Ready.getDefaultInstance();
      } else {
        if (messageCase_ == 2) {
          return readyBuilder_.getMessage();
        }
        return cloud.spawnery.agent.pb.Ready.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.Ready ready = 2;</code>
     */
    public Builder setReady(cloud.spawnery.agent.pb.Ready value) {
      if (readyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        readyBuilder_.setMessage(value);
      }
      messageCase_ = 2;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.Ready ready = 2;</code>
     */
    public Builder setReady(
        cloud.spawnery.agent.pb.Ready.Builder builderForValue) {
      if (readyBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        readyBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 2;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.Ready ready = 2;</code>
     */
    public Builder mergeReady(cloud.spawnery.agent.pb.Ready value) {
      if (readyBuilder_ == null) {
        if (messageCase_ == 2 &&
            message_ != cloud.spawnery.agent.pb.Ready.getDefaultInstance()) {
          message_ = cloud.spawnery.agent.pb.Ready.newBuilder((cloud.spawnery.agent.pb.Ready) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 2) {
          readyBuilder_.mergeFrom(value);
        } else {
          readyBuilder_.setMessage(value);
        }
      }
      messageCase_ = 2;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.Ready ready = 2;</code>
     */
    public Builder clearReady() {
      if (readyBuilder_ == null) {
        if (messageCase_ == 2) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 2) {
          messageCase_ = 0;
          message_ = null;
        }
        readyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.Ready ready = 2;</code>
     */
    public cloud.spawnery.agent.pb.Ready.Builder getReadyBuilder() {
      return internalGetReadyFieldBuilder().getBuilder();
    }
    /**
     * <code>.spawnery.agent.v1alpha1.Ready ready = 2;</code>
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.ReadyOrBuilder getReadyOrBuilder() {
      if ((messageCase_ == 2) && (readyBuilder_ != null)) {
        return readyBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 2) {
          return (cloud.spawnery.agent.pb.Ready) message_;
        }
        return cloud.spawnery.agent.pb.Ready.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.Ready ready = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.Ready, cloud.spawnery.agent.pb.Ready.Builder, cloud.spawnery.agent.pb.ReadyOrBuilder> 
        internalGetReadyFieldBuilder() {
      if (readyBuilder_ == null) {
        if (!(messageCase_ == 2)) {
          message_ = cloud.spawnery.agent.pb.Ready.getDefaultInstance();
        }
        readyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cloud.spawnery.agent.pb.Ready, cloud.spawnery.agent.pb.Ready.Builder, cloud.spawnery.agent.pb.ReadyOrBuilder>(
                (cloud.spawnery.agent.pb.Ready) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 2;
      onChanged();
      return readyBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.PlayerCount, cloud.spawnery.agent.pb.PlayerCount.Builder, cloud.spawnery.agent.pb.PlayerCountOrBuilder> playerCountBuilder_;
    /**
     * <code>.spawnery.agent.v1alpha1.PlayerCount player_count = 3;</code>
     * @return Whether the playerCount field is set.
     */
    @java.lang.Override
    public boolean hasPlayerCount() {
      return messageCase_ == 3;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.PlayerCount player_count = 3;</code>
     * @return The playerCount.
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.PlayerCount getPlayerCount() {
      if (playerCountBuilder_ == null) {
        if (messageCase_ == 3) {
          return (cloud.spawnery.agent.pb.PlayerCount) message_;
        }
        return cloud.spawnery.agent.pb.PlayerCount.getDefaultInstance();
      } else {
        if (messageCase_ == 3) {
          return playerCountBuilder_.getMessage();
        }
        return cloud.spawnery.agent.pb.PlayerCount.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.PlayerCount player_count = 3;</code>
     */
    public Builder setPlayerCount(cloud.spawnery.agent.pb.PlayerCount value) {
      if (playerCountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        playerCountBuilder_.setMessage(value);
      }
      messageCase_ = 3;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.PlayerCount player_count = 3;</code>
     */
    public Builder setPlayerCount(
        cloud.spawnery.agent.pb.PlayerCount.Builder builderForValue) {
      if (playerCountBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        playerCountBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 3;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.PlayerCount player_count = 3;</code>
     */
    public Builder mergePlayerCount(cloud.spawnery.agent.pb.PlayerCount value) {
      if (playerCountBuilder_ == null) {
        if (messageCase_ == 3 &&
            message_ != cloud.spawnery.agent.pb.PlayerCount.getDefaultInstance()) {
          message_ = cloud.spawnery.agent.pb.PlayerCount.newBuilder((cloud.spawnery.agent.pb.PlayerCount) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 3) {
          playerCountBuilder_.mergeFrom(value);
        } else {
          playerCountBuilder_.setMessage(value);
        }
      }
      messageCase_ = 3;
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.PlayerCount player_count = 3;</code>
     */
    public Builder clearPlayerCount() {
      if (playerCountBuilder_ == null) {
        if (messageCase_ == 3) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 3) {
          messageCase_ = 0;
          message_ = null;
        }
        playerCountBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.PlayerCount player_count = 3;</code>
     */
    public cloud.spawnery.agent.pb.PlayerCount.Builder getPlayerCountBuilder() {
      return internalGetPlayerCountFieldBuilder().getBuilder();
    }
    /**
     * <code>.spawnery.agent.v1alpha1.PlayerCount player_count = 3;</code>
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.PlayerCountOrBuilder getPlayerCountOrBuilder() {
      if ((messageCase_ == 3) && (playerCountBuilder_ != null)) {
        return playerCountBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 3) {
          return (cloud.spawnery.agent.pb.PlayerCount) message_;
        }
        return cloud.spawnery.agent.pb.PlayerCount.getDefaultInstance();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.PlayerCount player_count = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.PlayerCount, cloud.spawnery.agent.pb.PlayerCount.Builder, cloud.spawnery.agent.pb.PlayerCountOrBuilder> 
        internalGetPlayerCountFieldBuilder() {
      if (playerCountBuilder_ == null) {
        if (!(messageCase_ == 3)) {
          message_ = cloud.spawnery.agent.pb.PlayerCount.getDefaultInstance();
        }
        playerCountBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cloud.spawnery.agent.pb.PlayerCount, cloud.spawnery.agent.pb.PlayerCount.Builder, cloud.spawnery.agent.pb.PlayerCountOrBuilder>(
                (cloud.spawnery.agent.pb.PlayerCount) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 3;
      onChanged();
      return playerCountBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:spawnery.agent.v1alpha1.ServerMessage)
  }

  // @@protoc_insertion_point(class_scope:spawnery.agent.v1alpha1.ServerMessage)
  private static final cloud.spawnery.agent.pb.ServerMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.spawnery.agent.pb.ServerMessage();
  }

  public static cloud.spawnery.agent.pb.ServerMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServerMessage>
      PARSER = new com.google.protobuf.AbstractParser<ServerMessage>() {
    @java.lang.Override
    public ServerMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ServerMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServerMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.spawnery.agent.pb.ServerMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

