// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface StopBoostResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.StopBoostResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 removed = 1;</code>
   * @return The removed.
   */
  int getRemoved();
}
