---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spawnery-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - spawnery.cloud
  resources:
  - networks
  - servergroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spawnery.cloud
  resources:
  - networks/status
  - servergroups/finalizers
  - servergroups/status
  - servers/finalizers
  - servers/status
  verbs:
  - update
- apiGroups:
  - spawnery.cloud
  resources:
  - proxygroups
  verbs:
  - list
  - watch
- apiGroups:
  - spawnery.cloud
  resources:
  - servers
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
