#!/usr/bin/env bash
# Drives hack/chart-values-docs.sh against the schema and values checked into
# this tree; only the real files show a field drifting from its default.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
gen="$root/hack/chart-values-docs.sh"
page="$root/docs/reference/chart-values.md"
schema="$root/charts/spawnery/values.schema.json"
values="$root/charts/spawnery/values.yaml"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

failures=0
run() {
  local name="$1" want="$2"; shift 2
  local out status
  out="$("$@" 2>&1)" && status=0 || status=$?
  if [ "$status" -ne "$want" ]; then
    echo "FAIL $name: exit $status, want $want"
    printf '%s\n' "$out" | sed 's/^/    /'
    failures=$((failures + 1))
  else
    echo "ok   $name"
  fi
}

# Runs against the committed page before anything regenerates it: the drift it
# looks for is a default changed without `make manifests`.
if python3 - "$schema" "$values" "$page" <<'PY'
import html
import json
import re
import sys

import yaml

schema_path, values_path, page_path = sys.argv[1], sys.argv[2], sys.argv[3]

with open(schema_path) as f:
    schema = json.load(f)
with open(values_path) as f:
    values = yaml.safe_load(f) or {}

try:
    with open(page_path) as f:
        page = f.read()
except FileNotFoundError:
    print("FAIL every default shown matches values.yaml: %s does not exist yet -- run hack/chart-values-docs.sh" % page_path)
    sys.exit(1)

ROW_RE = re.compile(
    r'<tr><td><code>([^<]*)</code></td><td>.*?</td><td>(.*?)</td><td>.*?</td></tr>'
)


def format_value(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if v is None:
        return "null"
    if isinstance(v, (dict, list)):
        return yaml.safe_dump(v, default_flow_style=True, sort_keys=False, width=10**6).strip()
    return str(v)


def lookup(path, values):
    """path is a dotted key, possibly with '[]' segments for array items.
    An '[]' segment has no single default (values.yaml carries no example
    item), so it resolves to "absent" rather than to a value."""
    node = values
    for part in path.split("."):
        if part.endswith("[]"):
            return None, False
        if not isinstance(node, dict) or part not in node:
            return None, False
        node = node[part]
    return node, True


rows = {m.group(1): m.group(2) for m in ROW_RE.finditer(page)}
if not rows:
    print("FAIL every default shown matches values.yaml: no table rows found in %s" % page_path)
    sys.exit(1)

mismatches = []
for path, shown in rows.items():
    value, present = lookup(path, values)
    if not present:
        expected = ""
    else:
        expected = f"<code>{html.escape(format_value(value))}</code>"
    if shown != expected:
        mismatches.append((path, shown, expected))

if mismatches:
    print("FAIL every default shown matches values.yaml:")
    for path, shown, expected in mismatches:
        print(f"    {path}: page shows {shown!r}, values.yaml has {expected!r}")
    sys.exit(1)

print("ok   every default shown matches values.yaml")
PY
then
  :
else
  failures=$((failures + 1))
fi

# Otherwise a generator that wrote nothing leaves the committed copy to pass.
rm -f "$page"

run "the generator runs" 0 "$gen"

if [ -f "$page" ]; then
  echo "ok   the page was written this run"
else
  echo "FAIL the page was written this run: $page is missing after a fresh run"
  failures=$((failures + 1))
fi

first_line="$(head -1 "$page" 2>/dev/null || true)"
case "$first_line" in
  *"Generated by"*) echo "ok   the first line is the generated-by header" ;;
  *)
    echo "FAIL the first line is the generated-by header: got '$first_line'"
    failures=$((failures + 1))
    ;;
esac

if python3 - "$schema" "$page" <<'PY'
import json
import sys

schema_path, page_path = sys.argv[1], sys.argv[2]

with open(schema_path) as f:
    schema = json.load(f)
with open(page_path) as f:
    page = f.read()

paths = []


def walk(props, prefix):
    for name, prop_schema in (props or {}).items():
        path = f"{prefix}.{name}" if prefix else name
        paths.append(path)
        t = prop_schema.get("type")
        if t == "object" and "properties" in prop_schema:
            walk(prop_schema["properties"], path)
        elif t == "array":
            items = prop_schema.get("items", {}) or {}
            if items.get("type") == "object" and "properties" in items:
                walk(items["properties"], path + "[]")


walk(schema.get("properties", {}), "")

missing = [p for p in paths if f"<code>{p}</code>" not in page]
if missing:
    print("FAIL every leaf in values.schema.json appears in the page: missing " + ", ".join(missing))
    sys.exit(1)
print(f"ok   every leaf in values.schema.json appears in the page ({len(paths)} keys)")
PY
then
  :
else
  failures=$((failures + 1))
fi

# Starts from values.yaml, so it sees a key the schema lacks. Top-level only:
# `resources` is one row, and resources.requests.cpu rightly has none.
if python3 - "$values" "$page" <<'PY'
import sys

import yaml

values_path, page_path = sys.argv[1], sys.argv[2]

with open(values_path) as f:
    values = yaml.safe_load(f) or {}
with open(page_path) as f:
    page = f.read()

missing = [k for k in values if f"<code>{k}</code>" not in page]
if missing:
    print("FAIL every top-level key in values.yaml appears in the page: missing " + ", ".join(missing))
    sys.exit(1)
print(f"ok   every top-level key in values.yaml appears in the page ({len(values)} keys)")
PY
then
  :
else
  failures=$((failures + 1))
fi

if [ -f "$page" ] && cp "$page" "$tmp/first-run.md" && "$gen" > /dev/null && cp "$page" "$tmp/second-run.md"; then
  if diff -u "$tmp/first-run.md" "$tmp/second-run.md" > "$tmp/diff"; then
    echo "ok   two runs produce identical output"
  else
    echo "FAIL two runs produce identical output:"
    sed 's/^/    /' "$tmp/diff"
    failures=$((failures + 1))
  fi
else
  echo "FAIL two runs produce identical output: could not produce two runs to compare"
  failures=$((failures + 1))
fi

if [ "$failures" -ne 0 ]; then
  echo "$failures case(s) failed"
  exit 1
fi
echo "all cases passed"
