#!/usr/bin/env bash
# Drives hack/crd-docs.sh against the CRDs actually checked into this tree.
#
# There is no synthetic fixture: the interesting failure mode (Step 6 of the
# task this generator came out of) is a field renamed under the CRDs'
# noses, and the only way to catch that is to run the real generator against
# the real schema and let its own stop-list validation speak.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
gen="$root/hack/crd-docs.sh"
page="$root/docs/reference/crds.md"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

failures=0
run() {
  local name="$1" want="$2"; shift 2
  local out status
  out="$("$@" 2>&1)" && status=0 || status=$?
  if [ "$status" -ne "$want" ]; then
    echo "FAIL $name: exit $status, want $want"
    printf '%s\n' "$out" | sed 's/^/    /'
    failures=$((failures + 1))
  else
    echo "ok   $name"
  fi
}
has() {
  local name="$1" needle="$2"
  if grep -qF -- "$needle" "$page"; then
    echo "ok   $name"
  else
    echo "FAIL $name: $page does not contain '$needle'"
    failures=$((failures + 1))
  fi
}

# The page is removed before the run, not just read afterward: without this,
# a generator that exited before writing anything would leave the committed
# copy in place, and the next two cases would pass against that stale file
# instead of against this run's output.
rm -f "$page"

# The generator succeeds, and every stop-list entry in hack/crd-docs.sh
# resolved against the CRDs actually checked in here -- the case that
# matters most. A field renamed or moved out from under a stop-list path
# turns this red instead of silently expanding two hundred rows into the
# page; Step 6 of the task proves it by mutating a CRD in a throwaway
# worktree and watching this line fail by name.
run "the generator runs and every stop-list entry resolves" 0 "$gen"

if [ -f "$page" ]; then
  echo "ok   the page was written this run"
else
  echo "FAIL the page was written this run: $page is missing after a fresh run"
  failures=$((failures + 1))
fi

first_line="$(head -1 "$page" 2>/dev/null || true)"
case "$first_line" in
  *"Generated by"*) echo "ok   the first line is the generated-by header" ;;
  *)
    echo "FAIL the first line is the generated-by header: got '$first_line'"
    failures=$((failures + 1))
    ;;
esac

for kind in Network ServerGroup ProxyGroup Server ScaleBoost; do
  has "the page names $kind" "## $kind"
done

# The gap docs/superpowers/specs/2026-09-14-documentation-site-design.md
# names: these six fields appear in no page before this generator existed.
# Matched by their rendered <code> tag rather than the bare word: several of
# them ("type", "config") also appear in ordinary prose throughout the page.
for field in expose routing resources maxPlayers type config; do
  has "the page carries spec.$field" ">$field<"
done

# A description longer than one paragraph collapses everything after the
# first behind <details>, so a table of eight-word rows isn't broken up by
# the rare 300-word one. Network.spec.forwardingSecretRef is known
# multi-paragraph; Network.spec.defaults.minecraftVersion is known to be a
# single sentence, and must render with no <details> at all -- an empty
# "more" on every ordinary row would be worse than the wall of text it
# replaces.
row="$(grep -F '<code>forwardingSecretRef</code>' "$page" || true)"
case "$row" in
  *"<details>"*) echo "ok   a multi-paragraph description collapses behind <details>" ;;
  *)
    echo "FAIL a multi-paragraph description collapses behind <details>: no <details> in its row"
    failures=$((failures + 1))
    ;;
esac
row="$(grep -F '<code>defaults.minecraftVersion</code>' "$page" || true)"
case "$row" in
  *"<details>"*)
    echo "FAIL a single-paragraph description has no <details>: found one anyway"
    failures=$((failures + 1))
    ;;
  *) echo "ok   a single-paragraph description has no <details>" ;;
esac

if [ -f "$page" ] && cp "$page" "$tmp/first-run.md" && "$gen" > /dev/null && cp "$page" "$tmp/second-run.md"; then
  if diff -u "$tmp/first-run.md" "$tmp/second-run.md" > "$tmp/diff"; then
    echo "ok   two runs produce identical output"
  else
    echo "FAIL two runs produce identical output:"
    sed 's/^/    /' "$tmp/diff"
    failures=$((failures + 1))
  fi
else
  echo "FAIL two runs produce identical output: could not produce two runs to compare"
  failures=$((failures + 1))
fi

if [ "$failures" -ne 0 ]; then
  echo "$failures case(s) failed"
  exit 1
fi
echo "all cases passed"
