#!/usr/bin/env bash
# Drives hack/metrics-docs.sh against the operator's real metrics registry
# and the real chart. No synthetic fixture, for the same reason
# hack/crd-docs-test.sh and hack/chart-values-docs-test.sh have none: the
# interesting failure is a real alert naming a metric the real registry does
# not export, and only the real registry and the real chart show that.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
gen="$root/hack/metrics-docs.sh"
page="$root/docs/reference/metrics-and-alerts.md"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

failures=0
run() {
  local name="$1" want="$2"; shift 2
  local out status
  out="$("$@" 2>&1)" && status=0 || status=$?
  if [ "$status" -ne "$want" ]; then
    echo "FAIL $name: exit $status, want $want"
    printf '%s\n' "$out" | sed 's/^/    /'
    failures=$((failures + 1))
  else
    echo "ok   $name"
  fi
}
has() {
  local name="$1" needle="$2"
  if grep -qF -- "$needle" "$page"; then
    echo "ok   $name"
  else
    echo "FAIL $name: $page does not contain '$needle'"
    failures=$((failures + 1))
  fi
}

# The page is removed before the run, not just read afterward: without this,
# a generator that exited before writing anything would leave the committed
# copy in place, and the cases below would pass against that stale file
# instead of against this run's output.
rm -f "$page"

run "the generator runs" 0 "$gen"

if [ -f "$page" ]; then
  echo "ok   the page was written this run"
else
  echo "FAIL the page was written this run: $page is missing after a fresh run"
  failures=$((failures + 1))
fi

first_line="$(head -1 "$page" 2>/dev/null || true)"
case "$first_line" in
  *"Generated by"*) echo "ok   the first line is the generated-by header" ;;
  *)
    echo "FAIL the first line is the generated-by header: got '$first_line'"
    failures=$((failures + 1))
    ;;
esac

# Case 2, the one this generator exists for: every spawnery_ metric name that
# appears in a rendered alert expression also appears in the metrics table.
# An alert on a metric the operator does not export is a rule that never
# fires, and nothing else in this repository checks it. hack/metrics-docs.sh
# already refuses to write the page over a mismatch (see its own check), so
# this case re-derives the same answer independently, from the committed
# chart and the page just written, rather than trusting the generator's exit
# code to mean what it says.
if python3 - "$root/charts/spawnery" "$page" <<'PY'
import re
import subprocess
import sys

import yaml

chart_dir, page_path = sys.argv[1], sys.argv[2]

rendered = subprocess.run(
    [
        "helm", "template", "spawnery", chart_dir,
        "--namespace", "spawnery-system",
        "--set", "metrics.prometheusRule.enabled=true",
    ],
    check=True, capture_output=True, text=True,
).stdout

rule = None
for doc in yaml.safe_load_all(rendered):
    if isinstance(doc, dict) and doc.get("kind") == "PrometheusRule":
        rule = doc
        break
if rule is None:
    print("FAIL every metric named in an alert expression is documented: helm template produced no PrometheusRule")
    sys.exit(1)

alerted = set()
for group in rule["spec"]["groups"]:
    for r in group.get("rules", []):
        alerted.update(re.findall(r"spawnery_[A-Za-z0-9_]*", r.get("expr", "")))

with open(page_path) as f:
    page = f.read()
documented = set(re.findall(r"<code>(spawnery_[A-Za-z0-9_]*)</code>", page))

missing = sorted(alerted - documented)
if missing:
    print("FAIL every metric named in an alert expression is documented: " + ", ".join(missing))
    sys.exit(1)
print(f"ok   every metric named in an alert expression is documented ({len(alerted)} name(s) checked)")
PY
then
  :
else
  failures=$((failures + 1))
fi

# Case 3: every alert in the rendered PrometheusRule appears in the page with
# its severity and for-duration. Independent of the case above -- this one
# is about the page being complete, not about the rules being sound.
if python3 - "$root/charts/spawnery" "$page" <<'PY'
import subprocess
import sys

import yaml

chart_dir, page_path = sys.argv[1], sys.argv[2]

rendered = subprocess.run(
    [
        "helm", "template", "spawnery", chart_dir,
        "--namespace", "spawnery-system",
        "--set", "metrics.prometheusRule.enabled=true",
    ],
    check=True, capture_output=True, text=True,
).stdout

rule = None
for doc in yaml.safe_load_all(rendered):
    if isinstance(doc, dict) and doc.get("kind") == "PrometheusRule":
        rule = doc
        break
if rule is None:
    print("FAIL every alert appears with its severity and for-duration: helm template produced no PrometheusRule")
    sys.exit(1)

with open(page_path) as f:
    page = f.read()

missing = []
count = 0
for group in rule["spec"]["groups"]:
    for r in group.get("rules", []):
        name = r.get("alert")
        if not name:
            continue
        count += 1
        severity = r.get("labels", {}).get("severity", "")
        for_duration = r.get("for", "")
        needed = [f"### {name}", f"<code>{severity}</code>", f"<code>{for_duration}</code>"]
        if any(n not in page for n in needed):
            missing.append(name)

if missing:
    print("FAIL every alert appears with its severity and for-duration: " + ", ".join(missing))
    sys.exit(1)
print(f"ok   every alert appears with its severity and for-duration ({count} alert(s) checked)")
PY
then
  :
else
  failures=$((failures + 1))
fi

if [ -f "$page" ] && cp "$page" "$tmp/first-run.md" && "$gen" > /dev/null && cp "$page" "$tmp/second-run.md"; then
  if diff -u "$tmp/first-run.md" "$tmp/second-run.md" > "$tmp/diff"; then
    echo "ok   two runs produce identical output"
  else
    echo "FAIL two runs produce identical output:"
    sed 's/^/    /' "$tmp/diff"
    failures=$((failures + 1))
  fi
else
  echo "FAIL two runs produce identical output: could not produce two runs to compare"
  failures=$((failures + 1))
fi

if [ "$failures" -ne 0 ]; then
  echo "$failures case(s) failed"
  exit 1
fi
echo "all cases passed"
