apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docs-tls
spec:
  secretName: docs-tls
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  dnsNames:
    - docs.spawnery.cloud
